// Add any additional repositories for your dependencies here

repositories {
    exclusiveContent {
        forRepository {
            maven {
                name = 'glease'
                url = 'https://maven.glease.net/repos/releases/'
            }
        }
        filter {
            includeGroup('net.glease')
        }
    }
    mavenLocal()
}
