package gregtech.common.misc;

import static com.gtnewhorizon.gtnhlib.util.CommandUtils.literal;

import net.minecraft.command.ICommandSender;
import net.minecraft.entity.player.EntityPlayerMP;
import net.minecraft.util.ChatComponentText;
import net.minecraft.util.EnumChatFormatting;

import com.gtnewhorizon.gtnhlib.brigadier.BrigadierApi;
import com.mojang.brigadier.Command;
import com.mojang.brigadier.context.CommandContext;

/**
 * {@code /gtdebug} - developer/debug subcommands, gated behind op level 4 (or singleplayer cheats).
 */
public final class GTDebugCommand {

    private GTDebugCommand() {}

    // spotless:off
    public static void register() {
        BrigadierApi.getCommandDispatcher().register(literal("gtdebug")
                .requires(src -> src.canCommandSenderUseCommand(4, "gtdebug"))
                .executes(ctx -> tell(ctx, EnumChatFormatting.YELLOW + "Usage: /gtdebug <ore-showroom>"))

                .then(literal("ore-showroom")
                        .executes(ctx -> oreShowroom(ctx, false))
                        .then(literal("confirm").executes(ctx -> oreShowroom(ctx, true))))
        );
    }
    // spotless:on

    private static int oreShowroom(CommandContext<ICommandSender> ctx, boolean confirm) {
        if (ctx.getSource() instanceof EntityPlayerMP player) {
            OreShowroom.process(player, confirm);
        } else {
            tell(ctx, EnumChatFormatting.RED + "The ore showroom must be generated by a player.");
        }
        return Command.SINGLE_SUCCESS;
    }

    private static int tell(CommandContext<ICommandSender> ctx, String message) {
        ctx.getSource()
            .addChatMessage(new ChatComponentText(message));
        return Command.SINGLE_SUCCESS;
    }
}
