package gregtech.api.enums.materials2;

import com.ruling_0.materiallib.api.MaterialLibAPI;

import gregtech.api.material.GTMaterialProperties;
import gregtech.api.material.GTppData;

// Generated by scripts/mu/gen_materials.py; edit the script, not this file.
/// gtPlusPlus material declarations/merges, see [Materials2GtppMaterials]. Part->shape table (see
// `scripts/mu/gen_materials.py`'s gtpp-fold region for the full mapping and its exceptions):
/// bolt->shapeBolt, crushed(Centrifuged/Purified)->shapeCrushed*, dust(Impure/Pure/Small/Tiny)->shapeDust*,
// foil->shapeFoil, gearGt(Small)->shapeGearGt*, ingot(Hot)->shapeIngot*, nugget->shapeNugget,
/// plate(Dense/Double/Superdense)->shapePlate*, rawOre->shapeRawOre, ring->shapeRing, rotor->shapeRotor,
// screw->shapeScrew, spring(Small)->shapeSpring*, stick(Long)->shapeStick*, wireFine->shapeWireFine,
/// block->Materials2BlockShapes.shapeBlock, milled->Materials2GtppShapes.shapeMilled (new shape, no stage-02 equivalent
// -- see that class). `frameGt` stays legacy (gregtech policy, GTPP_LEGACY_ONLY_PREFIXES); `cell`/`cellPlasma` are
// deferred to commit 4 (need a cut-over fluid, GTPP_DEFERRED_PREFIXES); `pipeHuge`/`pipeMedium`/`wireGt01..16` are
// already gregtech-owned items on the three materials that carry them (GTPP_UNSUPPORTED_PREFIXES).
///
/// Melting/boiling points are Celsius in the gtpp dump; converted to Kelvin with `celsius_to_kelvin` (`round(c +
// 273.15)`, matching gtPlusPlus's own `MathUtils#celsiusToKelvin`).
public class Materials2GtppData1 {

    public static void init() {
        // spotless:off
        MaterialLibAPI.editMaterial("gregtech", "Almandine")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2GtppShapes.shapeMilled)
            .generateShape(Materials2Shapes.shapeRawOre)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 273, 51200, false, false, 0, false, "Al₂Fe₃Si₃O₁₂"));
        MaterialLibAPI.editMaterial("gregtech", "Alumina")
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(2, 120L, 2327, 2327, 64, true, false, 0, false, "Al₂O₃"));
        MaterialLibAPI.editMaterial("gregtech", "Aluminium")
            .generateShape(Materials2BlockShapes.shapeBlock)
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 1206, 1973, 128, true, false, 0, false, "Al"));
        MaterialLibAPI.editMaterial("gregtech", "Americium")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(1, 30L, 1722, 6069, 51200, false, false, 0, false, "Am"));
        MaterialLibAPI.editMaterial("gregtech", "Ammonia")
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 196, 240, 30000, false, false, 0, false, "NH₃"));
        MaterialLibAPI.editMaterial("gregtech", "Ammonium")
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 311, 427, 30000, false, false, 0, false, "NH₄"));
        MaterialLibAPI.editMaterial("gregtech", "Antimony")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 1176, 3885, 51200, false, false, 0, false, "Sb"));
        MaterialLibAPI.editMaterial("gregtech", "Argon")
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 356, 605, 51200, false, false, 0, false, "Ar"));
        MaterialLibAPI.editMaterial("gregtech", "Arsenic")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(1, 30L, 1363, 4633, 51200, false, false, 0, false, "As"));
        MaterialLibAPI.editMaterial("gregtech", "Barium")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(1, 30L, 1273, 4273, 51200, false, false, 0, false, "Ba"));
        MaterialLibAPI.editMaterial("gregtech", "Beryllium")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeStickLong)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(1, 30L, 1833, 6513, 64, false, false, 0, false, "Be"));
        MaterialLibAPI.editMaterial("gregtech", "Bismuth")
            .generateShape(Materials2BlockShapes.shapeBlock)
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 817, 2449, 64, false, false, 0, false, "Bi"));
        MaterialLibAPI.editMaterial("gregtech", "BlackSteel")
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapePlate)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 1473, 768, true, false, 0, false, "NiAuAgCu₃Fe₅C₃"));
        MaterialLibAPI.editMaterial("gregtech", "Boron")
            .generateShape(Materials2Shapes.shapeDust)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(2, 120L, 2622, 9669, 51200, false, false, 0, false, "B"));
        MaterialLibAPI.editMaterial("gregtech", "Bronze")
            .generateShape(Materials2Shapes.shapeDust)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 273, 192, false, false, 0, false, "SnCu₃"));
        MaterialLibAPI.editMaterial("gregtech", "Cadmium")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 867, 2649, 51200, false, false, 0, false, "Cd"));
        MaterialLibAPI.editMaterial("gregtech", "Caesium")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 574, 1477, 51200, false, false, 0, false, "Cs"));
        MaterialLibAPI.editMaterial("gregtech", "Calcium")
            .generateShape(Materials2BlockShapes.shapeBlock)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(1, 30L, 1388, 1388, 446, true, false, 0, false, "Ca"));
        MaterialLibAPI.editMaterial("gregtech", "Californium")
            .generateShape(Materials2Shapes.shapeDust)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 1172, 1745, 51200, false, true, 4, false, "Cf"));
        MaterialLibAPI.editMaterial("gregtech", "Carbon")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(4, 1920L, 4073, 15473, 64, false, false, 0, false, "C"));
        MaterialLibAPI.editMaterial("gregtech", "CastIron")
            .generateShape(Materials2Shapes.shapeDust)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(2, 120L, 2084, 7517, 384, false, false, 0, false, "Fe"));
        MaterialLibAPI.editMaterial("gregtech", "Cerium")
            .generateShape(Materials2BlockShapes.shapeBlock)
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(1, 30L, 1341, 1341, 51200, true, false, 0, false, "Ce"));
        MaterialLibAPI.editMaterial("gregtech", "Chalcopyrite")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .generateShape(Materials2GtppShapes.shapeMilled)
            .generateShape(Materials2Shapes.shapeRawOre)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 273, 51200, false, false, 0, false, "CuFeS₂"));
        MaterialLibAPI.editMaterial("gregtech", "Chlorine")
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 444, 957, 51200, false, false, 0, false, "Cl"));
        MaterialLibAPI.editMaterial("gregtech", "Chrome")
            .generateShape(Materials2BlockShapes.shapeBlock)
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(2, 120L, 2453, 1973, 256, true, false, 0, false, "Cr"));
        MaterialLibAPI.editMaterial("gregtech", "Clay")
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapePlate)
            .generateShape(Materials2Shapes.shapePlateDouble)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 273, 51200, false, false, 0, false, "Na₂LiAl₂Si₂O₇H₂O₂"));
        MaterialLibAPI.editMaterial("gregtech", "Cobalt")
            .generateShape(Materials2BlockShapes.shapeBlock)
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(2, 120L, 2041, 1973, 512, true, false, 0, false, "Co"));
        MaterialLibAPI.editMaterial("gregtech", "Copper")
            .generateShape(Materials2BlockShapes.shapeBlock)
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(1, 30L, 1630, 5701, 51200, false, false, 0, false, "Cu"));
        MaterialLibAPI.editMaterial("gregtech", "Dysprosium")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(1, 30L, 1685, 2835, 51200, false, false, 0, false, "Dy"));
        MaterialLibAPI.editMaterial("gregtech", "EnderPearl")
            .generateShape(Materials2Shapes.shapeDust)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 273, 16, false, false, 0, false, "BeK₄N₅Ma₆"));
        MaterialLibAPI.editMaterial("gregtech", "Erbium")
            .generateShape(Materials2BlockShapes.shapeBlock)
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(2, 120L, 2075, 2075, 51200, true, false, 0, false, "Er"));
        MaterialLibAPI.editMaterial("gregtech", "Europium")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(1, 30L, 1372, 1372, 51200, true, false, 0, false, "Eu"));
        MaterialLibAPI.editMaterial("gregtech", "Fluorine")
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 326, 485, 51200, false, false, 0, false, "F"));
        MaterialLibAPI.editMaterial("gregtech", "Force")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(4, 1920L, 4823, 7103, 51200, true, false, 0, false, "Fc⚙"));
        MaterialLibAPI.editMaterial("gregtech", "Gadolinium")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(1, 30L, 1858, 1858, 51200, true, false, 0, false, "Gd"));
        MaterialLibAPI.editMaterial("gregtech", "Galena")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 273, 51200, false, false, 0, false, "PbS"));
        MaterialLibAPI.editMaterial("gregtech", "Gallium")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 575, 1481, 64, false, false, 0, false, "Ga"));
        MaterialLibAPI.editMaterial("gregtech", "Glowstone")
            .generateShape(Materials2Shapes.shapeDust)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 273, 51200, false, false, 0, false, "??"));
        MaterialLibAPI.editMaterial("gregtech", "Gold")
            .generateShape(Materials2BlockShapes.shapeBlock)
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(1, 30L, 1610, 5621, 64, false, false, 0, false, "Au"));
        MaterialLibAPI.editMaterial("gregtech", "Grossular")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2GtppShapes.shapeMilled)
            .generateShape(Materials2Shapes.shapeRawOre)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 273, 51200, false, false, 0, false, "Ca₃Al₂Si₃O₁₂"));
        MaterialLibAPI.editMaterial("gregtech", "Hafnium")
            .generateShape(Materials2Shapes.shapeDust)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(2, 120L, 2423, 5673, 51200, false, false, 0, false, "Hf"));
        MaterialLibAPI.editMaterial("gregtech", "Helium")
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 274, 277, 51200, false, false, 0, false, "He"));
        MaterialLibAPI.editMaterial("gregtech", "Holmium")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(1, 30L, 2007, 2007, 51200, true, false, 0, false, "Ho"));
        MaterialLibAPI.editMaterial("gregtech", "Hydrogen")
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 287, 329, 51200, false, false, 0, false, "H"));
        MaterialLibAPI.editMaterial("gregtech", "Indium")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 702, 1989, 51200, false, false, 0, false, "In"));
        MaterialLibAPI.editMaterial("gregtech", "InfusedAir")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 273, 64, false, false, 0, false, "??"));
        MaterialLibAPI.editMaterial("gregtech", "InfusedEarth")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 273, 256, false, false, 0, false, "??"));
        MaterialLibAPI.editMaterial("gregtech", "InfusedEntropy")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 273, 64, false, false, 0, false, "??"));
        MaterialLibAPI.editMaterial("gregtech", "InfusedFire")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 273, 64, false, false, 0, false, "??"));
        MaterialLibAPI.editMaterial("gregtech", "InfusedOrder")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 273, 64, false, false, 0, false, "??"));
        MaterialLibAPI.editMaterial("gregtech", "InfusedWater")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 273, 64, false, false, 0, false, "??"));
        MaterialLibAPI.editMaterial("gregtech", "Invar")
            .generateShape(Materials2Shapes.shapeDust)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 273, 256, false, false, 0, false, "Fe₂Ni"));
        MaterialLibAPI.editMaterial("gregtech", "Iodine")
            .generateShape(Materials2BlockShapes.shapeBlock)
            .generateShape(Materials2Shapes.shapeBolt)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .generateShape(Materials2Shapes.shapeGearGt)
            .generateShape(Materials2Shapes.shapeIngot)
            .generateShape(Materials2Shapes.shapeNugget)
            .generateShape(Materials2Shapes.shapePlate)
            .generateShape(Materials2Shapes.shapePlateDense)
            .generateShape(Materials2Shapes.shapePlateDouble)
            .generateShape(Materials2Shapes.shapeRing)
            .generateShape(Materials2Shapes.shapeRotor)
            .generateShape(Materials2Shapes.shapeScrew)
            .generateShape(Materials2Shapes.shapeStick)
            .generateShape(Materials2Shapes.shapeStickLong)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 387, 457, 51200, false, false, 0, false, "I"));
        MaterialLibAPI.editMaterial("gregtech", "Iridium")
            .generateShape(Materials2BlockShapes.shapeBlock)
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(2, 120L, 2992, 4773, 2560, true, false, 0, false, "Ir"));
        MaterialLibAPI.editMaterial("gregtech", "Iron")
            .generateShape(Materials2BlockShapes.shapeBlock)
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(2, 120L, 2084, 7517, 256, false, false, 0, false, "Fe"));
        MaterialLibAPI.editMaterial("gregtech", "Kanthal")
            .generateShape(Materials2Shapes.shapeDust)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(2, 120L, 2073, 2073, 64, true, false, 0, false, "FeAlCr"));
        MaterialLibAPI.editMaterial("gregtech", "Krypton")
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 116, 120, 51200, false, false, 0, false, "Kr"));
        MaterialLibAPI.editMaterial("gregtech", "Lanthanum")
            .generateShape(Materials2BlockShapes.shapeBlock)
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(1, 30L, 1466, 1466, 51200, true, false, 0, false, "La"));
        MaterialLibAPI.editMaterial("gregtech", "Lead")
            .generateShape(Materials2BlockShapes.shapeBlock)
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 873, 2673, 64, false, false, 0, false, "Pb"));
        MaterialLibAPI.editMaterial("gregtech", "Lithium")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 727, 2089, 51200, false, false, 0, false, "Li"));
        // spotless:on
    }

    private Materials2GtppData1() {}
}
