// Generated by scripts/mu/gen_shape_data.py; edit the script, not this file.
package gregtech.api.enums.materials2;

import gregtech.api.material.GTShapeProperties;

/// The per-form data GregTech attaches to its MaterialLib shapes: how much material one item of the shape
/// holds, how it unifies, which texture slot it draws, and the rest of what a form knows about itself
/// independently of the material taking it.
///
/// Set on the shape objects directly rather than through
/// `com.ruling_0.materiallib.api.MaterialLibAPI#editShape`: these are GregTech's own shapes, so this
/// declares their data. The edit path addresses a shape by name and applies after unification, which is
/// what another mod changing someone else's shape needs and would wrongly let this beat a competing
/// owner's declaration. Runs inside `com.ruling_0.materiallib.api.MaterialRegistrationEvent`, after the
/// shape declarations and before shapes resolve, while the shapes are still mutable.
///
/// A value equal to the [gregtech.api.enums.OrePrefixBuilder] default is omitted, since the matching
/// [GTShapeProperties] key carries the same default.
///
/// [GTShapeProperties#SECONDARY_MATERIAL] and [GTShapeProperties#ASPECTS] are not emitted here: both are
/// object-valued, so declaring them means naming materials and aspect constants rather than copying a
/// scalar, and both are still read off the prefix. They move separately.
public final class Materials2ShapeData {

    private Materials2ShapeData() {}

    public static void init() {
        Materials2BlockShapes.block.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 32659200L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 71)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Block of %s")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2BlockShapes.blockCasing.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 32659200L)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Bolted %s Casing")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.SELF_REFERENCING, true)
            .setProperty(GTShapeProperties.CONTAINER, true);
        Materials2BlockShapes.blockCasingAdvanced.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 32659200L)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Rebolted %s Casing")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.SELF_REFERENCING, true)
            .setProperty(GTShapeProperties.CONTAINER, true);
        Materials2Shapes.bolt.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 453600L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 26)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 6)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s Bolt")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2PipeShapes.cableGt01.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 1814400L)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "1x %s Cable")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2PipeShapes.cableGt02.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 3628800L)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "2x %s Cable")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2PipeShapes.cableGt04.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 7257600L)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "4x %s Cable")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2PipeShapes.cableGt08.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 14515200L)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "8x %s Cable")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2PipeShapes.cableGt12.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 21772800L)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "12x %s Cable")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2PipeShapes.cableGt16.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 29030400L)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "16x %s Cable")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2CellShapes.cell.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 3628800L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 30)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 272)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s Cell")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.SELF_REFERENCING, true)
            .setProperty(GTShapeProperties.CONTAINER, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2CellShapes.cellHydroCracked1.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 3628800L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 30)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Lightly Hydro-Cracked %s Cell")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.SELF_REFERENCING, true)
            .setProperty(GTShapeProperties.CONTAINER, true);
        Materials2CellShapes.cellHydroCracked2.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 3628800L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 30)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Moderately Hydro-Cracked %s Cell")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.SELF_REFERENCING, true)
            .setProperty(GTShapeProperties.CONTAINER, true);
        Materials2CellShapes.cellHydroCracked3.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 3628800L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 30)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Severely Hydro-Cracked %s Cell")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.SELF_REFERENCING, true)
            .setProperty(GTShapeProperties.CONTAINER, true);
        Materials2CellShapes.cellMolten.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 3628800L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 31)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 64)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Molten %s Cell")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.SELF_REFERENCING, true)
            .setProperty(GTShapeProperties.CONTAINER, true)
            .setProperty(GTShapeProperties.HEAT_DAMAGE, 3.0F);
        Materials2CellShapes.cellPlasma.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 3628800L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 31)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 32)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s Plasma Cell")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.SELF_REFERENCING, true)
            .setProperty(GTShapeProperties.CONTAINER, true)
            .setProperty(GTShapeProperties.HEAT_DAMAGE, 6.0F);
        Materials2CellShapes.cellPlasmaLight // from prefix cellPlasma
            .setProperty(GTShapeProperties.MATERIAL_AMOUNT, 3628800L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 31)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 32)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s Plasma Cell")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.SELF_REFERENCING, true)
            .setProperty(GTShapeProperties.CONTAINER, true)
            .setProperty(GTShapeProperties.HEAT_DAMAGE, 6.0F);
        Materials2CellShapes.cellSteamCracked1.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 3628800L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 30)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Lightly Steam-Cracked %s Cell")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.SELF_REFERENCING, true)
            .setProperty(GTShapeProperties.CONTAINER, true);
        Materials2CellShapes.cellSteamCracked2.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 3628800L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 30)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Moderately Steam-Cracked %s Cell")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.SELF_REFERENCING, true)
            .setProperty(GTShapeProperties.CONTAINER, true);
        Materials2CellShapes.cellSteamCracked3.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 3628800L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 30)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Severely Steam-Cracked %s Cell")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.SELF_REFERENCING, true)
            .setProperty(GTShapeProperties.CONTAINER, true);
        Materials2Shapes.crushed.setProperty(GTShapeProperties.TEXTURE_INDEX, 5)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 8)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Crushed %s Ore")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true);
        Materials2Shapes.crushedCentrifuged.setProperty(GTShapeProperties.TEXTURE_INDEX, 7)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 8)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Centrifuged %s Ore")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true);
        Materials2Shapes.crushedPurified.setProperty(GTShapeProperties.TEXTURE_INDEX, 6)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 8)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Purified %s Ore")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true);
        Materials2Shapes.dust.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 3628800L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 2)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 15)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s Dust")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true);
        Materials2Shapes.dustImpure.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 3628800L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 3)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 8)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Impure Pile of %s Dust")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true);
        Materials2Shapes.dustPure.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 3628800L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 4)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 8)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Purified Pile of %s Dust")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true);
        Materials2Shapes.dustSmall.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 907200L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 1)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 15)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Small Pile of %s Dust")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true);
        Materials2Shapes.dustTiny.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 403200L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 0)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 15)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Tiny Pile of %s Dust")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true);
        Materials2Shapes.foil.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 907200L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 29)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 2)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s Foil")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2PipeShapes.frameGt.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 7257600L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 83)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s Frame Box")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true)
            .setProperty(GTShapeProperties.SKIP_ACTIVE_UNIFICATION, true);
        Materials2Shapes.gearGt.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 14515200L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 63)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 128)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s Gear")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.gearGtSmall.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 3628800L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 52)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 128)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Small %s Gear")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.gem.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 3628800L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 8)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 4)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.SELF_REFERENCING, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.gemChipped.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 907200L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 59)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 4)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Chipped %s")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.SELF_REFERENCING, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.gemExquisite.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 14515200L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 62)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 4)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Exquisite %s")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.SELF_REFERENCING, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.gemFlawed.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 1814400L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 60)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 4)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Flawed %s")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.SELF_REFERENCING, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.gemFlawless.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 7257600L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 61)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 4)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Flawless %s")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.SELF_REFERENCING, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.ingot.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 3628800L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 11)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 2)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s Ingot")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true);
        Materials2Shapes.ingotHot.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 3628800L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 12)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 2)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Hot %s Ingot")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.HEAT_DAMAGE, 3.0F);
        Materials2Shapes.itemCasing.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 1814400L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 10)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 6)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s Casing")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2PipeShapes.itemPipeHuge // from prefix pipeHuge
            .setProperty(GTShapeProperties.MATERIAL_AMOUNT, 43545600L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 82)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Huge %s Pipe")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true)
            .setProperty(GTShapeProperties.SKIP_ACTIVE_UNIFICATION, true);
        Materials2PipeShapes.itemPipeLarge // from prefix pipeLarge
            .setProperty(GTShapeProperties.MATERIAL_AMOUNT, 21772800L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 81)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Large %s Pipe")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true)
            .setProperty(GTShapeProperties.SKIP_ACTIVE_UNIFICATION, true);
        Materials2PipeShapes.itemPipeMedium // from prefix pipeMedium
            .setProperty(GTShapeProperties.MATERIAL_AMOUNT, 10886400L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 80)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Medium %s Pipe")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true)
            .setProperty(GTShapeProperties.SKIP_ACTIVE_UNIFICATION, true);
        Materials2PipeShapes.itemPipeRestrictiveHuge // from prefix pipeRestrictiveHuge
            .setProperty(GTShapeProperties.MATERIAL_AMOUNT, 43545600L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 82)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Huge Restrictive %s Pipe")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true)
            .setProperty(GTShapeProperties.SKIP_ACTIVE_UNIFICATION, true);
        Materials2PipeShapes.itemPipeRestrictiveLarge // from prefix pipeRestrictiveLarge
            .setProperty(GTShapeProperties.MATERIAL_AMOUNT, 21772800L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 81)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Large Restrictive %s Pipe")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true)
            .setProperty(GTShapeProperties.SKIP_ACTIVE_UNIFICATION, true);
        Materials2PipeShapes.itemPipeRestrictiveMedium // from prefix pipeRestrictiveMedium
            .setProperty(GTShapeProperties.MATERIAL_AMOUNT, 10886400L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 80)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Medium Restrictive %s Pipe")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true)
            .setProperty(GTShapeProperties.SKIP_ACTIVE_UNIFICATION, true);
        Materials2PipeShapes.itemPipeRestrictiveSmall // from prefix pipeRestrictiveSmall
            .setProperty(GTShapeProperties.MATERIAL_AMOUNT, 3628800L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 79)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Small Restrictive %s Pipe")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true)
            .setProperty(GTShapeProperties.SKIP_ACTIVE_UNIFICATION, true);
        Materials2PipeShapes.itemPipeRestrictiveTiny // from prefix pipeRestrictiveTiny
            .setProperty(GTShapeProperties.MATERIAL_AMOUNT, 1814400L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 78)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Tiny Restrictive %s Pipe")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true)
            .setProperty(GTShapeProperties.SKIP_ACTIVE_UNIFICATION, true);
        Materials2PipeShapes.itemPipeSmall // from prefix pipeSmall
            .setProperty(GTShapeProperties.MATERIAL_AMOUNT, 3628800L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 79)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Small %s Pipe")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true)
            .setProperty(GTShapeProperties.SKIP_ACTIVE_UNIFICATION, true);
        Materials2PipeShapes.itemPipeTiny // from prefix pipeTiny
            .setProperty(GTShapeProperties.MATERIAL_AMOUNT, 1814400L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 78)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Tiny %s Pipe")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true)
            .setProperty(GTShapeProperties.SKIP_ACTIVE_UNIFICATION, true);
        Materials2Shapes.lens.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 2721600L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 24)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 4)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s Lens")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.milled.setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 8)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Milled %s Ore")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true);
        Materials2Shapes.nugget.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 403200L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 9)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 2)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s Nugget")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true);
        Materials2OreShapes.ore.setProperty(GTShapeProperties.TEXTURE_INDEX, 68)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 8)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s Ore")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true);
        Materials2OreShapes.oreSmall.setProperty(GTShapeProperties.TEXTURE_INDEX, 67)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 8)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Small %s Ore")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true);
        Materials2PipeShapes.pipeHuge.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 43545600L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 82)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Huge %s Pipe")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true)
            .setProperty(GTShapeProperties.SKIP_ACTIVE_UNIFICATION, true);
        Materials2PipeShapes.pipeLarge.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 21772800L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 81)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Large %s Pipe")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true)
            .setProperty(GTShapeProperties.SKIP_ACTIVE_UNIFICATION, true);
        Materials2PipeShapes.pipeMedium.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 10886400L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 80)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Medium %s Pipe")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true)
            .setProperty(GTShapeProperties.SKIP_ACTIVE_UNIFICATION, true);
        Materials2PipeShapes.pipeNonuple.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 32659200L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 85)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Nonuple %s Pipe")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true)
            .setProperty(GTShapeProperties.SKIP_ACTIVE_UNIFICATION, true);
        Materials2PipeShapes.pipeQuadruple.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 43545600L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 84)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Quadruple %s Pipe")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true)
            .setProperty(GTShapeProperties.SKIP_ACTIVE_UNIFICATION, true);
        Materials2PipeShapes.pipeSmall.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 3628800L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 79)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Small %s Pipe")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true)
            .setProperty(GTShapeProperties.SKIP_ACTIVE_UNIFICATION, true);
        Materials2PipeShapes.pipeTiny.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 1814400L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 78)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Tiny %s Pipe")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true)
            .setProperty(GTShapeProperties.SKIP_ACTIVE_UNIFICATION, true);
        Materials2Shapes.plate.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 3628800L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 17)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 6)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s Plate")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.plateDense.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 32659200L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 22)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 2)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Dense %s Plate")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.plateDouble.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 7257600L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 18)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 2)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Double %s Plate")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.plateQuadruple.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 14515200L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 20)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 2)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Quadruple %s Plate")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.plateQuintuple.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 18144000L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 21)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 2)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Quintuple %s Plate")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.plateSuperdense.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 232243200L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 125)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 2)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Superdense %s Plate")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.plateTriple.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 10886400L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 19)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 2)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Triple %s Plate")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.rawOre.setProperty(GTShapeProperties.TEXTURE_INDEX, 64)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 8)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Raw %s Ore")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true);
        Materials2Shapes.ring.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 907200L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 28)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 2)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s Ring")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.rotor.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 15422400L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 53)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 128)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s Rotor")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.round.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 403200L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 25)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 2)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s Round")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.screw.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 453600L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 27)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 6)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s Screw")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2BlockShapes.sheetmetal.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 7257600L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 86)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 2)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s Sheetmetal")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.spring.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 3628800L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 56)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 2)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s Spring")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.springSmall.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 907200L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 55)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 2)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Small %s Spring")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.stick.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 1814400L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 23)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 6)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s Rod")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.stickLong.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 3628800L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 54)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 6)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Long %s Rod")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.toolHeadBuzzSaw.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 14515200L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 48)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 64)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s Buzzsaw Blade")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.toolHeadChainsaw.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 7257600L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 41)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 64)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s Chainsaw Tip")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.toolHeadDrill.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 14515200L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 40)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 64)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s Drill Tip")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.toolHeadFile.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 7257600L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 38)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 64)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s File Head")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.toolHeadHammer.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 21772800L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 37)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 64)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s Hammer Head")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.toolHeadSaw.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 7257600L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 39)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 64)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s Saw Blade")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.toolHeadWrench.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 14515200L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 42)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 64)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s Wrench Tip")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.turbineBlade.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 21772800L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 100)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 64)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "%s Turbine Blade")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2Shapes.wireFine.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 453600L)
            .setProperty(GTShapeProperties.TEXTURE_INDEX, 51)
            .setProperty(GTShapeProperties.MATERIAL_GENERATION_BITS, 2)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "Fine %s Wire")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2PipeShapes.wireGt01.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 1814400L)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "1x %s Wire")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2PipeShapes.wireGt02.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 3628800L)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "2x %s Wire")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2PipeShapes.wireGt04.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 7257600L)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "4x %s Wire")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2PipeShapes.wireGt08.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 14515200L)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "8x %s Wire")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2PipeShapes.wireGt12.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 21772800L)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "12x %s Wire")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
        Materials2PipeShapes.wireGt16.setProperty(GTShapeProperties.MATERIAL_AMOUNT, 29030400L)
            .setProperty(GTShapeProperties.LOCAL_NAME_FORMAT, "16x %s Wire")
            .setProperty(GTShapeProperties.UNIFIABLE, true)
            .setProperty(GTShapeProperties.MATERIAL_BASED, true)
            .setProperty(GTShapeProperties.RECYCLABLE, true);
    }
}
