package gregtech.api.enums.materials2;

import java.util.List;

import com.ruling_0.materiallib.api.MaterialLibAPI;

import gregtech.api.material.GTMaterialProperties;
import gregtech.api.material.GTppData;
import gregtech.api.material.MaterialRef;
import gregtech.api.material.MaterialRefStack;

// Generated by scripts/mu/gen_materials.py; edit the script, not this file.
/// gtPlusPlus material declarations/merges, see [Materials2GtppMaterials]. Part->shape table (see
// `scripts/mu/gen_materials.py`'s gtpp-fold region for the full mapping and its exceptions):
/// bolt->shapeBolt, crushed(Centrifuged/Purified)->shapeCrushed*, dust(Impure/Pure/Small/Tiny)->shapeDust*,
// foil->shapeFoil, gearGt(Small)->shapeGearGt*, ingot(Hot)->shapeIngot*, nugget->shapeNugget,
/// plate(Dense/Double/Superdense)->shapePlate*, rawOre->shapeRawOre, ring->shapeRing, rotor->shapeRotor,
// screw->shapeScrew, spring(Small)->shapeSpring*, stick(Long)->shapeStick*, wireFine->shapeWireFine,
/// block->Materials2BlockShapes.shapeBlock, milled->Materials2GtppShapes.shapeMilled (new shape, no stage-02 equivalent
// -- see that class). `frameGt` stays legacy (gregtech policy, GTPP_LEGACY_ONLY_PREFIXES); `cell`/`cellPlasma` are
// deferred to commit 4 (need a cut-over fluid, GTPP_DEFERRED_PREFIXES); `pipeHuge`/`pipeMedium`/`wireGt01..16` are
// already gregtech-owned items on the three materials that carry them (GTPP_UNSUPPORTED_PREFIXES).
///
/// Melting/boiling points are Celsius in the gtpp dump; converted to Kelvin with `celsius_to_kelvin` (`round(c +
// 273.15)`, matching gtPlusPlus's own `MathUtils#celsiusToKelvin`).
public class Materials2GtppData2 {

    public static void init() {
        // spotless:off
        MaterialLibAPI.editMaterial("gregtech", "Lutetium")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(2, 120L, 2198, 2198, 51200, true, false, 0, false, "Lu", 71L, 103L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Magic")
            .setProperty(GTMaterialProperties.GTPP, new GTppData(5, 7680L, 5273, 20273, 5120, false, false, 0, false, "Ma", 0L, 0L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Magnesium")
            .generateShape(Materials2BlockShapes.shapeBlock)
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 1196, 3965, 51200, false, false, 0, false, "Mg", 12L, 12L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Manganese")
            .generateShape(Materials2BlockShapes.shapeBlock)
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(1, 30L, 1792, 6349, 512, false, false, 0, false, "Mn", 25L, 30L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "MeatRaw")
            .generateShape(Materials2Shapes.shapeDust)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 273, 51200, false, false, 0, false, "??", 43L, 55L, "SOLID", false, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Mercury")
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 507, 1209, 51200, false, false, 0, false, "Hg", 80L, 120L, "LIQUID", true, true, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Molybdenum")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(3, 480L, 3169, 11857, 512, false, false, 0, false, "Mo", 42L, 53L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Monazite")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2GtppShapes.shapeMilled)
            .generateShape(Materials2Shapes.shapeRawOre)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 273, 51200, false, false, 0, false, "PO₄", 26L, 32L, "SOLID", false, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Naquadah")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(5, 7680L, 5673, 5673, 1280, true, false, 0, false, "Nq", 130L, 200L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "NaquadahEnriched")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(4, 1920L, 4773, 4773, 1280, true, false, 0, false, "??", 43L, 55L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Naquadria")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(9, 1966080L, 9273, 9273, 512, true, false, 0, false, "??", 43L, 55L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Neodymium")
            .generateShape(Materials2BlockShapes.shapeBlock)
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(1, 30L, 1570, 1570, 512, true, false, 0, false, "Nd", 60L, 84L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Neon")
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 25, 27, 51200, false, false, 0, false, "Ne", 10L, 10L, "PURE_GAS", true, true, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "NetherQuartz")
            .generateShape(Materials2BlockShapes.shapeBlock)
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 273, 32, false, false, 0, false, "??", 43L, 55L, "SOLID", false, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Netherrack")
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2GtppShapes.shapeMilled)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 273, 51200, false, false, 0, false, "??", 43L, 55L, "SOLID", false, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Nichrome")
            .generateShape(Materials2Shapes.shapeDust)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(2, 120L, 2973, 2973, 64, true, false, 0, false, "Ni₄Cr", 27L, 29L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Nickel")
            .generateShape(Materials2BlockShapes.shapeBlock)
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .generateShape(Materials2GtppShapes.shapeMilled)
            .generateShape(Materials2Shapes.shapeRawOre)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(1, 30L, 2001, 7185, 64, false, false, 0, false, "Ni", 28L, 30L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Niobium")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(3, 480L, 3023, 3023, 51200, true, false, 0, false, "Nb", 41L, 53L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Nitrogen")
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 336, 525, 51200, false, false, 0, false, "N", 7L, 7L, "GAS", true, true, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Osmiridium")
            .generateShape(Materials2Shapes.shapeDust)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(3, 480L, 3773, 4773, 1600, true, false, 0, false, "Ir₃Os", 76L, 114L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Osmium")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(3, 480L, 3579, 4773, 1280, true, false, 0, false, "Os", 76L, 114L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Oxygen")
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 327, 489, 51200, false, false, 0, false, "O", 8L, 8L, "GAS", true, true, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Palladium")
            .generateShape(Materials2BlockShapes.shapeBlock)
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(2, 120L, 2101, 2101, 512, true, false, 0, false, "Pd", 46L, 60L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Pentlandite")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2GtppShapes.shapeMilled)
            .generateShape(Materials2Shapes.shapeRawOre)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 273, 51200, false, false, 0, false, "Ni₉S₈", 22L, 23L, "SOLID", false, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Phosphorus")
            .generateShape(Materials2Shapes.shapeDust)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 590, 1541, 51200, false, false, 0, false, "P", 15L, 15L, "SOLID", false, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Plastic")
            .generateShape(Materials2Shapes.shapeDust)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 673, 1873, 32, false, false, 0, false, "CH₂", 2L, 2L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Platinum")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2GtppShapes.shapeMilled)
            .generateShape(Materials2Shapes.shapeRawOre)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(2, 120L, 2314, 8437, 64, false, false, 0, false, "Pt", 78L, 117L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Plutonium241")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 1185, 3921, 512, false, false, 0, false, "Pu₂₄₁", 94L, 149L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Polytetrafluoroethylene")
            .generateShape(Materials2Shapes.shapeDust)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 873, 2673, 32, false, false, 0, false, "C₂F₄", 8L, 8L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Potassium")
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 609, 1617, 51200, false, false, 0, false, "K", 19L, 20L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "PotassiumNitrate")
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 424, 877, 138000, false, false, 0, false, "KNO3", 11L, 11L, "SOLID", true, false, List.of(new MaterialRefStack(new MaterialRef("Potassium"), 1L), new MaterialRefStack(new MaterialRef("Nitrogen"), 1L), new MaterialRefStack(new MaterialRef("Oxygen"), 3L))));
        MaterialLibAPI.editMaterial("gregtech", "Praseodymium")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(1, 30L, 1481, 1481, 51200, true, false, 0, false, "Pr", 59L, 81L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Promethium")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(1, 30L, 1588, 1588, 51200, true, false, 0, false, "Pm", 61L, 83L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Pyrope")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2GtppShapes.shapeMilled)
            .generateShape(Materials2Shapes.shapeRawOre)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 273, 51200, false, false, 0, false, "Al₂Mg₃Si₃O₁₂", 10L, 10L, "SOLID", false, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Radon")
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 475, 1081, 51200, false, false, 0, false, "Rn", 86L, 134L, "GAS", true, true, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Redstone")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2GtppShapes.shapeMilled)
            .generateShape(Materials2Shapes.shapeRawOre)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 773, 2273, 51200, false, false, 0, false, "SiFeS₂₅CrAl₂O₃Hg₃", 36L, 48L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Rhodium")
            .generateShape(Materials2BlockShapes.shapeBlock)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(2, 120L, 2239, 4000, 51200, false, false, 0, false, "Rh", 45L, 58L, "SOLID", true, true, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Rubidium")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 585, 1521, 51200, false, false, 0, false, "Rb", 37L, 48L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Ruthenium")
            .generateShape(Materials2BlockShapes.shapeBlock)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(2, 120L, 2523, 4173, 51200, false, false, 0, false, "Ru", 44L, 57L, "SOLID", true, true, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "SaltWater")
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 425, 882, 72000, false, false, 0, false, "(H₂O)₃(NaCl)", 9L, 9L, "PURE_LIQUID", false, false, List.of(new MaterialRefStack(new MaterialRef("Water"), 3L), new MaterialRefStack(new MaterialRef("SodiumChloride"), 1L))));
        MaterialLibAPI.editMaterial("gregtech", "Samarium")
            .generateShape(Materials2BlockShapes.shapeBlock)
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(1, 30L, 1618, 1618, 51200, true, false, 0, false, "Sm", 62L, 88L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Scandium")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(2, 120L, 2087, 2087, 51200, true, false, 0, false, "Sc", 21L, 24L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Silicon")
            .generateShape(Materials2BlockShapes.shapeBlock)
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(2, 120L, 2546, 2546, 51200, true, false, 0, false, "Si", 14L, 14L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "SiliconDioxide")
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 273, 51200, false, false, 0, false, "SiO₂", 10L, 10L, "SOLID", false, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Silver")
            .generateShape(Materials2BlockShapes.shapeBlock)
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(1, 30L, 1507, 5209, 64, false, false, 0, false, "Ag", 47L, 60L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Sodium")
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .generateShape(Materials2Shapes.shapePlate)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 643, 1753, 51200, false, false, 0, false, "Na", 11L, 11L, "LIQUID", true, true, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "SodiumNitrate")
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 435, 922, 104000, false, false, 0, false, "NaNO3", 8L, 8L, "SOLID", true, false, List.of(new MaterialRefStack(new MaterialRef("Sodium"), 1L), new MaterialRefStack(new MaterialRef("Nitrogen"), 1L), new MaterialRefStack(new MaterialRef("Oxygen"), 3L))));
        MaterialLibAPI.editMaterial("gregtech", "SoulSand")
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 273, 51200, false, false, 0, false, "??", 43L, 55L, "SOLID", false, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Spessartine")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2GtppShapes.shapeMilled)
            .generateShape(Materials2Shapes.shapeRawOre)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 273, 51200, false, false, 0, false, "Al₂Mn₃Si₃O₁₂", 11L, 12L, "SOLID", false, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Sphalerite")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2GtppShapes.shapeMilled)
            .generateShape(Materials2Shapes.shapeRawOre)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 273, 51200, false, false, 0, false, "ZnS", 23L, 25L, "SOLID", false, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "StainlessSteel")
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapePlate)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 1973, 480, true, false, 0, false, "Fe₆CrMnNi", 25L, 29L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Steel")
            .generateShape(Materials2Shapes.shapeDust)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(2, 120L, 2084, 1273, 512, true, false, 0, false, "Fe₅C", 26L, 30L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Stone")
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 273, 32, false, false, 0, false, "??", 43L, 55L, "SOLID", false, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Strontium")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(1, 30L, 1323, 4473, 51200, false, false, 0, false, "Sr", 38L, 49L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Sulfur")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 661, 1825, 51200, false, false, 0, false, "S", 16L, 16L, "SOLID", false, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Tantalum")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(3, 480L, 3563, 3563, 2560, true, false, 0, false, "Ta", 73L, 107L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Tellurium")
            .generateShape(Materials2BlockShapes.shapeBlock)
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 722, 1262, 51200, false, false, 0, false, "Te", 52L, 76L, "SOLID", true, true, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Terbium")
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(1, 30L, 1902, 1902, 51200, true, false, 0, false, "Tb", 65L, 93L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Thaumium")
            .generateShape(Materials2BlockShapes.shapeBlock)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(0, 16L, 273, 273, 256, false, false, 0, false, "FeMa", 26L, 30L, "SOLID", true, false, List.of()));
        MaterialLibAPI.editMaterial("gregtech", "Thorium")
            .generateShape(Materials2BlockShapes.shapeBlock)
            .generateShape(Materials2Shapes.shapeCrushed)
            .generateShape(Materials2Shapes.shapeCrushedPurified)
            .generateShape(Materials2Shapes.shapeDust)
            .generateShape(Materials2Shapes.shapeDustImpure)
            .generateShape(Materials2Shapes.shapeDustPure)
            .generateShape(Materials2Shapes.shapeDustSmall)
            .generateShape(Materials2Shapes.shapeDustTiny)
            .setProperty(GTMaterialProperties.GTPP, new GTppData(2, 120L, 2388, 8733, 51200, false, true, 1, false, "Th", 90L, 142L, "SOLID", true, true, List.of()));
        // spotless:on
    }

    private Materials2GtppData2() {}
}
