package gregtech.api.enums.materials2;

import com.ruling_0.materiallib.api.Family;
import com.ruling_0.materiallib.api.MaterialLibAPI;
import com.ruling_0.materiallib.api.StandardProperties;
import com.ruling_0.materiallib.api.TextureSet;

// Generated by scripts/mu/gen_shapes.py; edit the script, not this file.
/// Capability families mirroring the legacy `OrePrefixes` generation-bit groups (`DUST`, `METAL`,
/// `GEM`, `ORE`, `CELL`, `PLASMA`, `TOOL`, `GEAR`, `EMPTY`). A shape with generation bits `B` joins
/// every family whose bit is set in `B`, which over-generates relative to the legacy AND/OR
/// capability logic where a material's own bits must also overlap; stage 03's codegen corrects
/// per-material differences with explicit `generateShape`/`removeShape` deltas computed from the
/// dumped `generatedPrefixes` ground truth.
public class Materials2Families {

    // spotless:off
    public static Family all;
    public static Family dusts;
    public static Family metals;
    public static Family gems;
    public static Family ores;
    public static Family cells;
    public static Family plasmas;
    public static Family toolParts;
    public static Family gears;
    public static Family empties;
    // spotless:on

    public static void init() {
        all = MaterialLibAPI.newFamily("gregtech", "All")
            .setProperty(StandardProperties.FALLBACK_TEXTURE_SET, TextureSet.of("gregtech", "NONE"))
            .build();

        dusts = MaterialLibAPI.newFamily("gregtech", "Dusts")
            .generateShapes(Materials2Shapes.dust, Materials2Shapes.dustSmall, Materials2Shapes.dustTiny)
            .build();
        metals = MaterialLibAPI.newFamily("gregtech", "Metals")
            .generateShapes(
                Materials2Shapes.bolt,
                Materials2Shapes.dust,
                Materials2Shapes.dustSmall,
                Materials2Shapes.dustTiny,
                Materials2Shapes.foil,
                Materials2Shapes.ingot,
                Materials2Shapes.ingotHot,
                Materials2Shapes.itemCasing,
                Materials2Shapes.nugget,
                Materials2Shapes.plate,
                Materials2Shapes.plateDense,
                Materials2Shapes.plateDouble,
                Materials2Shapes.plateQuadruple,
                Materials2Shapes.plateQuintuple,
                Materials2Shapes.plateSuperdense,
                Materials2Shapes.plateTriple,
                Materials2Shapes.ring,
                Materials2Shapes.round,
                Materials2Shapes.screw,
                Materials2Shapes.spring,
                Materials2Shapes.springSmall,
                Materials2Shapes.stick,
                Materials2Shapes.stickLong,
                Materials2Shapes.wireFine)
            .build();
        gems = MaterialLibAPI.newFamily("gregtech", "Gems")
            .generateShapes(
                Materials2Shapes.bolt,
                Materials2Shapes.dust,
                Materials2Shapes.dustSmall,
                Materials2Shapes.dustTiny,
                Materials2Shapes.gem,
                Materials2Shapes.gemChipped,
                Materials2Shapes.gemExquisite,
                Materials2Shapes.gemFlawed,
                Materials2Shapes.gemFlawless,
                Materials2Shapes.itemCasing,
                Materials2Shapes.lens,
                Materials2Shapes.plate,
                Materials2Shapes.screw,
                Materials2Shapes.stick,
                Materials2Shapes.stickLong)
            .build();
        ores = MaterialLibAPI.newFamily("gregtech", "Ores")
            .generateShapes(
                Materials2Shapes.crushed,
                Materials2Shapes.crushedCentrifuged,
                Materials2Shapes.crushedPurified,
                Materials2Shapes.dust,
                Materials2Shapes.dustImpure,
                Materials2Shapes.dustPure,
                Materials2Shapes.dustSmall,
                Materials2Shapes.dustTiny,
                Materials2Shapes.rawOre)
            .build();
        cells = MaterialLibAPI.newFamily("gregtech", "Cells")
            .build();
        plasmas = MaterialLibAPI.newFamily("gregtech", "Plasmas")
            .build();
        toolParts = MaterialLibAPI.newFamily("gregtech", "ToolParts")
            .generateShapes(
                Materials2Shapes.toolHeadBuzzSaw,
                Materials2Shapes.toolHeadChainsaw,
                Materials2Shapes.toolHeadDrill,
                Materials2Shapes.toolHeadFile,
                Materials2Shapes.toolHeadHammer,
                Materials2Shapes.toolHeadSaw,
                Materials2Shapes.toolHeadWrench,
                Materials2Shapes.turbineBlade)
            .build();
        gears = MaterialLibAPI.newFamily("gregtech", "Gears")
            .generateShapes(Materials2Shapes.gearGt, Materials2Shapes.gearGtSmall, Materials2Shapes.rotor)
            .build();
        empties = MaterialLibAPI.newFamily("gregtech", "Empties")
            .build();
    }

    private Materials2Families() {}
}
