package gregtech.api.enums.materials2;

import com.ruling_0.materiallib.api.Family;
import com.ruling_0.materiallib.api.MaterialLibAPI;
import com.ruling_0.materiallib.api.StandardProperties;
import com.ruling_0.materiallib.api.TextureSet;

// Generated by scripts/mu/gen_shapes.py; edit the script, not this file.
/// Capability families mirroring the legacy `OrePrefixes` generation-bit groups (`DUST`, `METAL`,
/// `GEM`, `ORE`, `CELL`, `PLASMA`, `TOOL`, `GEAR`, `EMPTY`). A shape with generation bits `B` joins
/// every family whose bit is set in `B`, which over-generates relative to the legacy AND/OR
/// capability logic where a material's own bits must also overlap; stage 03's codegen corrects
/// per-material differences with explicit `generateShape`/`removeShape` deltas computed from the
/// dumped `generatedPrefixes` ground truth.
public class Materials2Families {

    // spotless:off
    public static Family familyAll;
    public static Family familyDusts;
    public static Family familyMetals;
    public static Family familyGems;
    public static Family familyOres;
    public static Family familyCells;
    public static Family familyPlasmas;
    public static Family familyToolParts;
    public static Family familyGears;
    public static Family familyEmpties;
    // spotless:on

    public static void init() {
        familyAll = MaterialLibAPI.newFamily("gregtech", "All")
            .setProperty(StandardProperties.FALLBACK_TEXTURE_SET, TextureSet.of("gregtech", "NONE"))
            .build();

        familyDusts = MaterialLibAPI.newFamily("gregtech", "Dusts")
            .generateShapes(Materials2Shapes.shapeDust, Materials2Shapes.shapeDustSmall, Materials2Shapes.shapeDustTiny)
            .build();
        familyMetals = MaterialLibAPI.newFamily("gregtech", "Metals")
            .generateShapes(
                Materials2Shapes.shapeBolt,
                Materials2Shapes.shapeDust,
                Materials2Shapes.shapeDustSmall,
                Materials2Shapes.shapeDustTiny,
                Materials2Shapes.shapeFoil,
                Materials2Shapes.shapeHandleMallet,
                Materials2Shapes.shapeIngot,
                Materials2Shapes.shapeIngotHot,
                Materials2Shapes.shapeItemCasing,
                Materials2Shapes.shapeNugget,
                Materials2Shapes.shapePlate,
                Materials2Shapes.shapePlateDense,
                Materials2Shapes.shapePlateDouble,
                Materials2Shapes.shapePlateQuadruple,
                Materials2Shapes.shapePlateQuintuple,
                Materials2Shapes.shapePlateSuperdense,
                Materials2Shapes.shapePlateTriple,
                Materials2Shapes.shapeRing,
                Materials2Shapes.shapeRound,
                Materials2Shapes.shapeScrew,
                Materials2Shapes.shapeSpring,
                Materials2Shapes.shapeSpringSmall,
                Materials2Shapes.shapeStick,
                Materials2Shapes.shapeStickLong,
                Materials2Shapes.shapeWireFine)
            .build();
        familyGems = MaterialLibAPI.newFamily("gregtech", "Gems")
            .generateShapes(
                Materials2Shapes.shapeBolt,
                Materials2Shapes.shapeCrystal,
                Materials2Shapes.shapeDust,
                Materials2Shapes.shapeDustSmall,
                Materials2Shapes.shapeDustTiny,
                Materials2Shapes.shapeGem,
                Materials2Shapes.shapeGemChipped,
                Materials2Shapes.shapeGemExquisite,
                Materials2Shapes.shapeGemFlawed,
                Materials2Shapes.shapeGemFlawless,
                Materials2Shapes.shapeHandleMallet,
                Materials2Shapes.shapeItemCasing,
                Materials2Shapes.shapeLens,
                Materials2Shapes.shapePlate,
                Materials2Shapes.shapeScrew,
                Materials2Shapes.shapeStick,
                Materials2Shapes.shapeStickLong)
            .build();
        familyOres = MaterialLibAPI.newFamily("gregtech", "Ores")
            .generateShapes(
                Materials2Shapes.shapeCleanGravel,
                Materials2Shapes.shapeClump,
                Materials2Shapes.shapeCrushed,
                Materials2Shapes.shapeCrushedCentrifuged,
                Materials2Shapes.shapeCrushedPurified,
                Materials2Shapes.shapeCrystalline,
                Materials2Shapes.shapeDirtyGravel,
                Materials2Shapes.shapeDust,
                Materials2Shapes.shapeDustImpure,
                Materials2Shapes.shapeDustPure,
                Materials2Shapes.shapeDustRefined,
                Materials2Shapes.shapeDustSmall,
                Materials2Shapes.shapeDustTiny,
                Materials2Shapes.shapeMilled,
                Materials2Shapes.shapeRawOre,
                Materials2Shapes.shapeReduced,
                Materials2Shapes.shapeShard)
            .build();
        familyCells = MaterialLibAPI.newFamily("gregtech", "Cells")
            .build();
        familyPlasmas = MaterialLibAPI.newFamily("gregtech", "Plasmas")
            .build();
        familyToolParts = MaterialLibAPI.newFamily("gregtech", "ToolParts")
            .generateShapes(
                Materials2Shapes.shapeBulletGtLarge,
                Materials2Shapes.shapeBulletGtMedium,
                Materials2Shapes.shapeBulletGtSmall,
                Materials2Shapes.shapeToolHeadBuzzSaw,
                Materials2Shapes.shapeToolHeadChainsaw,
                Materials2Shapes.shapeToolHeadDrill,
                Materials2Shapes.shapeToolHeadFile,
                Materials2Shapes.shapeToolHeadHammer,
                Materials2Shapes.shapeToolHeadMallet,
                Materials2Shapes.shapeToolHeadSaw,
                Materials2Shapes.shapeToolHeadScrewdriver,
                Materials2Shapes.shapeToolHeadWrench,
                Materials2Shapes.shapeTurbineBlade)
            .build();
        familyGears = MaterialLibAPI.newFamily("gregtech", "Gears")
            .generateShapes(
                Materials2Shapes.shapeGearGt,
                Materials2Shapes.shapeGearGtSmall,
                Materials2Shapes.shapeRotor)
            .build();
        familyEmpties = MaterialLibAPI.newFamily("gregtech", "Empties")
            .generateShapes(
                Materials2Shapes.shapeBulletGtLarge,
                Materials2Shapes.shapeBulletGtMedium,
                Materials2Shapes.shapeBulletGtSmall)
            .build();
    }

    private Materials2Families() {}
}
