package gregtech.common.tileentities.machines.multi.purification;

// Extracted to another class to not fill the main source file with bloat
public class PurificationPlantStructureString {

    public static final String[][] STRUCTURE_STRING = new String[][] {
        // spotless:off
        {   "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                       GHG                       ",
            "                       GHG                       ",
            "                       GHG                       ",
            "                       G~G                       ",
            "                       GHG                       ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                       GBG                       ",
            "                     BBBBBBB                     ",
            "                     BAAAAAB                     ",
            "                     BAAAAAB                     ",
            "                     BAAAAAB                     ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                      G   G                      ",
            "                      G   G                      ",
            "                      G   G                      ",
            "                      GGBGG                      ",
            "                     BAAAAAB                     ",
            "                     A     A                     ",
            "                     A     A                     ",
            "                     A     A                     ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                       BBB                       ",
            "                       BBB                       ",
            "                       BBB                       ",
            "                       BBB                       ",
            "                     BAAAAAB                     ",
            "                     A     A                     ",
            "                     E     A                     ",
            "                     A     A                     ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                       BWB                       ",
            "                       BWB                       ",
            "                       BWB                       ",
            "                       BWB                       ",
            "                     BAAAAAB                     ",
            "                     A     A                     ",
            "                     E     A                     ",
            "                     A     A                     ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                       BBB                       ",
            "                       BBB                       ",
            "                       BBB                       ",
            "                       BBB                       ",
            "                     BAAAAAB                     ",
            "                     A     A                     ",
            "                     E     D                     ",
            "                     A     D                     ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                      G   G                      ",
            "                      G   G                      ",
            "                      G   G                      ",
            "                      G   G                      ",
            "                     BAAAAAB                     ",
            "                     A     A                     ",
            "                     A     A                     ",
            "                     A     A                     ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                     BBBBBBB                     ",
            "                     BAAAAAB                     ",
            "                     BAEEEAB                     ",
            "                     BAAAAAB                     ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" },
          { "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "                                                 ",
            "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC" } };
    // spotless:on
}
