package gregtech.loaders.load;

import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;

import gregtech.GTMod;
import gregtech.api.enums.SoundResource;
import gregtech.api.util.GTLog;

public class SonictronLoader implements Runnable {

    @Override
    public void run() {
        GTLog.out.println("GTMod: Loading Sonictron Sounds");
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Blocks.iron_block, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.NOTE_HARP.toString());
        GTMod.gregtechproxy.mSoundCounts.add(25);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Blocks.gold_block, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.NOTE_PLING.toString());
        GTMod.gregtechproxy.mSoundCounts.add(25);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Blocks.stone, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.NOTE_BD.toString());
        GTMod.gregtechproxy.mSoundCounts.add(25);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Blocks.log, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.NOTE_BASSATTACK.toString());
        GTMod.gregtechproxy.mSoundCounts.add(25);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Blocks.planks, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.NOTE_BASS.toString());
        GTMod.gregtechproxy.mSoundCounts.add(25);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Blocks.glass, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.NOTE_HAT.toString());
        GTMod.gregtechproxy.mSoundCounts.add(25);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Blocks.sand, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.NOTE_BASS.toString());
        GTMod.gregtechproxy.mSoundCounts.add(25);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Items.record_cat, 1));
        GTMod.gregtechproxy.mSoundNames.add("streaming.");
        GTMod.gregtechproxy.mSoundCounts.add(12);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Blocks.tnt, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.RANDOM_EXPLODE.toString());
        GTMod.gregtechproxy.mSoundCounts.add(3);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Blocks.fire, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.FIRE_FIRE.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Items.flint_and_steel, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.FIRE_IGNITE.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Blocks.lava, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.LIQUID_LAVAPOP.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Blocks.water, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.LIQUID_WATER.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Items.water_bucket, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.LIQUID_SPLASH.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Items.lava_bucket, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.RANDOM_FIZZ.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Blocks.portal, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.PORTAL_PORTAL.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Blocks.end_portal, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.PORTAL_TRAVEL.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Blocks.end_portal_frame, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.PORTAL_TRIGGER.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Blocks.glass_pane, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.RANDOM_GLASS.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Items.ender_pearl, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.RANDOM_ORB.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Items.ender_eye, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.RANDOM_LEVELUP.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Blocks.stone_button, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.RANDOM_CLICK.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Blocks.cobblestone, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.DAMAGE_FALLBIG.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Blocks.dirt, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.DAMAGE_FALLSMALL.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Items.iron_sword, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.DAMAGE_HURTFLESH.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Items.diamond_sword, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.RANDOM_HURT.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Items.bow, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.RANDOM_BOW.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Items.arrow, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.RANDOM_DRR.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Items.fishing_rod, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.RANDOM_BOWHIT.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Items.iron_shovel, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.RANDOM_BREAK.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Items.bucket, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.RANDOM_BREATH.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Items.potionitem, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.RANDOM_DRINK.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Items.glass_bottle, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.RANDOM_BURP.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems
            .add(new ItemStack(Blocks.ender_chest == null ? Blocks.obsidian : Blocks.ender_chest, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.RANDOM_CHESTOPEN.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Blocks.chest, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.RANDOM_CHESTCLOSED.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Items.iron_door, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.RANDOM_DOOR_OPEN.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Items.wooden_door, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.RANDOM_DOOR_CLOSE.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Items.porkchop, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.RANDOM_EAT.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Blocks.wool, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.STEP_CLOTH.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Blocks.grass, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.STEP_GRASS.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Blocks.gravel, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.STEP_GRAVEL.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Blocks.snow, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.STEP_SNOW.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Blocks.piston, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.TILE_PISTON_OUT.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Blocks.sticky_piston, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.TILE_PISTON_IN.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Blocks.mossy_cobblestone, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.AMBIENT_CAVE_CAVE.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Blocks.lapis_block, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.AMBIENT_WEATHER_RAIN.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
        GTMod.gregtechproxy.mSoundItems.add(new ItemStack(Blocks.diamond_block, 1));
        GTMod.gregtechproxy.mSoundNames.add(SoundResource.AMBIENT_WEATHER_THUNDER.toString());
        GTMod.gregtechproxy.mSoundCounts.add(1);
    }
}
