/*
 * Copyright (c) 2018-2020 bartimaeusnek Permission is hereby granted, free of charge, to any person obtaining a copy of
 * this software and associated documentation files (the "Software"), to deal in the Software without restriction,
 * including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following
 * conditions: The above copyright notice and this permission notice shall be included in all copies or substantial
 * portions of the Software. THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

package bartworks.API;

import static gregtech.api.enums.Mods.Gendustry;
import static gregtech.api.recipe.RecipeMaps.centrifugeRecipes;
import static gregtech.api.util.GTRecipeBuilder.SECONDS;

import java.awt.Color;

import bartworks.API.enums.BioCultureEnum;
import net.minecraft.item.EnumRarity;
import net.minecraftforge.fluids.FluidStack;

import org.jetbrains.annotations.Nullable;

import bartworks.util.BioCulture;
import bartworks.util.BioData;
import gregtech.api.enums.FluidState;
import gregtech.api.enums.GTValues;
import gregtech.api.enums.Materials;
import gregtech.api.enums.TierEU;
import gregtech.api.fluid.GTFluidFactory;
import gregtech.api.util.GTModHandler;

public final class BioObjectAdder {

    /**
     * @param voltageTier (i.e. 6 for LuV, 7 for ZPM, only intresting for LuV+)
     * @return the propper Bacteria Tier (at least 0)
     */
    public static int getBacteriaTierFromVoltageTier(int voltageTier) {
        return Math.max(voltageTier - 6, 0);
    }

    /**
     * If you get NPE's related to BioCultures (most likely because of Load Order or creating BioCultures after the
     * postinit Phase) execute this.
     */
    public static void regenerateBioFluids() {
        FluidStack dnaFluid = Gendustry.isModLoaded() ? GTModHandler.getLiquidDNA(100)
            : Materials.Biomass.getFluid(100L);
        for (BioCulture B : BioCultureEnum.BIO_CULTURES) {
            if (B.getFluidNotSet()) {
                B.setFluid(
                    GTFluidFactory.builder(
                        B.getName()
                            .replace(" ", "")
                            .toLowerCase() + "fluid")
                        .withTextureName("molten.autogenerated")
                        .withColorRGBA(
                            new short[] { (short) B.getColor()
                                .getRed(),
                                (short) B.getColor()
                                    .getBlue(),
                                (short) B.getColor()
                                    .getGreen() })
                        .withStateAndTemperature(FluidState.LIQUID, 300)
                        .buildAndRegister()
                        .asFluid());

                GTValues.RA.stdBuilder()
                    .circuit(10)
                    .fluidInputs(new FluidStack(B.getFluid(), 1000))
                    .fluidOutputs(dnaFluid)
                    .duration(25 * SECONDS)
                    .eut(TierEU.RECIPE_MV)
                    .addTo(centrifugeRecipes);
            }
        }
    }
}
