package gregtech.loaders.postload.recipes;

import static gregtech.api.enums.GT_Values.NI;
import static gregtech.api.enums.ModIDs.ExtraUtilities;
import static gregtech.api.enums.ModIDs.Thaumcraft;
import static gregtech.api.util.GT_ModHandler.getModItem;
import static net.minecraftforge.fluids.FluidRegistry.getFluidStack;

import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemStack;

import gregtech.api.enums.*;
import gregtech.api.util.GT_ModHandler;
import gregtech.api.util.GT_OreDictUnificator;
import gregtech.api.util.GT_Utility;
import gregtech.loaders.postload.GT_MachineRecipeLoader;

public class CentrifugeRecipes implements Runnable {

    @Override
    public void run() {
        GT_Values.RA.addCentrifugeRecipe(
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.InfusedGold, 1L),
                GT_Values.NI,
                Materials.Mercury.getFluid(200L),
                GT_Values.NF,
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Gold, 1L),
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Gold, 1L),
                getModItem("Thaumcraft", "ItemResource", 2L, 14),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                new int[] { 10000, 10000, 9000 },
                400,
                (int) TierEU.RECIPE_MV);

        GT_Values.RA.addCentrifugeRecipe(
                ItemList.Cell_Empty.get(1),
                null,
                Materials.Air.getGas(10000),
                Materials.Nitrogen.getGas(3900),
                GT_OreDictUnificator.get(OrePrefixes.cell, Materials.Oxygen, 1),
                null,
                null,
                null,
                null,
                null,
                null,
                1600,
                8);

        GT_Values.RA.addCentrifugeRecipe(
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.PlatinumGroupSludge, 9),
                null,
                null,
                null,
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.SiliconDioxide, 9),
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Gold, 9),
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Platinum, 9),
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Palladium, 3),
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Iridium, 3),
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Osmium, 3),
                new int[] { 10000, 10000, 10000, 9500, 9000, 8500 },
                8100,
                30);

        GT_Values.RA.addCentrifugeRecipe(
                GT_Values.NI,
                GT_Values.NI,
                MaterialsOreAlum.SluiceJuice.getFluid(1000),
                Materials.Water.getFluid(500),
                Materials.Stone.getDust(1),
                Materials.Iron.getDust(1),
                Materials.Copper.getDust(1),
                Materials.Tin.getDust(1),
                Materials.Nickel.getDust(1),
                Materials.Antimony.getDust(1),
                new int[] { 10000, 4000, 2000, 2000, 2000, 2000 },
                40,
                (int) TierEU.RECIPE_MV);

        // food ->CH4
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Items.golden_apple, 1, 1),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(4608L),
                new ItemStack(Items.gold_ingot, 64),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                9216,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Items.golden_apple, 1, 0),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                new ItemStack(Items.gold_ingot, 7),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                9216,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Items.golden_carrot, 1, 0),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                new ItemStack(Items.gold_nugget, 6),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                9216,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Items.speckled_melon, 1, 0),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                new ItemStack(Items.gold_nugget, 6),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                9216,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Items.mushroom_stew, 16, 0),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                new ItemStack(Items.bowl, 16, 0),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Items.apple, 32, 0),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Items.bread, 64, 0),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Items.porkchop, 12, 0),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Items.cooked_porkchop, 16, 0),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Items.beef, 12, 0),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Items.cooked_beef, 16, 0),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Items.fish, 12, 32767),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Items.cooked_fished, 16, 32767),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Items.chicken, 12, 0),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Items.cooked_chicken, 16, 0),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Items.melon, 64, 0),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Blocks.pumpkin, 16, 0),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Items.rotten_flesh, 16, 0),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Items.spider_eye, 32, 0),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Items.carrot, 16, 0),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                ItemList.Food_Raw_Potato.get(16L),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                ItemList.Food_Poisonous_Potato.get(12L),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                ItemList.Food_Baked_Potato.get(24L),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Items.cookie, 64, 0),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Items.cake, 8, 0),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Blocks.brown_mushroom_block, 12, 32767),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Blocks.red_mushroom_block, 12, 32767),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Blocks.brown_mushroom, 32, 32767),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Blocks.red_mushroom, 32, 32767),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Items.nether_wart, 32, 32767),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                GT_ModHandler.getIC2Item("terraWart", 16L),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                getModItem("TwilightForest", "item.meefRaw", 12L, 32767),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                getModItem("TwilightForest", "item.meefSteak", 16L, 32767),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                getModItem("TwilightForest", "item.venisonRaw", 12L, 32767),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                getModItem("TwilightForest", "item.venisonCooked", 16L, 32767),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                Materials.Methane.getGas(576L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                4608,
                5);

        GT_Values.RA.addCentrifugeRecipe(
                GT_OreDictUnificator.get(OrePrefixes.log, Materials.Wood, 1L),
                GT_Utility.getIntegratedCircuit(1),
                null,
                Materials.Methane.getGas(60L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                200,
                20);

        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Blocks.sand, 1, 1),
                GT_Values.NI,
                GT_Values.NF,
                GT_Values.NF,
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Iron, 1L),
                GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Diamond, 1L),
                new ItemStack(Blocks.sand, 1),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                new int[] { 5000, 100, 5000 },
                600,
                (int) TierEU.RECIPE_MV);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Blocks.dirt, 1, 32767),
                GT_Values.NI,
                GT_Values.NF,
                GT_Values.NF,
                ItemList.IC2_Plantball.get(1L),
                GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Clay, 1L),
                new ItemStack(Blocks.sand, 1),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                new int[] { 1250, 5000, 5000 },
                250,
                30);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Blocks.grass, 1, 32767),
                GT_Values.NI,
                GT_Values.NF,
                GT_Values.NF,
                ItemList.IC2_Plantball.get(1L),
                GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Clay, 1L),
                new ItemStack(Blocks.sand, 1),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                new int[] { 2500, 5000, 5000 },
                250,
                30);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Blocks.mycelium, 1, 32767),
                GT_Values.NI,
                GT_Values.NF,
                GT_Values.NF,
                new ItemStack(Blocks.brown_mushroom, 1),
                new ItemStack(Blocks.red_mushroom, 1),
                GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Clay, 1L),
                new ItemStack(Blocks.sand, 1),
                GT_Values.NI,
                GT_Values.NI,
                new int[] { 2500, 2500, 5000, 5000 },
                650,
                30);
        GT_Values.RA.addCentrifugeRecipe(
                ItemList.IC2_Resin.get(1L),
                GT_Values.NI,
                GT_Values.NF,
                Materials.Glue.getFluid(100L),
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.RawRubber, 3L),
                ItemList.IC2_Plantball.get(1L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                new int[] { 10000, 1000 },
                300,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.DarkAsh, 1),
                0,
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Ash, 1L),
                ItemList.TE_Slag.get(1L, GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Carbon, 1L)),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                250);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Items.magma_cream, 1),
                0,
                new ItemStack(Items.blaze_powder, 1),
                new ItemStack(Items.slime_ball, 1),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                500);
        GT_Values.RA.addCentrifugeRecipe(
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Uranium, 1L),
                GT_Utility.getIntegratedCircuit(10),
                GT_Values.NF,
                GT_Values.NF,
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Uranium235, 1L),
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Plutonium, 1L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                new int[] { 1000, 500 },
                2000,
                (int) TierEU.RECIPE_HV);
        // Uranium Enrichment in Centrifuge by adding Fluorine (Uranium Hexafluoride)
        GT_Values.RA.addCentrifugeRecipe(
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Uranium, 1L),
                GT_Values.NI,
                Materials.Fluorine.getGas(4000),
                GT_Values.NF,
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Uranium235, 1L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                new int[] { 10000 },
                4000,
                (int) TierEU.RECIPE_EV);
        GT_Values.RA.addCentrifugeRecipe(
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Plutonium, 1L),
                GT_Values.NI,
                GT_Values.NF,
                GT_Values.NF,
                GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Plutonium241, 1L),
                GT_OreDictUnificator.get(OrePrefixes.dustTiny, Materials.Uranium, 1L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                new int[] { 2000, 3000 },
                1600,
                320);
        GT_Values.RA.addCentrifugeRecipe(
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Naquadah, 9L),
                GT_Values.NI,
                GT_Values.NF,
                GT_Values.NF,
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.NaquadahEnriched, 1L),
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Naquadria, 1L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                new int[] { 5000, 1000 },
                28800,
                320);
        GT_Values.RA.addCentrifugeRecipe(
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.NaquadahEnriched, 4L),
                GT_Values.NI,
                GT_Values.NF,
                GT_Values.NF,
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Naquadria, 1L),
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Naquadah, 1L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                new int[] { 2000, 3000 },
                25600,
                640);
        GT_Values.RA.addCentrifugeRecipe(
                GT_Values.NI,
                GT_Values.NI,
                Materials.Hydrogen.getGas(160L),
                Materials.Deuterium.getGas(40L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                160,
                20);
        GT_Values.RA.addCentrifugeRecipe(
                GT_Values.NI,
                GT_Values.NI,
                Materials.Deuterium.getGas(160L),
                Materials.Tritium.getGas(40L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                160,
                80);
        GT_Values.RA.addCentrifugeRecipe(
                GT_Values.NI,
                GT_Values.NI,
                Materials.Helium.getGas(80L),
                Materials.Helium_3.getGas(5L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                160,
                80);
        GT_Values.RA.addCentrifugeRecipe(
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Glowstone, 2L),
                GT_Values.NI,
                GT_Values.NF,
                GT_Values.NF,
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Redstone, 1L),
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Gold, 1L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                null,
                976,
                80);

        GT_Values.RA.addCentrifugeRecipe(
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Endstone, 36L),
                GT_Values.NI,
                GT_Values.NF,
                Materials.Helium.getGas(4320L),
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Tungstate, 3L),
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Platinum, 1L),
                new ItemStack(Blocks.sand, 36),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                new int[] { 3750, 2500, 9000, 0, 0, 0 },
                11520,
                20);
        GT_Values.RA.addCentrifugeRecipe(
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Netherrack, 36L),
                GT_Values.NI,
                GT_Values.NF,
                GT_Values.NF,
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Redstone, 4L),
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Sulfur, 9L),
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Coal, 4L),
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Gold, 1L),
                GT_Values.NI,
                GT_Values.NI,
                new int[] { 5625, 9900, 5625, 2500, 0, 0 },
                5760,
                20);

        GT_Values.RA.addCentrifugeRecipe(
                GT_Utility.getIntegratedCircuit(10),
                GT_Values.NI,
                Materials.Lava.getFluid(400L),
                GT_Values.NF,
                Materials.SiliconDioxide.getDust(1),
                Materials.Magnesia.getDust(1),
                Materials.Quicklime.getDust(1),
                Materials.Gold.getNuggets(4),
                Materials.Sapphire.getDust(1),
                Materials.Tantalite.getDust(1),
                new int[] { 5000, 1000, 1000, 250, 1250, 500 },
                320,
                80);
        GT_Values.RA.addCentrifugeRecipe(
                GT_Utility.getIntegratedCircuit(20),
                GT_Values.NI,
                Materials.Lava.getFluid(3600L),
                GT_Values.NF,
                Materials.SiliconDioxide.getDust(5),
                Materials.Magnesia.getDust(1),
                Materials.Quicklime.getDust(1),
                Materials.Gold.getIngots(1),
                Materials.Sapphire.getDust(3),
                Materials.Tantalite.getDust(1),
                new int[] { 9000, 9000, 9000, 1000, 3750, 4500 },
                2880,
                80);
        GT_Values.RA.addCentrifugeRecipe(
                new ItemStack(Blocks.soul_sand, 1),
                GT_Values.NI,
                GT_Values.NF,
                Materials.Oil.getFluid(200L),
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Saltpeter, 1L),
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Coal, 1L),
                new ItemStack(Blocks.sand, 1),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                new int[] { 1000, 700, 9000, 0, 0, 0 },
                200,
                12);

        GT_Values.RA.addCentrifugeRecipe(
                GT_Utility.getIntegratedCircuit(10),
                GT_Values.NI,
                getFluidStack("ic2pahoehoelava", 100),
                GT_Values.NF,
                GT_OreDictUnificator.get(OrePrefixes.nugget, Materials.Copper, 1L),
                GT_OreDictUnificator.get(OrePrefixes.nugget, Materials.Tin, 1L),
                GT_OreDictUnificator.get(OrePrefixes.nugget, Materials.Silver, 1L),
                GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Phosphorus, 1L),
                GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Scheelite, 1L),
                GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Bauxite, 1L),
                new int[] { 2000, 1000, 250, 50, 250, 500 },
                40,
                1024);
        GT_Values.RA.addCentrifugeRecipe(
                GT_Utility.getIntegratedCircuit(20),
                GT_Values.NI,
                getFluidStack("ic2pahoehoelava", 3600),
                GT_Values.NF,
                GT_OreDictUnificator.get(OrePrefixes.ingot, Materials.Copper, 1L),
                GT_OreDictUnificator.get(OrePrefixes.ingot, Materials.Tin, 1L),
                GT_OreDictUnificator.get(OrePrefixes.ingot, Materials.Silver, 1L),
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Phosphorus, 1L),
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Scheelite, 1L),
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Bauxite, 1L),
                new int[] { 8000, 4000, 1000, 450, 2250, 4500 },
                328,
                4096);

        // rare earth ( why this still remain
        GT_Values.RA.addCentrifugeRecipe(
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.RareEarth, 1L),
                GT_Values.NI,
                GT_Values.NF,
                GT_Values.NF,
                GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Neodymium, 1L),
                GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Yttrium, 1L),
                GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Lanthanum, 1L),
                GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Cerium, 1L),
                GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Cadmium, 1L),
                GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Caesium, 1L),
                new int[] { 2500, 2500, 2500, 2500, 2500, 2500 },
                64,
                20);

        GT_Values.RA.addCentrifugeRecipe(
                getModItem(GT_MachineRecipeLoader.aTextAE, GT_MachineRecipeLoader.aTextAEMM, 1L, 45),
                GT_Utility.getIntegratedCircuit(1),
                GT_Values.NF,
                GT_Values.NF,
                GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.BasalticMineralSand, 1L),
                GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Olivine, 1L),
                GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Obsidian, 1L),
                GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Basalt, 1L),
                GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.Flint, 1L),
                GT_OreDictUnificator.get(OrePrefixes.dustSmall, Materials.RareEarth, 1L),
                new int[] { 2000, 2000, 2000, 2000, 2000, 2000 },
                64,
                20);
        GT_Values.RA.addCentrifugeRecipe(
                getModItem(GT_MachineRecipeLoader.aTextAE, GT_MachineRecipeLoader.aTextAEMM, 36L, 45),
                GT_Utility.getIntegratedCircuit(2),
                GT_Values.NF,
                GT_Values.NF,
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.BasalticMineralSand, 2L),
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Olivine, 2L),
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Obsidian, 2L),
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Basalt, 2L),
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Flint, 2L),
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.RareEarth, 2L),
                new int[] { 9000, 9000, 9000, 9000, 9000, 9000 },
                518,
                80);

        // Ash centrifuge recipes
        GT_Values.RA.addCentrifugeRecipe(
                Materials.Ash.getDust(36),
                GT_Values.NI,
                GT_Values.NF,
                GT_Values.NF,
                Materials.Quicklime.getDust(18),
                Materials.Potash.getDust(9),
                Materials.Magnesia.getDust(1),
                Materials.PhosphorousPentoxide.getDust(2),
                Materials.SodaAsh.getDust(1),
                Materials.BandedIron.getDust(4),
                new int[] { 6400, 6000, 4500, 10000, 10000, 10000 },
                6000,
                30);
        // Stone Dust and Metal Mixture centrifuge recipes
        GT_Values.RA.addCentrifugeRecipe(
                Materials.Stone.getDust(36),
                GT_Values.NI,
                GT_Values.NF,
                GT_Values.NF,
                Materials.Quartzite.getDust(9),
                Materials.PotassiumFeldspar.getDust(9),
                Materials.Marble.getDust(8),
                Materials.Biotite.getDust(4),
                Materials.MetalMixture.getDust(3),
                Materials.Sodalite.getDust(2),
                new int[] { 10000, 10000, 10000, 10000, 10000, 10000 },
                8640,
                30);
        GT_Values.RA.addCentrifugeRecipe(
                Materials.MetalMixture.getDust(36),
                GT_Values.NI,
                GT_Values.NF,
                GT_Values.NF,
                Materials.BandedIron.getDust(9),
                Materials.Bauxite.getDust(9),
                Materials.Pyrolusite.getDust(8),
                Materials.Barite.getDust(4),
                Materials.Chromite.getDust(3),
                Materials.Ilmenite.getDust(2),
                new int[] { 10000, 10000, 10000, 10000, 10000, 10000 },
                13125,
                (int) TierEU.RECIPE_EV);

        GT_Values.RA.addCentrifugeRecipe(
                null,
                null,
                Materials.Propane.getGas(320),
                Materials.LPG.getFluid(290),
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                20,
                5);
        GT_Values.RA.addCentrifugeRecipe(
                null,
                null,
                Materials.Butane.getGas(320),
                Materials.LPG.getFluid(370),
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                20,
                5);

        GT_Values.RA.addCentrifugeRecipe(
                GT_Values.NI,
                GT_Values.NI,
                Materials.EnrichedNaquadria.getFluid(9216L),
                Materials.FluidNaquadahFuel.getFluid(4806L),
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.Naquadah, 8L),
                GT_OreDictUnificator.get(OrePrefixes.dust, Materials.ElectrumFlux, 8L),
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                GT_Values.NI,
                new int[] { 10000, 10000 },
                600,
                2000000);

        if (Thaumcraft.isModLoaded()) {
            // air
            GT_Values.RA.addCentrifugeRecipe(
                    getModItem("gregtech", "gt.comb", 1L, 144),
                    GT_Utility.getIntegratedCircuit(1),
                    GT_Values.NF,
                    null,
                    GT_OreDictUnificator.get(OrePrefixes.gem, Materials.InfusedAir, 1L),
                    GT_Values.NI,
                    GT_Values.NI,
                    GT_Values.NI,
                    GT_Values.NI,
                    GT_Values.NI,
                    null,
                    1024,
                    12);
            // fire
            GT_Values.RA.addCentrifugeRecipe(
                    getModItem("gregtech", "gt.comb", 1L, 146),
                    GT_Utility.getIntegratedCircuit(1),
                    GT_Values.NF,
                    null,
                    GT_OreDictUnificator.get(OrePrefixes.gem, Materials.InfusedFire, 1L),
                    GT_Values.NI,
                    GT_Values.NI,
                    GT_Values.NI,
                    GT_Values.NI,
                    GT_Values.NI,
                    null,
                    1024,
                    12);
            // aqua
            GT_Values.RA.addCentrifugeRecipe(
                    getModItem("gregtech", "gt.comb", 1L, 147),
                    GT_Utility.getIntegratedCircuit(1),
                    GT_Values.NF,
                    null,
                    GT_OreDictUnificator.get(OrePrefixes.gem, Materials.InfusedWater, 1L),
                    GT_Values.NI,
                    GT_Values.NI,
                    GT_Values.NI,
                    GT_Values.NI,
                    GT_Values.NI,
                    null,
                    1024,
                    12);
            // terra
            GT_Values.RA.addCentrifugeRecipe(
                    getModItem("gregtech", "gt.comb", 1L, 145),
                    GT_Utility.getIntegratedCircuit(1),
                    GT_Values.NF,
                    null,
                    GT_OreDictUnificator.get(OrePrefixes.gem, Materials.InfusedEarth, 1L),
                    GT_Values.NI,
                    GT_Values.NI,
                    GT_Values.NI,
                    GT_Values.NI,
                    GT_Values.NI,
                    null,
                    1024,
                    12);
            // ordo
            GT_Values.RA.addCentrifugeRecipe(
                    getModItem("gregtech", "gt.comb", 1L, 148),
                    GT_Utility.getIntegratedCircuit(1),
                    GT_Values.NF,
                    null,
                    GT_OreDictUnificator.get(OrePrefixes.gem, Materials.InfusedOrder, 1L),
                    GT_Values.NI,
                    GT_Values.NI,
                    GT_Values.NI,
                    GT_Values.NI,
                    GT_Values.NI,
                    null,
                    1024,
                    12);
            // perditio
            GT_Values.RA.addCentrifugeRecipe(
                    getModItem("gregtech", "gt.comb", 1L, 149),
                    GT_Utility.getIntegratedCircuit(1),
                    GT_Values.NF,
                    null,
                    GT_OreDictUnificator.get(OrePrefixes.gem, Materials.InfusedEntropy, 1L),
                    GT_Values.NI,
                    GT_Values.NI,
                    GT_Values.NI,
                    GT_Values.NI,
                    GT_Values.NI,
                    null,
                    1024,
                    12);
            // Nethershard
            GT_Values.RA.addCentrifugeRecipe(
                    getModItem("gregtech", "gt.comb", 1L, 152),
                    GT_Utility.getIntegratedCircuit(1),
                    GT_Values.NF,
                    null,
                    getModItem("ThaumicTinkerer", "kamiResource", 1L, 6),
                    GT_Values.NI,
                    GT_Values.NI,
                    GT_Values.NI,
                    GT_Values.NI,
                    GT_Values.NI,
                    null,
                    128,
                    512);
            // Endshard
            GT_Values.RA.addCentrifugeRecipe(
                    getModItem("gregtech", "gt.comb", 1L, 153),
                    GT_Utility.getIntegratedCircuit(1),
                    GT_Values.NF,
                    null,
                    getModItem("ThaumicTinkerer", "kamiResource", 1L, 7),
                    GT_Values.NI,
                    GT_Values.NI,
                    GT_Values.NI,
                    GT_Values.NI,
                    GT_Values.NI,
                    null,
                    128,
                    512);
        }

        if (ExtraUtilities.isModLoaded()) {
            // Caelestis red
            GT_Values.RA.addCentrifugeRecipe(
                    getModItem("gregtech", "gt.comb", 1L, 154),
                    GT_Utility.getIntegratedCircuit(1),
                    GT_Values.NF,
                    null,
                    getModItem("ExtraUtilities", "greenscreen", 1L, 2),
                    getModItem("ExtraUtilities", "greenscreen", 1L, 10),
                    getModItem("ExtraUtilities", "greenscreen", 1L, 14),
                    getModItem("ExtraUtilities", "greenscreen", 1L, 1),
                    getModItem("ExtraUtilities", "greenscreen", 1L, 12),
                    getModItem("ExtraUtilities", "greenscreen", 1L, 6),
                    null,
                    512,
                    12);
            // Caelestis green
            GT_Values.RA.addCentrifugeRecipe(
                    getModItem("gregtech", "gt.comb", 1L, 155),
                    GT_Utility.getIntegratedCircuit(1),
                    GT_Values.NF,
                    null,
                    getModItem("ExtraUtilities", "greenscreen", 1L, 13),
                    getModItem("ExtraUtilities", "greenscreen", 1L, 5),
                    getModItem("ExtraUtilities", "greenscreen", 1L, 4),
                    getModItem("ExtraUtilities", "greenscreen", 1L, 8),
                    getModItem("ExtraUtilities", "greenscreen", 1L, 0),
                    NI,
                    null,
                    512,
                    12);
            // Caelestis blue
            GT_Values.RA.addCentrifugeRecipe(
                    getModItem("gregtech", "gt.comb", 1L, 156),
                    GT_Utility.getIntegratedCircuit(1),
                    GT_Values.NF,
                    null,
                    getModItem("ExtraUtilities", "greenscreen", 1L, 3),
                    getModItem("ExtraUtilities", "greenscreen", 1L, 9),
                    getModItem("ExtraUtilities", "greenscreen", 1L, 11),
                    getModItem("ExtraUtilities", "greenscreen", 1L, 7),
                    getModItem("ExtraUtilities", "greenscreen", 1L, 15),
                    NI,
                    null,
                    512,
                    12);
        }
    }
}
