package gtPlusPlus.core.util.minecraft;

import static gregtech.api.recipe.RecipeMaps.cannerRecipes;
import static gregtech.api.recipe.RecipeMaps.fluidExtractionRecipes;
import static gregtech.api.util.GTRecipeBuilder.SECONDS;

import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;
import net.minecraftforge.fluids.Fluid;
import net.minecraftforge.fluids.FluidContainerRegistry;
import net.minecraftforge.fluids.FluidRegistry;
import net.minecraftforge.fluids.FluidStack;

import gregtech.api.enums.Dyes;
import gregtech.api.enums.GTValues;
import gregtech.api.enums.ItemList;
import gregtech.api.enums.Materials;
import gregtech.api.enums.TierEU;
import gregtech.api.util.StringUtils;
import gtPlusPlus.api.objects.Logger;
import gtPlusPlus.api.objects.minecraft.FluidGT6;
import gtPlusPlus.core.item.base.BaseItemComponent;
import gtPlusPlus.core.item.base.cell.BaseItemPlasmaCell;
import gtPlusPlus.core.material.Material;
import gtPlusPlus.core.material.MaterialStack;

public class FluidUtils {

    public static Fluid addGtFluid(final String aName, final String aLocalized, final short[] rgba, final int aState,
        final long aTemperatureK, final ItemStack aFullContainer, final ItemStack aEmptyContainer,
        final int aFluidAmount, final boolean aGenerateCell, final boolean aCustomTexture) {
        if (aCustomTexture) {
            return addGTFluid(
                aName,
                aName,
                aLocalized,
                rgba,
                aState,
                aTemperatureK,
                aFullContainer,
                aEmptyContainer,
                aFluidAmount,
                aGenerateCell,
                true);
        } else {
            return addGTFluid(
                aName,
                "fluid.autogenerated",
                aLocalized,
                rgba,
                aState,
                aTemperatureK,
                aFullContainer,
                aEmptyContainer,
                aFluidAmount,
                aGenerateCell,
                false);
        }
    }

    public static Fluid addGtFluid(final String aName, final String aLocalized, final short[] rgba, final int aState,
        final long aTemperatureK, final ItemStack aFullContainer, final ItemStack aEmptyContainer,
        final int aFluidAmount, final boolean aGenerateCell) {
        return addGTFluid(
            aName,
            "fluid.autogenerated",
            aLocalized,
            rgba,
            aState,
            aTemperatureK,
            aFullContainer,
            aEmptyContainer,
            aFluidAmount,
            aGenerateCell,
            false);
    }

    public static Fluid addGTFluidMolten(final String aName, final String aLocalized, final short[] aRGBa,
        final int aState, final long aTemperatureK, final ItemStack aFullContainer, final ItemStack aEmptyContainer,
        final int aFluidAmount, final boolean aGenerateCell, final Material aMaterial) {
        return addGTFluid(
            "molten." + aName,
            "molten." + aMaterial.getTextureSet().aTextCustomAutogenerated,
            aLocalized,
            aRGBa,
            aState,
            aTemperatureK,
            aFullContainer,
            aEmptyContainer,
            aFluidAmount,
            aGenerateCell,
            aMaterial.getTextureSet().is_custom);
    }

    public static Fluid addGTFluidNonMolten(final String aName, final String aLocalized, final short[] aRGBa,
        final int aState, final long aTemperatureK, final ItemStack aFullContainer, final ItemStack aEmptyContainer,
        final int aFluidAmount, final boolean aGenerateCell) {
        return addGTFluid(
            "fluid." + aName,
            "fluid.autogenerated",
            aLocalized,
            aRGBa,
            aState,
            aTemperatureK,
            aFullContainer,
            aEmptyContainer,
            aFluidAmount,
            aGenerateCell,
            false);
    }

    public static Fluid addGTFluidNoPrefix(final String aName, final String aLocalized, final short[] aRGBa,
        final int aState, final long aTemperatureK, final ItemStack aFullContainer, final ItemStack aEmptyContainer,
        final int aFluidAmount, final boolean aGenerateCell) {
        return addGTFluid(
            aName,
            "fluid.autogenerated",
            aLocalized,
            aRGBa,
            aState,
            aTemperatureK,
            aFullContainer,
            aEmptyContainer,
            aFluidAmount,
            aGenerateCell,
            false);
    }

    // Gas
    public static Fluid addGtGas(final String aName, final String aLocalized, final short[] aRGBa, final int aState,
        final long aTemperatureK, final ItemStack aFullContainer, final ItemStack aEmptyContainer,
        final int aFluidAmount, final boolean aGenerateCell) {
        return addGTFluid(
            aName,
            "fluid.autogenerated",
            aLocalized,
            aRGBa,
            aState,
            aTemperatureK,
            aFullContainer,
            aEmptyContainer,
            aFluidAmount,
            aGenerateCell,
            false);
    }

    public static Fluid addGTPlasma(final Material aMaterial) {
        if (aMaterial.getDefaultLocalName()
            .toLowerCase()
            .contains("clay")
            || (aMaterial.getComposites()
                .size() > 1)
            || aMaterial.getDefaultLocalName()
                .toLowerCase()
                .contains("wrought")) {
            return null;
        }
        Logger.INFO("Generating a " + aMaterial.getDefaultLocalName() + " Plasma Cell");
        if (aMaterial.vComponentCount != 1) {
            Logger.INFO("Compound made from: ");
            for (final MaterialStack x : aMaterial.getComposites()) {
                Logger.INFO(
                    x.getStackMaterial()
                        .getDefaultLocalName());
            }
            Logger.INFO("Material is a composite, not generating plasma.");
            return null;
        }

        ItemStack temp = null;
        // Generate a Cell if we need to
        if (ItemUtils.getItemStackOfAmountFromOreDictNoBroken("cellPlasma" + aMaterial.getUnlocalizedName(), 1)
            == null) {
            new BaseItemPlasmaCell(aMaterial);
            temp = aMaterial.getPlasmaCell(1);
        } else {
            temp = ItemUtils.getItemStackOfAmountFromOreDictNoBroken("cellPlasma" + aMaterial.getUnlocalizedName(), 1);
        }
        short[] rgba = aMaterial.getRGBA();
        if (aMaterial.getTextureSet().is_custom) {
            rgba = new short[] { 255, 255, 255, 255 };
        }
        if (temp != null) {
            return addGTFluid(
                "plasma." + StringUtils.sanitizeString(
                    aMaterial.getDefaultLocalName()
                        .toLowerCase()),
                "plasma." + aMaterial.getTextureSet().aTextCustomAutogenerated,
                aMaterial.getDefaultLocalName() + " Plasma",
                rgba,
                3,
                10000,
                temp,
                ItemList.Cell_Empty.get(1),
                1000,
                false,
                false);
        }
        return null;
    }

    public static Fluid addGTFluid(String aName, final String aTexture, final String aLocalized, short[] aRGBa,
        final int aState, final long aTemperatureK, ItemStack aFullContainer, final ItemStack aEmptyContainer,
        final int aFluidAmount, final boolean aGenerateFilledCell, final boolean aCustomTexture) {

        String aNameOriginal = aName;
        Logger.INFO("Generating Fluid for " + aName);

        aName = StringUtils.sanitizeString(aName.toLowerCase());

        String aLocalName = (aLocalized == null) ? aName : aLocalized;

        Fluid rFluid;
        Fluid gFluid = FluidRegistry.getFluid(aName);
        FluidStack aCheck = FluidUtils.getWildcardFluidStack(aName.toLowerCase(), 1000);
        boolean register = false;
        if (aCheck != null) {
            rFluid = aCheck.getFluid();
        } else if (gFluid != null) {
            rFluid = gFluid;
        } else {
            short[] rRGB = aRGBa;
            if (aCustomTexture) {
                rRGB = new short[] { 255, 255, 255, 255 };
            }
            rFluid = new FluidGT6(aName, aTexture, (rRGB != null) ? rRGB : Dyes._NULL.getRGBA(), aLocalName);
            register = true;
        }

        if (register) {
            if (FluidRegistry.registerFluid(rFluid)) {
                switch (aState) {
                    case 0 -> {
                        rFluid.setGaseous(false);
                        rFluid.setViscosity(10000);
                    }
                    case 1, 4 -> {
                        rFluid.setGaseous(false);
                        rFluid.setViscosity(1000);
                    }
                    case 2 -> {
                        rFluid.setGaseous(true);
                        rFluid.setDensity(-100);
                        rFluid.setViscosity(200);
                    }
                    case 3 -> {
                        rFluid.setGaseous(true);
                        rFluid.setDensity(-10000);
                        rFluid.setViscosity(10);
                        rFluid.setLuminosity(15);
                    }
                }
            }
        }

        String aNameNonMolten = aLocalName.contains("Molten") ? aLocalName.replace("Molten", "") : aLocalName;

        if (aFullContainer == null) {
            ItemStack oreStack = ItemUtils.getItemStackOfAmountFromOreDictNoBroken("cell" + aLocalName, 1);
            aFullContainer = oreStack;
            if (aFullContainer == null) {
                oreStack = ItemUtils.getItemStackOfAmountFromOreDictNoBroken("cell" + aNameOriginal, 1);
                aFullContainer = oreStack;
                if (aFullContainer == null) {
                    oreStack = ItemUtils.getItemStackOfAmountFromOreDictNoBroken("cell" + aNameNonMolten, 1);
                    aFullContainer = oreStack;
                    if (aFullContainer != null) {
                        Logger.INFO("Found cell for " + aNameNonMolten);
                    }
                } else {
                    Logger.INFO("Found cell for " + aNameOriginal);
                }
            } else {
                Logger.INFO("Found cell for " + aLocalName);
            }
        }

        Item tempCell = null;
        // Generate a Cell if we need to
        if (aGenerateFilledCell && aFullContainer == null) {
            String aMatName = aNameOriginal;
            if (aMatName.contains("molten.")) {
                aMatName = aMatName.replace("molten.", "");
                aMatName = aMatName.substring(0, 1)
                    .toUpperCase() + aMatName.substring(1);
            }
            if (aMatName.contains("fluid.")) {
                aMatName = aMatName.replace("fluid.", "");
                aMatName = aMatName.substring(0, 1)
                    .toUpperCase() + aMatName.substring(1);
            }
            Logger.INFO("Generating cell for " + aMatName + ", " + aLocalName);
            tempCell = new BaseItemComponent(aMatName, rFluid, aLocalName, aRGBa);
            aFullContainer = new ItemStack(tempCell);
        }

        if ((rFluid.getTemperature() == new Fluid("test").getTemperature()) || (rFluid.getTemperature() <= 0)) {
            rFluid.setTemperature((int) (aTemperatureK));
        }
        if ((aFullContainer != null) && (aEmptyContainer != null)
            && !FluidContainerRegistry
                .registerFluidContainer(new FluidStack(rFluid, aFluidAmount), aFullContainer, aEmptyContainer)) {
            GTValues.RA.stdBuilder()
                .itemInputs(ItemList.Cell_Empty.get(1L))
                .itemOutputs(aFullContainer)
                .fluidInputs(new FluidStack(rFluid, aFluidAmount))
                .duration(4)
                .eut(1)
                .addTo(cannerRecipes);
        }
        return rFluid;
    }

    public static Fluid generateFluidNonMolten(final String unlocalizedName, final String localizedName,
        final int MeltingPoint, final short[] RGBA, final ItemStack dustStack, final ItemStack dustStack2) {
        return generateFluidNonMolten(
            unlocalizedName,
            localizedName,
            MeltingPoint,
            RGBA,
            dustStack,
            dustStack2,
            144,
            true);
    }

    public static Fluid generateFluidNonMolten(final String unlocalizedName, final String localizedName,
        final int MeltingPoint, final short[] RGBA, final ItemStack dustStack, final ItemStack dustStack2,
        final boolean aGenerateCell) {
        return generateFluidNonMolten(
            unlocalizedName,
            localizedName,
            MeltingPoint,
            RGBA,
            dustStack,
            dustStack2,
            144,
            aGenerateCell);
    }

    public static Fluid generateFluidNonMolten(final String unlocalizedName, final String localizedName,
        final int MeltingPoint, final short[] RGBA, ItemStack dustStack, final ItemStack dustStack2,
        final int amountPerItem, final boolean aGenerateCell) {
        if (dustStack == null) {
            dustStack = ItemUtils
                .getItemStackOfAmountFromOreDictNoBroken("dust" + StringUtils.sanitizeString(localizedName), 1);
        }
        FluidStack aFStack = FluidRegistry.getFluidStack(unlocalizedName.toLowerCase(), 1);
        if (aFStack == null) {
            Logger.WARNING("Generating our own fluid.");

            final Fluid gtFluid = FluidUtils.addGTFluidNonMolten(
                unlocalizedName,
                localizedName,
                RGBA,
                4,
                MeltingPoint,
                null,
                ItemList.Cell_Empty.get(1),
                1000,
                aGenerateCell);

            if (dustStack != null) {
                GTValues.RA.stdBuilder()
                    .itemInputs(dustStack)
                    .fluidOutputs(new FluidStack(gtFluid, amountPerItem))
                    .duration(1 * SECONDS)
                    .eut(TierEU.RECIPE_LV / 2)
                    .addTo(fluidExtractionRecipes);
            }
            if (dustStack2 != null) {
                GTValues.RA.stdBuilder()
                    .itemInputs(dustStack2)
                    .fluidOutputs(new FluidStack(gtFluid, amountPerItem))
                    .duration(1 * SECONDS)
                    .eut(TierEU.RECIPE_LV / 2)
                    .addTo(fluidExtractionRecipes);
            }

            return gtFluid;
        } else {
            Logger.INFO("FLUID GENERATION FAILED FOR " + localizedName + ", ALREADY EXISTS");
            return aFStack.getFluid();
        }
    }

    public static Fluid generateFluidNoPrefix(final String unlocalizedName, final String localizedName,
        final int MeltingPoint, final short[] RGBA) {
        return generateFluidNoPrefix(unlocalizedName, localizedName, MeltingPoint, RGBA, true);
    }

    public static Fluid generateFluidNoPrefix(final String unlocalizedName, final String localizedName,
        final int MeltingPoint, final short[] RGBA, final boolean aGenerateCell) {
        Fluid fluid = FluidRegistry.getFluid(unlocalizedName.toLowerCase());
        if (fluid == null) {
            Logger.WARNING("Generating our own fluid.");
            fluid = FluidUtils.addGTFluidNoPrefix(
                unlocalizedName,
                localizedName,
                RGBA,
                4,
                MeltingPoint,
                null,
                ItemList.Cell_Empty.get(1),
                1000,
                aGenerateCell);
        }
        return fluid;
    }

    public static Fluid generateGas(final String unlocalizedName, final String localizedName, final int MeltingPoint,
        final short[] RGBA, final boolean aGenerateCell) {
        Fluid fluid = FluidRegistry.getFluid(unlocalizedName.toLowerCase());
        if (fluid == null) {
            Logger.WARNING("Generating our own gas.");
            fluid = FluidUtils.addGtGas(
                unlocalizedName,
                localizedName,
                RGBA,
                3,
                MeltingPoint,
                null,
                ItemList.Cell_Empty.get(1),
                1000,
                aGenerateCell);
        }
        return fluid;
    }

    // Used in waila
    public static FluidStack getWildcardFluidStack(String aFluidName, int amount) {
        FluidStack aFStack1 = (FluidRegistry.getFluidStack(aFluidName, amount));
        FluidStack aFStack2 = (FluidRegistry.getFluidStack(aFluidName.toLowerCase(), amount));
        FluidStack aFStack3 = (FluidRegistry.getFluidStack("molten" + "." + aFluidName.toLowerCase(), amount));
        FluidStack aFStack4 = (FluidRegistry.getFluidStack("fluid" + "." + aFluidName.toLowerCase(), amount));
        FluidStack aFStack5 = (FluidRegistry.getFluidStack("liquid_" + aFluidName.toLowerCase(), amount));
        FluidStack aFStack6 = (FluidRegistry.getFluidStack("liquid" + "." + aFluidName.toLowerCase(), amount));
        if (aFStack1 != null) {
            return aFStack1;
        }
        if (aFStack2 != null) {
            return aFStack2;
        }
        if (aFStack3 != null) {
            return aFStack3;
        }
        if (aFStack4 != null) {
            return aFStack4;
        }
        if (aFStack5 != null) {
            return aFStack5;
        }
        return aFStack6;
    }

    public static FluidStack getWildcardFluidStack(Materials aMaterial, int amount) {
        FluidStack aFStack1 = aMaterial.getFluid(amount);
        FluidStack aFStack2 = aMaterial.getGas(amount);
        FluidStack aFStack3 = aMaterial.getMolten(amount);
        FluidStack aFStack4 = aMaterial.getSolid(amount);
        if (aFStack1 != null) {
            return aFStack1;
        } else if (aFStack2 != null) {
            return aFStack2;
        } else if (aFStack3 != null) {
            return aFStack3;
        } else return aFStack4;
    }
}
