package gregtech.common.tileentities.machines.multi.drone;

import java.io.IOException;
import java.util.UUID;

import net.minecraft.item.ItemStack;
import net.minecraft.nbt.NBTTagCompound;
import net.minecraft.network.PacketBuffer;
import net.minecraft.tileentity.TileEntity;
import net.minecraft.util.ChunkCoordinates;
import net.minecraft.util.StatCollector;
import net.minecraft.world.World;
import net.minecraftforge.common.DimensionManager;

import com.cleanroommc.modularui.network.NetworkUtils;

import gregtech.api.interfaces.tileentity.IGregTechTileEntity;
import gregtech.api.metatileentity.implementations.MTEMultiBlockBase;
import gregtech.api.util.GTUtil;
import gregtech.api.util.shutdown.ShutDownReason;

public class DroneConnection {

    // Generated by machine coordinate and worldID
    public UUID uuid;

    private final String unlocalizedName;
    private final ItemStack machineItem;
    private final ChunkCoordinates machineCoord;
    private final ChunkCoordinates centreCoord;
    private final int centreWorld;
    private final int machineWorld;
    private final int machineFacing;

    private String customName;
    private boolean machineStatus;
    private String shutdownReason;
    private boolean isSelected;
    private long groupMask;

    private final MTEMultiBlockBase cachedCentre;
    private final MTEMultiBlockBase cachedMachine;

    public DroneConnection(MTEMultiBlockBase machine, MTEDroneCentre centre) {
        this.machineItem = machine.getStackForm(1);
        this.machineCoord = machine.getBaseMetaTileEntity()
            .getCoords();
        this.centreCoord = centre.getBaseMetaTileEntity()
            .getCoords();
        this.cachedCentre = centre;
        this.cachedMachine = machine;
        this.centreWorld = centre.getBaseMetaTileEntity()
            .getWorld().provider.dimensionId;
        this.machineWorld = machine.getBaseMetaTileEntity()
            .getWorld().provider.dimensionId;
        this.machineFacing = machine.getBaseMetaTileEntity()
            .getFrontFacing()
            .ordinal();
        this.uuid = UUID.nameUUIDFromBytes((machineCoord.toString() + machineWorld).getBytes());
        this.unlocalizedName = machine.mName;
        this.customName = centre.getConnectionName(uuid.toString(), machine.getLocalName());
        this.groupMask = centre.getConnectionGroups(uuid.toString());
        this.machineStatus = machine.isAllowedToWork();
        this.shutdownReason = machine.getBaseMetaTileEntity()
            .getLastShutDownReason()
            .getDisplayString();
    }

    public DroneConnection(NBTTagCompound aNBT) {
        NBTTagCompound machineTag = aNBT.getCompoundTag("machine");
        NBTTagCompound centreTag = aNBT.getCompoundTag("centre");
        this.centreWorld = aNBT.getInteger("centreWorld");
        this.machineWorld = aNBT.getInteger("machineWorld");
        this.machineFacing = aNBT.getInteger("machineFacing");
        machineItem = ItemStack.loadItemStackFromNBT(aNBT.getCompoundTag("item"));
        machineCoord = new ChunkCoordinates(
            machineTag.getInteger("x"),
            machineTag.getInteger("y"),
            machineTag.getInteger("z"));
        centreCoord = new ChunkCoordinates(
            centreTag.getInteger("x"),
            centreTag.getInteger("y"),
            centreTag.getInteger("z"));
        this.customName = aNBT.getString("name");
        this.unlocalizedName = aNBT.getString("unlocalizedName");
        this.uuid = UUID.fromString(aNBT.getString("uuid"));
        this.machineStatus = aNBT.getBoolean("machineStatus");
        this.shutdownReason = aNBT.getString("shutdownReason");
        this.isSelected = aNBT.getBoolean("isSelected");
        this.groupMask = aNBT.getLong("groupMask");
        if (!NetworkUtils.isClient()) {
            this.cachedCentre = getLoadedGTBaseMachineAt(centreCoord, DimensionManager.getWorld(centreWorld), false);
            this.cachedMachine = getLoadedGTBaseMachineAt(machineCoord, DimensionManager.getWorld(machineWorld), false);
        } else {
            this.cachedCentre = null;
            this.cachedMachine = null;
        }
    }

    public MTEMultiBlockBase getLinkedMachine() {
        return cachedMachine;
    }

    public MTEMultiBlockBase getLinkedCentre() {
        return cachedCentre;
    }

    public String getCustomName() {
        return customName;
    }

    public ChunkCoordinates getCentreCoord() {
        return centreCoord;
    }

    public ChunkCoordinates getMachineCoord() {
        return machineCoord;
    }

    public ItemStack getMachineItem() {
        return machineItem;
    }

    public String getLocalizedName() {
        return StatCollector.translateToLocal("gt.blockmachines." + unlocalizedName + ".name");
    }

    public float getDistanceSquared() {
        return centreCoord.getDistanceSquaredToChunkCoordinates(machineCoord);
    }

    public void setCustomName(String name) {
        customName = name;
        if (cachedCentre instanceof MTEDroneCentre dc) {
            dc.setConnectionName(uuid.toString(), name);
        }
    }

    public boolean isMachineShutdown() {
        return !shutdownReason.isEmpty() && !machineStatus;
    }

    public String getShutdownReason() {
        return shutdownReason;
    }

    public NBTTagCompound writeToNBT() {
        NBTTagCompound aNBT = new NBTTagCompound();
        aNBT.setTag("machine", transCoordsToNBT(machineCoord));
        aNBT.setTag("centre", transCoordsToNBT(centreCoord));
        aNBT.setTag("item", machineItem.writeToNBT(new NBTTagCompound()));
        aNBT.setInteger("centreWorld", centreWorld);
        aNBT.setInteger("machineWorld", machineWorld);
        aNBT.setInteger("machineFacing", machineFacing);
        aNBT.setString("name", getCustomName());
        aNBT.setString("unlocalizedName", unlocalizedName);
        aNBT.setString("uuid", this.uuid.toString());
        aNBT.setBoolean("machineStatus", machineStatus);
        aNBT.setString("shutdownReason", shutdownReason);
        aNBT.setBoolean("isSelected", isSelected);
        aNBT.setLong("groupMask", groupMask);
        return aNBT;
    }

    public MTEMultiBlockBase getLoadedGTBaseMachineAt(ChunkCoordinates coords, World world, boolean isLoaded) {
        if (coords == null || world == null) return null;
        TileEntity te = GTUtil.getTileEntity(world, coords, isLoaded);
        if (te == null) return null;
        return (MTEMultiBlockBase) ((IGregTechTileEntity) te).getMetaTileEntity();
    }

    private NBTTagCompound transCoordsToNBT(ChunkCoordinates coord) {
        NBTTagCompound tag = new NBTTagCompound();
        tag.setInteger("x", coord.posX);
        tag.setInteger("y", coord.posY);
        tag.setInteger("z", coord.posZ);
        return tag;
    }

    public boolean isValid() {
        return cachedCentre != null && cachedMachine != null && cachedCentre.isValid() && cachedMachine.isValid();
    }

    public void setShutdownReason(ShutDownReason reason) {
        shutdownReason = reason.getDisplayString();
    }

    public static DroneConnection deserialize(PacketBuffer buf) throws IOException {
        NBTTagCompound tag = buf.readNBTTagCompoundFromBuffer();
        if (tag == null) return null;
        return new DroneConnection(tag);
    }

    public static void serialize(PacketBuffer buf, DroneConnection connection) throws IOException {
        buf.writeNBTTagCompoundToBuffer(connection.writeToNBT());
    }

    public static boolean areEqual(DroneConnection a, DroneConnection b) {
        if (a == null || b == null) return false;
        return a.customName.equals(b.customName) && a.isSelected == b.isSelected
            && a.machineStatus == b.machineStatus
            && a.shutdownReason.equals(b.shutdownReason)
            && a.groupMask == b.groupMask;
    }

    public boolean isActive() {
        return machineStatus;
    }

    public void setActive(boolean active) {
        machineStatus = active;
    }

    public void setSelect(boolean bool) {
        isSelected = bool;
    }

    public boolean isSelected() {
        return isSelected;
    }

    public long getGroupMask() {
        return groupMask;
    }

    public void setGroupMask(long groupMask) {
        this.groupMask = groupMask;
        if (cachedCentre instanceof MTEDroneCentre dc) {
            dc.setConnectionGroups(uuid.toString(), groupMask);
        }
    }

    public int getMachineWorld() {
        return machineWorld;
    }

    public int getMachineFacing() {
        return machineFacing;
    }
}
