package miscutil.gregtech.api.enums;

import gregtech.api.enums.Textures;
import gregtech.api.interfaces.IIconContainer;

public class GregtechTextureSet {
    public static final GregtechTextureSet
            SET_NONE = new GregtechTextureSet("NONE"), SET_DULL = new GregtechTextureSet("DULL"), SET_RUBY = new GregtechTextureSet("RUBY"), SET_OPAL = new GregtechTextureSet("OPAL"), SET_LEAF = new GregtechTextureSet("LEAF"), SET_WOOD = new GregtechTextureSet("WOOD"), SET_SAND = new GregtechTextureSet("SAND"), SET_FINE = new GregtechTextureSet("FINE"), SET_FIERY = new GregtechTextureSet("FIERY"), SET_FLUID = new GregtechTextureSet("FLUID"), SET_ROUGH = new GregtechTextureSet("ROUGH"), SET_PAPER = new GregtechTextureSet("PAPER"), SET_GLASS = new GregtechTextureSet("GLASS"), SET_FLINT = new GregtechTextureSet("FLINT"), SET_LAPIS = new GregtechTextureSet("LAPIS"), SET_SHINY = new GregtechTextureSet("SHINY"), SET_SHARDS = new GregtechTextureSet("SHARDS"), SET_POWDER = new GregtechTextureSet("POWDER"), SET_QUARTZ = new GregtechTextureSet("QUARTZ"), SET_EMERALD = new GregtechTextureSet("EMERALD"), SET_DIAMOND = new GregtechTextureSet("DIAMOND"), SET_LIGNITE = new GregtechTextureSet("LIGNITE"), SET_MAGNETIC = new GregtechTextureSet("MAGNETIC"), SET_METALLIC = new GregtechTextureSet("METALLIC"), SET_NETHERSTAR = new GregtechTextureSet("NETHERSTAR"), SET_GEM_VERTICAL = new GregtechTextureSet("GEM_VERTICAL"), SET_GEM_HORIZONTAL = new GregtechTextureSet("GEM_HORIZONTAL");

    public final IIconContainer[] mTextures = new IIconContainer[128];
    public final String mSetName;

    public GregtechTextureSet(String aSetName) {
        mSetName = aSetName;
        mTextures[0] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/turbineBlade");
        mTextures[1] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[2] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[3] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[4] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[5] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[6] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[7] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[8] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[9] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[10] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[11] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[12] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[13] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[14] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[15] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[16] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[17] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[18] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[19] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[20] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[21] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[22] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[23] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[24] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[25] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[26] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[27] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[28] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[29] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[30] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[31] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[32] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[33] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[34] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[35] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[36] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[37] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[38] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[39] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[40] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[41] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[42] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[43] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[44] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[45] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[46] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[47] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[48] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[49] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[50] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[51] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[52] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[53] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[54] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[55] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[56] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[57] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[58] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[59] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[60] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[61] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[62] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[63] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[64] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[65] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[66] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[67] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[68] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[69] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[70] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[71] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[72] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[73] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[74] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[75] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[76] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[77] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[78] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[79] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[80] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[81] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[82] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[83] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[84] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[85] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[86] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[87] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[88] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[89] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[90] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[91] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[92] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[93] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[94] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[95] = new Textures.BlockIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[96] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[97] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[98] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[99] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[100] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[101] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[102] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[103] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[104] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[105] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[106] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[107] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[108] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[109] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[110] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[111] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[112] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[113] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[114] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[115] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[116] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[117] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[118] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[119] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[120] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[121] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[122] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[123] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[124] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[125] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[126] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
        mTextures[127] = new Textures.ItemIcons.CustomIcon("materialicons/" + mSetName + "/void");
    }
}