package gregtech.api.enums;

import gregtech.GTMod;
import it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap;

public class MaterialsIDMap extends Int2ObjectOpenHashMap<Materials> {

    MaterialsIDMap() {
        // spotless:off
        r(  0, Materials.Empty);
        r(  1, Materials.Hydrogen);
        r(  2, Materials.Deuterium);
        r(  3, Materials.Tritium);
        r(  4, Materials.Helium);
        r(  5, Materials.Helium3);
        r(  6, Materials.Lithium);
        r(  8, Materials.Beryllium);
        r(  9, Materials.Boron);
        r( 10, Materials.Carbon);
        r( 12, Materials.Nitrogen);
        r( 13, Materials.Oxygen);
        r( 14, Materials.Fluorine);
        r( 17, Materials.Sodium);
        r( 18, Materials.Magnesium);
        r( 19, Materials.Aluminium);
        r( 20, Materials.Silicon);
        r( 21, Materials.Phosphorus);
        r( 22, Materials.Sulfur);
        r( 23, Materials.Chlorine);
        r( 24, Materials.Argon);
        r( 25, Materials.Potassium);
        r( 26, Materials.Calcium);
        r( 27, Materials.Scandium);
        r( 28, Materials.Titanium);
        r( 29, Materials.Vanadium);
        r( 30, Materials.Chrome);
        r( 31, Materials.Manganese);
        r( 32, Materials.Iron);
        r( 33, Materials.Cobalt);
        r( 34, Materials.Nickel);
        r( 35, Materials.Copper);
        r( 36, Materials.Zinc);
        r( 37, Materials.Gallium);
        r( 39, Materials.Arsenic);
        r( 43, Materials.Rubidium);
        r( 44, Materials.Strontium);
        r( 45, Materials.Yttrium);
        r( 47, Materials.Niobium);
        r( 48, Materials.Molybdenum);
        r( 52, Materials.Palladium);
        r( 54, Materials.Silver);
        r( 55, Materials.Cadmium);
        r( 56, Materials.Indium);
        r( 57, Materials.Tin);
        r( 58, Materials.Antimony);
        r( 59, Materials.Tellurium);
        r( 62, Materials.Caesium);
        r( 63, Materials.Barium);
        r( 64, Materials.Lanthanum);
        r( 65, Materials.Cerium);
        r( 66, Materials.Praseodymium);
        r( 67, Materials.Neodymium);
        r( 68, Materials.Promethium);
        r( 69, Materials.Samarium);
        r( 70, Materials.Europium);
        r( 71, Materials.Gadolinium);
        r( 72, Materials.Terbium);
        r( 73, Materials.Dysprosium);
        r( 74, Materials.Holmium);
        r( 75, Materials.Erbium);
        r( 76, Materials.Thulium);
        r( 77, Materials.Ytterbium);
        r( 78, Materials.Lutetium);
        r( 80, Materials.Tantalum);
        r( 81, Materials.Tungsten);
        r( 83, Materials.Osmium);
        r( 84, Materials.Iridium);
        r( 85, Materials.Platinum);
        r( 86, Materials.Gold);
        r( 87, Materials.Mercury);
        r( 89, Materials.Lead);
        r( 90, Materials.Bismuth);
        r( 93, Materials.Radon);
        r( 96, Materials.Thorium);
        r( 97, Materials.Uranium235);
        r( 98, Materials.Uranium);
        r(100, Materials.Plutonium);
        r(101, Materials.Plutonium241);
        r(103, Materials.Americium);
        r(106, Materials.Space);
        r(109, Materials.ExcitedDTCC);
        r(110, Materials.TengamRaw);
        r(111, Materials.TengamPurified);
        r(112, Materials.TengamAttuned);
        r(113, Materials.ExcitedDTPC);
        r(118, Materials.NetherAir);
        r(119, Materials.NetherSemiFluid);
        r(120, Materials.NefariousGas);
        r(121, Materials.ExcitedDTRC);
        r(122, Materials.NefariousOil);
        r(123, Materials.PoorNetherWaste);
        r(124, Materials.RichNetherWaste);
        r(125, Materials.HellishMetal);
        r(126, Materials.ExcitedDTEC);
        r(127, Materials.ExcitedDTSC);
        r(129, Materials.Neutronium);
        r(130, Materials.DTSC);
        r(131, Materials.SuperconductorUIVBase);
        r(132, Materials.Netherite);
        r(133, Materials.ActivatedNetherite);
        r(134, Materials.SuperconductorUMVBase);
        r(135, Materials.PrismarineSolution);
        r(136, Materials.PrismarineContaminatedHydrogenPeroxide);
        r(137, Materials.PrismarineRichNitrobenzeneSolution);
        r(138, Materials.PrismarineContaminatedNitrobenzeSolution);
        r(139, Materials.Universium);
        r(140, Materials.SuperCoolant);
        r(141, Materials.Eternity);
        r(142, Materials.PrimordialMatter);
        r(143, Materials.MagMatter);
        r(144, Materials.QuarkGluonPlasma);
        r(145, Materials.PhononMedium);
        r(146, Materials.PhononCrystalSolution);
        r(147, Materials.SixPhasedCopper);
        r(148, Materials.Mellion);
        r(149, Materials.Creon);
        r(150, Materials.GravitonShard);
        r(151, Materials.DimensionallyShiftedSuperfluid);
        r(152, Materials.MoltenProtoHalkoniteBase);
        r(153, Materials.HotProtoHalkonite);
        r(154, Materials.ProtoHalkonite);
        r(155, Materials.MoltenExoHalkoniteBase);
        r(156, Materials.HotExoHalkonite);
        r(157, Materials.ExoHalkonite);
        r(158, Materials.Antimatter);
        r(159, Materials.Protomatter);
        r(160, Materials.StargateCrystalSlurry);
        r(161, Materials.PrismaticGas);
        r(162, Materials.PrismaticAcid);
        r(163, Materials.PrismaticNaquadah);
        r(164, Materials.PrismaticNaquadahCompositeSlurry);
        r(165, Materials.LumipodExtract);
        r(166, Materials.BiocatalyzedPropulsionFluid);
        r(167, Materials.Chlorite);
        r(168, Materials.Staurolite);
        r(169, Materials.Cordierite);
        r(170, Materials.Datolite);
        r(171, Materials.MetamorphicMineralMixture);
        r(172, Materials.Plagioclase);
        r(201, Materials.Manasteel);
        r(202, Materials.Terrasteel);
        r(203, Materials.ElvenElementium);
        r(204, Materials.Livingrock);
        r(205, Materials.GaiaSpirit);
        r(206, Materials.Livingwood);
        r(207, Materials.Dreamwood);
        r(208, Materials.ManaDiamond);
        r(209, Materials.Dragonstone);
        r(232, Materials.DenseSteam);
        r(233, Materials.DenseSuperheatedSteam);
        r(234, Materials.DenseSupercriticalSteam);
        r(241, Materials.PlatinumGroupSludge);
        r(242, Materials.WeedEX9000);
        r(299, Materials.Stone);
        r(300, Materials.Bronze);
        r(301, Materials.Brass);
        r(302, Materials.Invar);
        r(303, Materials.Electrum);
        r(304, Materials.WroughtIron);
        r(305, Materials.Steel);
        r(306, Materials.StainlessSteel);
        r(307, Materials.PigIron);
        r(308, Materials.RedAlloy);
        r(309, Materials.BlueAlloy);
        r(310, Materials.Cupronickel);
        r(311, Materials.Nichrome);
        r(312, Materials.Kanthal);
        r(313, Materials.Magnalium);
        r(314, Materials.SolderingAlloy);
        r(315, Materials.BatteryAlloy);
        r(316, Materials.TungstenSteel);
        r(317, Materials.Osmiridium);
        r(318, Materials.Sunnarium);
        r(319, Materials.Adamantium);
        r(320, Materials.ElectrumFlux);
        r(321, Materials.Enderium);
        r(322, Materials.HSLA);
        r(323, Materials.InfusedGold);
        r(324, Materials.Naquadah);
        r(325, Materials.NaquadahAlloy);
        r(326, Materials.NaquadahEnriched);
        r(327, Materials.Naquadria);
        r(328, Materials.Duranium);
        r(329, Materials.Tritanium);
        r(330, Materials.Thaumium);
        r(331, Materials.Mithril);
        r(333, Materials.AstralSilver);
        r(334, Materials.BlackSteel);
        r(335, Materials.DamascusSteel);
        r(336, Materials.ShadowIron);
        r(337, Materials.ShadowSteel);
        r(338, Materials.IronWood);
        r(339, Materials.Steeleaf);
        r(340, Materials.MeteoricIron);
        r(341, Materials.MeteoricSteel);
        r(342, Materials.DarkIron);
        r(343, Materials.CobaltBrass);
        r(344, Materials.Ultimet);
        r(345, Materials.AnnealedCopper);
        r(346, Materials.FierySteel);
        r(347, Materials.Firestone);
        r(348, Materials.RedSteel);
        r(349, Materials.BlueSteel);
        r(350, Materials.SterlingSilver);
        r(351, Materials.RoseGold);
        r(352, Materials.BlackBronze);
        r(353, Materials.BismuthBronze);
        r(354, Materials.IronMagnetic);
        r(355, Materials.SteelMagnetic);
        r(356, Materials.NeodymiumMagnetic);
        r(357, Materials.VanadiumGallium);
        r(358, Materials.YttriumBariumCuprate);
        r(359, Materials.NiobiumNitride);
        r(360, Materials.NiobiumTitanium);
        r(361, Materials.ChromiumDioxide);
        r(362, Materials.Knightmetal);
        r(363, Materials.TinAlloy);
        r(364, Materials.DarkSteel);
        r(365, Materials.ElectricalSteel);
        r(366, Materials.EnergeticAlloy);
        r(367, Materials.VibrantAlloy);
        r(368, Materials.Shadow);
        r(369, Materials.ConductiveIron);
        r(370, Materials.TungstenCarbide);
        r(371, Materials.VanadiumSteel);
        r(372, Materials.HSSG);
        r(373, Materials.HSSE);
        r(374, Materials.HSSS);
        r(375, Materials.Rutile);
        r(376, Materials.Titaniumtetrachloride);
        r(377, Materials.Magnesiumchloride);
        r(378, Materials.PulsatingIron);
        r(379, Materials.Soularium);
        r(380, Materials.EnderiumBase);
        r(381, Materials.RedstoneAlloy);
        r(382, Materials.Ardite);
        r(383, Materials.Reinforced);
        r(384, Materials.Galgadorian);
        r(385, Materials.GalgadorianEnhanced);
        r(386, Materials.Manyullyn);
        r(387, Materials.Mytryl);
        r(388, Materials.BlackPlutonium);
        r(389, Materials.CallistoIce);
        r(390, Materials.Ledox);
        r(391, Materials.Quantium);
        r(392, Materials.Duralumin);
        r(393, Materials.Oriharukon);
        r(394, Materials.InfinityCatalyst);
        r(395, Materials.Bedrockium);
        r(396, Materials.Unstable);
        r(397, Materials.Infinity);
        r(398, Materials.MysteriousCrystal);
        r(399, Materials.SamariumMagnetic);
        r(400, Materials.Alumite);
        r(401, Materials.EndSteel);
        r(402, Materials.ClayCompound);
        r(403, Materials.CrystallineAlloy);
        r(404, Materials.MelodicAlloy);
        r(405, Materials.StellarAlloy);
        r(406, Materials.CrystallinePinkSlime);
        r(407, Materials.EnergeticSilver);
        r(408, Materials.VividAlloy);
        r(409, Materials.BauxiteSlurry);
        r(410, Materials.HeatedBauxiteSlurry);
        r(411, Materials.SluiceJuice);
        r(412, Materials.SluiceSand);
        r(413, Materials.BauxiteSlag);
        r(414, Materials.IlmeniteSlag);
        r(415, Materials.GreenSapphireJuice);
        r(416, Materials.SapphireJuice);
        r(417, Materials.RubyJuice);
        r(425, Materials.MTBEMixtureAlt);
        r(460, Materials.HydricSulfide);
        r(470, Materials.Epoxid);
        r(471, Materials.RubberSilicone);
        r(472, Materials.Polycaprolactam);
        r(473, Materials.Polytetrafluoroethylene);
        r(485, Materials.Alduorite);
        r(488, Materials.Rubracium);
        r(489, Materials.Vulcanite);
        r(493, Materials.LiquidOxygen);
        r(494, Materials.LiquidNitrogen);
        r(495, Materials.LiquidAir);
        r(496, Materials.NobleGases);
        r(497, Materials.CarbonDioxide);
        r(500, Materials.Diamond);
        r(501, Materials.Emerald);
        r(502, Materials.Ruby);
        r(503, Materials.Sapphire);
        r(504, Materials.GreenSapphire);
        r(505, Materials.Olivine);
        r(506, Materials.NetherStar);
        r(507, Materials.Topaz);
        r(508, Materials.Tanzanite);
        r(509, Materials.Amethyst);
        r(510, Materials.Opal);
        r(511, Materials.Jasper);
        r(512, Materials.Spinel);
        r(513, Materials.BlueTopaz);
        r(514, Materials.Amber);
        r(515, Materials.Dilithium);
        r(516, Materials.CertusQuartz);
        r(517, Materials.CertusQuartzCharged);
        r(518, Materials.Forcicium);
        r(519, Materials.Forcillium);
        r(520, Materials.Monazite);
        r(521, Materials.Force);
        r(522, Materials.NetherQuartz);
        r(523, Materials.Quartzite);
        r(524, Materials.Lazurite);
        r(525, Materials.Sodalite);
        r(526, Materials.Lapis);
        r(527, Materials.GarnetRed);
        r(528, Materials.GarnetYellow);
        r(529, Materials.Vinteum);
        r(530, Materials.Apatite);
        r(531, Materials.Niter);
        r(532, Materials.EnderPearl);
        r(533, Materials.EnderEye);
        r(534, Materials.TricalciumPhosphate);
        r(535, Materials.Coal);
        r(536, Materials.Charcoal);
        r(537, Materials.Jade);
        r(538, Materials.Lignite);
        r(540, Materials.InfusedAir);
        r(541, Materials.InfusedFire);
        r(542, Materials.InfusedEarth);
        r(543, Materials.InfusedWater);
        r(544, Materials.InfusedEntropy);
        r(545, Materials.InfusedOrder);
        r(546, Materials.RoastedCopper);
        r(547, Materials.RoastedAntimony);
        r(548, Materials.RoastedIron);
        r(549, Materials.RoastedNickel);
        r(550, Materials.RoastedZinc);
        r(551, Materials.RoastedCobalt);
        r(552, Materials.RoastedArsenic);
        r(553, Materials.RoastedLead);
        r(554, Materials.Grade1PurifiedWater);
        r(555, Materials.Grade2PurifiedWater);
        r(556, Materials.Grade3PurifiedWater);
        r(557, Materials.Grade4PurifiedWater);
        r(558, Materials.Grade5PurifiedWater);
        r(559, Materials.Grade6PurifiedWater);
        r(560, Materials.Grade7PurifiedWater);
        r(561, Materials.Grade8PurifiedWater);
        r(562, Materials.FlocculationWasteLiquid);
        r(563, Materials.ActivatedCarbon);
        r(564, Materials.PreActivatedCarbon);
        r(565, Materials.DirtyActivatedCarbon);
        r(566, Materials.PolyAluminiumChloride);
        r(567, Materials.GlueAdvanced);
        r(568, Materials.Ozone);
        r(569, Materials.StableBaryonicMatter);
        r(570, Materials.OilExtraHeavy);
        r(576, Materials.TPV);
        r(581, Materials.TranscendentMetal);
        r(582, Materials.EnrichedHolmium);
        r(583, Materials.MHDCSM);
        r(584, Materials.RawStarMatter);
        r(585, Materials.WhiteDwarfMatter);
        r(586, Materials.BlackDwarfMatter);
        r(587, Materials.Time);
        r(588, Materials.SpaceTime);
        r(589, Materials.DTR);
        r(590, Materials.PotassiumNitrade);
        r(591, Materials.ChromiumTrioxide);
        r(592, Materials.Nitrochlorobenzene);
        r(593, Materials.Dimethylbenzene);
        r(594, Materials.Potassiumdichromate);
        r(595, Materials.PhthalicAcid);
        r(596, Materials.Dichlorobenzidine);
        r(597, Materials.Diaminobenzidin);
        r(598, Materials.Diphenylisophthalate);
        r(599, Materials.Polybenzimidazole);
        r(600, Materials.SoulInfusedMedium);
        r(602, Materials.ReinforcedGlass);
        r(603, Materials.BioMediumRaw);
        r(604, Materials.BioMediumSterilized);
        r(605, Materials.Chlorobenzene);
        r(606, Materials.DilutedHydrochloricAcid);
        r(607, Materials.Pyrochlore);
        r(608, Materials.GrowthMediumRaw);
        r(609, Materials.GrowthMediumSterilized);
        r(610, Materials.EpoxidFiberReinforced);
        r(611, Materials.BorosilicateGlass);
        r(612, Materials.FerriteMixture);
        r(613, Materials.NickelZincFerrite);
        r(614, Materials.Massicot);
        r(615, Materials.ArsenicTrioxide);
        r(616, Materials.CobaltOxide);
        r(617, Materials.Zincite);
        r(618, Materials.AntimonyTrioxide);
        r(619, Materials.CupricOxide);
        r(620, Materials.Ferrosilite);
        r(621, Materials.Magnesia);
        r(622, Materials.Quicklime);
        r(623, Materials.Potash);
        r(624, Materials.SodaAsh);
        r(625, Materials.Brick);
        r(626, Materials.Fireclay);
        r(627, Materials.BioDiesel);
        r(628, Materials.NitrationMixture);
        r(629, Materials.Glycerol);
        r(630, Materials.SodiumBisulfate);
        r(631, Materials.PolyphenyleneSulfide);
        r(632, Materials.Dichlorobenzene);
        r(633, Materials.Polydimethylsiloxane);
        r(634, Materials.RawStyreneButadieneRubber);
        r(635, Materials.StyreneButadieneRubber);
        r(636, Materials.Polystyrene);
        r(637, Materials.Styrene);
        r(638, Materials.Isoprene);
        r(639, Materials.Tetranitromethane);
        r(640, Materials.DilutedSulfuricAcid);
        r(641, Materials.Ethenone);
        r(642, Materials.Ethane);
        r(643, Materials.Propane);
        r(644, Materials.Butane);
        r(645, Materials.Butene);
        r(646, Materials.Butadiene);
        r(647, Materials.Toluene);
        r(648, Materials.Epichlorohydrin);
        r(649, Materials.PolyvinylChloride);
        r(650, Materials.VinylChloride);
        r(651, Materials.SulfurDioxide);
        r(652, Materials.SulfurTrioxide);
        r(653, Materials.NitricAcid);
        r(654, Materials.Dimethylhydrazine);
        r(655, Materials.Chloramine);
        r(656, Materials.Dimethylamine);
        r(657, Materials.DinitrogenTetroxide);
        r(658, Materials.NitricOxide);
        r(659, Materials.Ammonia);
        r(660, Materials.WoodGas);
        r(661, Materials.WoodVinegar);
        r(662, Materials.WoodTar);
        r(663, Materials.Dimethyldichlorosilane);
        r(664, Materials.Chloromethane);
        r(665, Materials.PhosphorousPentoxide);
        r(666, Materials.Tetrafluoroethylene);
        r(667, Materials.HydrofluoricAcid);
        r(668, Materials.Chloroform);
        r(669, Materials.BisphenolA);
        r(670, Materials.AceticAcid);
        r(671, Materials.CalciumAcetateSolution);
        r(672, Materials.Acetone);
        r(673, Materials.Methanol);
        r(674, Materials.CarbonMonoxide);
        r(675, Materials.CharcoalByproducts);
        r(676, Materials.MetalMixture);
        r(677, Materials.Ethylene);
        r(678, Materials.Propene);
        r(679, Materials.VinylAcetate);
        r(680, Materials.PolyvinylAcetate);
        r(681, Materials.MethylAcetate);
        r(682, Materials.AllylChloride);
        r(683, Materials.HydrochloricAcid);
        r(684, Materials.HypochlorousAcid);
        r(685, Materials.SodiumHydroxide);
        r(686, Materials.Benzene);
        r(687, Materials.Phenol);
        r(688, Materials.Cumene);
        r(689, Materials.PhosphoricAcid);
        r(690, Materials.Vinegar);
        r(691, Materials.FermentedBiomass);
        r(692, Materials.SaltWater);
        r(693, Materials.IronIIIChloride);
        r(694, Materials.LifeEssence);
        r(695, Materials.SodiumCarbonate);
        r(696, Materials.SodiumAluminate);
        r(697, Materials.Aluminiumoxide);
        r(698, Materials.Aluminiumhydroxide);
        r(699, Materials.Cryolite);
        r(700, Materials.Lava);
        r(701, Materials.Water);
        r(702, Materials.Ice);
        r(703, Materials.UUMatter);
        r(704, Materials.Biomass);
        r(706, Materials.Ethanol);
        r(707, Materials.Oil);
        r(708, Materials.Diesel);
        r(709, Materials.NitroFuel);
        r(710, Materials.CoalFuel);
        r(711, Materials.FishOil);
        r(712, Materials.Creosote);
        r(713, Materials.SeedOil);
        r(714, Materials.Glyceryl);
        r(715, Materials.Methane);
        r(716, Materials.NitroCarbon);
        r(717, Materials.NitrogenDioxide);
        r(718, Materials.SodiumPersulfate);
        r(719, Materials.SodiumSulfide);
        r(720, Materials.SulfuricAcid);
        r(721, Materials.UUAmplifier);
        r(722, Materials.SeedOilHemp);
        r(723, Materials.SeedOilLin);
        r(724, Materials.Lubricant);
        r(725, Materials.Honey);
        r(726, Materials.Glue);
        r(727, Materials.FryingOilHot);
        r(728, Materials.Snow);
        r(729, Materials.HolyWater);
        r(730, Materials.OilHeavy);
        r(731, Materials.OilMedium);
        r(732, Materials.OilLight);
        r(733, Materials.NaturalGas);
        r(734, Materials.SulfuricGas);
        r(735, Materials.Gas);
        r(736, Materials.SulfuricNaphtha);
        r(737, Materials.SulfuricLightFuel);
        r(738, Materials.SulfuricHeavyFuel);
        r(739, Materials.Naphtha);
        r(740, Materials.LightFuel);
        r(741, Materials.HeavyFuel);
        r(742, Materials.LPG);
        r(743, Materials.RedMud);
        r(744, Materials.SodiumOxide);
        r(745, Materials.DTEC);
        r(746, Materials.DTRC);
        r(747, Materials.DTPC);
        r(748, Materials.DTCC);
        r(760, Materials.NaphthenicAcid);
        r(764, Materials.TerephthalicAcid);
        r(765, Materials.Kevlar);
        r(770, Materials.Endium);
        r(772, Materials.NickelAluminide);
        r(774, Materials.LiquidCrystalKevlar);
        r(775, Materials.CalciumCarbide);
        r(779, Materials.ParaPhenylenediamine);
        r(780, Materials.Nitroaniline);
        r(782, Materials.TerephthaloylChloride);
        r(784, Materials.PolyurethaneResin);
        r(787, Materials.Ethyleneglycol);
        r(789, Materials.EthyleneOxide);
        r(791, Materials.NickelTetracarbonyl);
        r(795, Materials.Methylenedianiline);
        r(796, Materials.MethyleneDiphenylDiisocyanate);
        r(797, Materials.Calciumhydride);
        r(798, Materials.Silane);
        r(799, Materials.Dichlorosilane);
        r(800, Materials.Gunpowder);
        r(801, Materials.Blaze);
        r(802, Materials.Flint);
        r(803, Materials.Sugar);
        r(804, Materials.Obsidian);
        r(805, Materials.Clay);
        r(806, Materials.Bone);
        r(807, Materials.Netherrack);
        r(808, Materials.Endstone);
        r(809, Materials.Wood);
        r(810, Materials.Redstone);
        r(811, Materials.Glowstone);
        r(812, Materials.Electrotine);
        r(813, Materials.Bluestone);
        r(814, Materials.NetherBrick);
        r(815, Materials.Ash);
        r(816, Materials.AshDark);
        r(817, Materials.Salt);
        r(818, Materials.HydratedCoal);
        r(819, Materials.Graphene);
        r(820, Materials.Almandine);
        r(821, Materials.Andradite);
        r(822, Materials.Bauxite);
        r(823, Materials.Calcite);
        r(824, Materials.Cassiterite);
        r(825, Materials.Chromite);
        r(826, Materials.Cinnabar);
        r(827, Materials.Cobaltite);
        r(828, Materials.Cooperite);
        r(829, Materials.DeepIron);
        r(830, Materials.Galena);
        r(831, Materials.Grossular);
        r(832, Materials.LiveRoot);
        r(833, Materials.Phosphate);
        r(834, Materials.Pyrite);
        r(835, Materials.Pyrope);
        r(836, Materials.Saltpeter);
        r(837, Materials.SiliconDioxide);
        r(838, Materials.Spessartine);
        r(839, Materials.Sphalerite);
        r(840, Materials.Tetrahedrite);
        r(841, Materials.Tungstate);
        r(842, Materials.Uvarovite);
        r(843, Materials.Pyrotheum);
        r(844, Materials.Basalt);
        r(845, Materials.Marble);
        r(846, Materials.Redrock);
        r(847, Materials.PotassiumFeldspar);
        r(848, Materials.Biotite);
        r(849, Materials.GraniteBlack);
        r(850, Materials.GraniteRed);
        r(851, Materials.Blizz);
        r(853, Materials.CobaltHexahydrate);
        r(854, Materials.ConstructionFoam);
        r(855, Materials.Chalcopyrite);
        r(856, Materials.SiliconSG);
        r(858, Materials.CrudeOil);
        r(861, Materials.Emery);
        r(862, Materials.Epidote);
        r(865, Materials.Graphite);
        r(867, Materials.Greenstone);
        r(868, Materials.Trinium);
        r(870, Materials.Magnetite);
        r(871, Materials.Malachite);
        r(872, Materials.Migmatite);
        r(873, Materials.Pitchblende);
        r(874, Materials.Polyethylene);
        r(876, Materials.Siltstone);
        r(877, Materials.Soapstone);
        r(878, Materials.Oilsands);
        r(879, Materials.Paper);
        r(880, Materials.Rubber);
        r(881, Materials.Wheat);
        r(882, Materials.Wulfenite);
        r(883, Materials.Powellite);
        r(884, Materials.Desh);
        r(885, Materials.Milk);
        r(886, Materials.Chocolate);
        r(887, Materials.Cocoa);
        r(888, Materials.Coffee);
        r(889, Materials.WoodSealed);
        r(890, Materials.Glass);
        r(891, Materials.RareEarth);
        r(892, Materials.MeatRaw);
        r(893, Materials.MeatCooked);
        r(894, Materials.Cheese);
        r(895, Materials.Chili);
        r(896, Materials.RubberRaw);
        r(897, Materials.ComplexityCatalyst);
        r(898, Materials.Cryotheum);
        r(899, Materials.EntropicCatalyst);
        r(900, Materials.Mirabilite);
        r(901, Materials.Mica);
        r(902, Materials.Talc);
        r(903, Materials.Trona);
        r(904, Materials.Barite);
        r(905, Materials.Bastnasite);
        r(906, Materials.Garnierite);
        r(907, Materials.Lepidolite);
        r(908, Materials.Magnesite);
        r(909, Materials.Pentlandite);
        r(910, Materials.Scheelite);
        r(911, Materials.Alunite);
        r(912, Materials.Chrysotile);
        r(913, Materials.Realgar);
        r(914, Materials.Dolomite);
        r(915, Materials.Wollastonite);
        r(916, Materials.Zeolite);
        r(917, Materials.BandedIron);
        r(918, Materials.Ilmenite);
        r(919, Materials.Pollucite);
        r(920, Materials.Spodumene);
        r(921, Materials.Tantalite);
        r(922, Materials.Uraninite);
        r(923, Materials.VanadiumMagnetite);
        r(924, Materials.Kyanite);
        r(925, Materials.Perlite);
        r(926, Materials.Pumice);
        r(927, Materials.Bentonite);
        r(928, Materials.FullersEarth);
        r(929, Materials.Kaolinite);
        r(930, Materials.BrownLimonite);
        r(931, Materials.YellowLimonite);
        r(932, Materials.Vermiculite);
        r(933, Materials.Glauconite);
        r(934, Materials.Gypsum);
        r(935, Materials.BasalticMineralSand);
        r(936, Materials.GraniticMineralSand);
        r(937, Materials.CassiteriteSand);
        r(938, Materials.GarnetSand);
        r(939, Materials.QuartzSand);
        r(940, Materials.VolcanicAsh);
        r(941, Materials.Borax);
        r(942, Materials.Molybdenite);
        r(943, Materials.Pyrolusite);
        r(944, Materials.RockSalt);
        r(945, Materials.Stibnite);
        r(946, Materials.Asbestos);
        r(947, Materials.Concrete);
        r(948, Materials.Diatomite);
        r(949, Materials.GlauconiteSand);
        r(951, Materials.Vyroxeres);
        r(952, Materials.Ceruclase);
        r(956, Materials.Tartarite);
        r(966, Materials.Orichalcum);
        r(967, Materials.SiliconTetrafluoride);
        r(968, Materials.SiliconTetrachloride);
        r(969, Materials.AluminiumFluoride);
        r(970, Materials.Void);
        r(971, Materials.CalciumDisilicide);
        r(972, Materials.Trichlorosilane);
        r(973, Materials.Hexachlorodisilane);
        r(974, Materials.SuperconductorUEVBase);
        r(975, Materials.Draconium);
        r(976, Materials.DraconiumAwakened);
        r(977, Materials.BloodInfusedIron);
        r(978, Materials.Ichorium);
        r(979, Materials.RadoxPolymer);
        r(980, Materials.GalliumArsenide);
        r(981, Materials.IndiumGalliumPhosphide);
        r(982, Materials.CosmicNeutronium);
        r(983, Materials.MTBEMixture);
        r(984, Materials.Flerovium);
        r(985, Materials.SuperconductorUHVBase);
        r(986, Materials.SuperconductorUVBase);
        r(987, Materials.SuperconductorMVBase);
        r(988, Materials.SuperconductorHVBase);
        r(989, Materials.SuperconductorEVBase);
        r(990, Materials.SuperconductorIVBase);
        r(991, Materials.SuperconductorLuVBase);
        r(992, Materials.SuperconductorZPMBase);
        r(993, Materials.NitrousOxide);
        r(994, Materials.AntiKnock);
        r(995, Materials.Octane);
        r(996, Materials.GasolineRaw);
        r(997, Materials.GasolineRegular);
        r(998, Materials.GasolinePremium);
        r(999, Materials.McGuffium239);
        // spotless:on
    }

    public void register() {
        forEach((ID, material) -> material.mMetaItemSubID = ID);
    }

    private void r(int ID, Materials material) {
        final Materials prevMaterial = put(ID, material);
        if (prevMaterial == null) return;
        GTMod.GT_FML_LOGGER.warn("Material '{}' with ID {} was replaced by '{}'.", prevMaterial, ID, material);
    }
}
