package gregtech.api.enums;

import static gregtech.GTMod.GT_FML_LOGGER;
import static gregtech.api.enums.Materials.Aluminium;
import static gregtech.api.enums.Materials.Aluminiumoxide;
import static gregtech.api.enums.Materials.Boron;
import static gregtech.api.enums.Materials.Calcium;
import static gregtech.api.enums.Materials.Hydrogen;
import static gregtech.api.enums.Materials.Iron;
import static gregtech.api.enums.Materials.Magnesium;
import static gregtech.api.enums.Materials.Oxygen;
import static gregtech.api.enums.Materials.Silicon;
import static gregtech.api.enums.Materials.SiliconDioxide;
import static gregtech.api.enums.Materials.Sodium;
import static gregtech.api.enums.Materials.Water;

import gregtech.api.interfaces.IMaterialHandler;
import gregtech.api.objects.MaterialStack;

public class MaterialsGTNH implements IMaterialHandler {

    public MaterialsGTNH() {
        GT_FML_LOGGER.info("Registering GTNH-Materials (post Java 64kb limit)");
        Materials.add(this);
    }

    /**
     * This Class is for adding new Materials since Java has a Limiation of 64kb per Method / Class header
     */
    public static Materials Signalum = new Materials(
        -1,
        TextureSet.SET_NONE,
        1.0F,
        0,
        2,
        1 | 2,
        255,
        255,
        255,
        0,
        "Signalum",
        "Signalum",
        0,
        0,
        -1,
        0,
        false,
        false,
        3,
        1,
        1,
        Dyes._NULL);

    public static Materials Lumium = new Materials(
        -1,
        TextureSet.SET_NONE,
        1.0F,
        0,
        2,
        1 | 2,
        255,
        255,
        255,
        0,
        "Lumium",
        "Lumium",
        0,
        0,
        -1,
        0,
        false,
        false,
        3,
        1,
        1,
        Dyes._NULL);
    public static Materials EnrichedCopper = new Materials(
        -1,
        TextureSet.SET_NONE,
        1.0F,
        0,
        2,
        1 | 2,
        255,
        255,
        255,
        0,
        "EnrichedCopper",
        "Enriched Copper",
        0,
        0,
        -1,
        0,
        false,
        false,
        3,
        1,
        1,
        Dyes._NULL);
    public static Materials DiamondCopper = new Materials(
        -1,
        TextureSet.SET_NONE,
        1.0F,
        0,
        2,
        1 | 2,
        255,
        255,
        255,
        0,
        "DiamondCopper",
        "Diamond Copper",
        0,
        0,
        -1,
        0,
        false,
        false,
        3,
        1,
        1,
        Dyes._NULL);
    public static Materials TarPitch = new Materials(
        -1,
        TextureSet.SET_NONE,
        1.0F,
        0,
        2,
        1 | 2,
        255,
        255,
        255,
        0,
        "TarPitch",
        "Tar Pitch",
        0,
        0,
        -1,
        0,
        false,
        false,
        3,
        1,
        1,
        Dyes._NULL);
    public static Materials LimePure = new Materials(
        -1,
        TextureSet.SET_NONE,
        1.0F,
        0,
        0,
        0,
        255,
        255,
        255,
        0,
        "LimePure",
        "Pure Lime",
        0,
        0,
        -1,
        0,
        false,
        false,
        1,
        1,
        1,
        Dyes.dyeLime);
    public static Materials Wimalite = new Materials(
        -1,
        TextureSet.SET_NONE,
        1.0F,
        0,
        2,
        8,
        255,
        255,
        255,
        0,
        "Wimalite",
        "Wimalite",
        0,
        0,
        -1,
        0,
        false,
        false,
        3,
        1,
        1,
        Dyes.dyeYellow);
    public static Materials Yellorite = new Materials(
        -1,
        TextureSet.SET_NONE,
        1.0F,
        0,
        2,
        8,
        255,
        255,
        255,
        0,
        "Yellorite",
        "Yellorite",
        0,
        0,
        -1,
        0,
        false,
        false,
        3,
        1,
        1,
        Dyes.dyeYellow);
    public static Materials Turquoise = new Materials(
        -1,
        TextureSet.SET_NONE,
        1.0F,
        0,
        1,
        1,
        255,
        255,
        255,
        0,
        "Turquoise",
        "Turquoise",
        0,
        0,
        -1,
        0,
        false,
        false,
        3,
        1,
        1,
        Dyes._NULL);
    public static Materials Tapazite = new Materials(
        -1,
        TextureSet.SET_NONE,
        1.0F,
        0,
        1,
        1,
        255,
        255,
        255,
        0,
        "Tapazite",
        "Tapazite",
        0,
        0,
        -1,
        0,
        false,
        false,
        3,
        1,
        1,
        Dyes.dyeGreen);
    public static Materials Thyrium = new Materials(
        -1,
        TextureSet.SET_NONE,
        1.0F,
        0,
        1,
        1 | 2 | 8,
        255,
        255,
        255,
        0,
        "Thyrium",
        "Thyrium",
        0,
        0,
        -1,
        0,
        false,
        false,
        3,
        1,
        1,
        Dyes._NULL);
    public static Materials Tourmaline = new Materials(
        -1,
        TextureSet.SET_RUBY,
        1.0F,
        0,
        1,
        1,
        255,
        255,
        255,
        0,
        "Tourmaline",
        "Tourmaline",
        0,
        0,
        -1,
        0,
        false,
        false,
        3,
        1,
        1,
        Dyes._NULL);
    public static Materials Spinel = new Materials(
        -1,
        TextureSet.SET_NONE,
        1.0F,
        0,
        1,
        0,
        255,
        255,
        255,
        0,
        "Spinel",
        "Spinel",
        0,
        0,
        -1,
        0,
        false,
        false,
        3,
        1,
        1,
        Dyes._NULL);
    public static Materials Starconium = new Materials(
        -1,
        TextureSet.SET_NONE,
        1.0F,
        0,
        1,
        1 | 2 | 8,
        255,
        255,
        255,
        0,
        "Starconium",
        "Starconium",
        0,
        0,
        -1,
        0,
        false,
        false,
        3,
        1,
        1,
        Dyes._NULL);
    public static Materials Sugilite = new Materials(
        -1,
        TextureSet.SET_NONE,
        1.0F,
        0,
        1,
        1,
        255,
        255,
        255,
        0,
        "Sugilite",
        "Sugilite",
        0,
        0,
        -1,
        0,
        false,
        false,
        3,
        1,
        1,
        Dyes._NULL);
    public static Materials Prismarine = new Materials(
        -1,
        TextureSet.SET_NONE,
        1.0F,
        0,
        2,
        1 | 4,
        255,
        255,
        255,
        0,
        "Prismarine",
        "Prismarine",
        0,
        0,
        -1,
        0,
        false,
        false,
        3,
        1,
        1,
        Dyes._NULL);
    public static Materials GraveyardDirt = new Materials(
        -1,
        TextureSet.SET_NONE,
        1.0F,
        0,
        2,
        1,
        255,
        255,
        255,
        0,
        "GraveyardDirt",
        "Graveyard Dirt",
        0,
        0,
        -1,
        0,
        false,
        false,
        3,
        1,
        1,
        Dyes._NULL);
    public static Materials Tennantite = new Materials(
        -1,
        TextureSet.SET_NONE,
        1.0F,
        0,
        2,
        1,
        255,
        255,
        255,
        0,
        "Tennantite",
        "Tennantite",
        0,
        0,
        -1,
        0,
        false,
        false,
        3,
        1,
        1,
        Dyes._NULL);
    public static Materials Fairy = new Materials(
        -1,
        TextureSet.SET_NONE,
        1.0F,
        0,
        2,
        1 | 2,
        255,
        255,
        255,
        0,
        "Fairy",
        "Fairy",
        0,
        0,
        -1,
        0,
        false,
        false,
        3,
        1,
        1,
        Dyes._NULL);
    public static Materials Ludicrite = new Materials(
        -1,
        TextureSet.SET_NONE,
        1.0F,
        0,
        2,
        1 | 2,
        255,
        255,
        255,
        0,
        "Ludicrite",
        "Ludicrite",
        0,
        0,
        -1,
        0,
        false,
        false,
        3,
        1,
        1,
        Dyes._NULL);
    public static Materials AquaRegia = new Materials(
        -1,
        TextureSet.SET_NONE,
        1.0F,
        0,
        2,
        0,
        255,
        255,
        255,
        0,
        "AquaRegia",
        "Aqua Regia",
        0,
        0,
        -1,
        0,
        false,
        false,
        3,
        1,
        1,
        Dyes._NULL);
    public static Materials SolutionBlueVitriol = new Materials(
        -1,
        TextureSet.SET_NONE,
        1.0F,
        0,
        2,
        0,
        255,
        255,
        255,
        0,
        "SolutionBlueVitriol",
        "Blue Vitriol Solution",
        0,
        0,
        -1,
        0,
        false,
        false,
        3,
        1,
        1,
        Dyes._NULL);
    public static Materials SolutionNickelSulfate = new Materials(
        -1,
        TextureSet.SET_NONE,
        1.0F,
        0,
        2,
        0,
        255,
        255,
        255,
        0,
        "SolutionNickelSulfate",
        "Nickel Sulfate Solution",
        0,
        0,
        -1,
        0,
        false,
        false,
        3,
        1,
        1,
        Dyes._NULL);
    public static Materials Lodestone = new Materials(
        -1,
        TextureSet.SET_NONE,
        1.0F,
        0,
        1,
        1 | 8,
        255,
        255,
        255,
        0,
        "Lodestone",
        "Lodestone",
        0,
        0,
        -1,
        0,
        false,
        false,
        1,
        1,
        1,
        Dyes._NULL);
    public static Materials Luminite = new Materials(
        -1,
        TextureSet.SET_NONE,
        1.0F,
        0,
        1,
        1 | 8,
        250,
        250,
        250,
        0,
        "Luminite",
        "Luminite",
        0,
        0,
        -1,
        0,
        false,
        false,
        3,
        1,
        1,
        Dyes.dyeWhite);

    // Deepslate stuff
    public static Materials Chlorite = new MaterialBuilder(167, TextureSet.SET_SHINY, "Chlorite").addDustItems()
        .setRGB(96, 125, 108)
        .setColor(Dyes.dyeLime)
        .setMaterialList(
            new MaterialStack(Iron, 3),
            new MaterialStack(Magnesium, 2),
            new MaterialStack(Aluminiumoxide, 1),
            new MaterialStack(SiliconDioxide, 3),
            new MaterialStack(Water, 4),
            new MaterialStack(Oxygen, 5))
        .constructMaterial();
    public static Materials Staurolite = new MaterialBuilder(168, TextureSet.SET_DULL, "Staurolite").addDustItems()
        .setRGB(63, 40, 22)
        .setColor(Dyes.dyeBrown)
        .setMaterialList(
            new MaterialStack(Iron, 2),
            new MaterialStack(Aluminium, 9),
            new MaterialStack(SiliconDioxide, 4),
            new MaterialStack(Oxygen, 16),
            new MaterialStack(Hydrogen, 1))
        .constructMaterial();
    public static Materials Cordierite = new MaterialBuilder(169, TextureSet.SET_SHINY, "Cordierite").addDustItems()
        .setRGB(67, 75, 130)
        .setColor(Dyes.dyePurple)
        .setMaterialList(
            new MaterialStack(Iron, 1),
            new MaterialStack(Magnesium, 1),
            new MaterialStack(SiliconDioxide, 5),
            new MaterialStack(Aluminiumoxide, 1),
            new MaterialStack(Oxygen, 5))
        .constructMaterial();
    public static Materials Datolite = new MaterialBuilder(170, TextureSet.SET_SHINY, "Datolite").addDustItems()
        .setRGB(234, 196, 206)
        .setColor(Dyes.dyeWhite)
        .setMaterialList(
            new MaterialStack(Calcium, 1),
            new MaterialStack(Boron, 1),
            new MaterialStack(SiliconDioxide, 1),
            new MaterialStack(Oxygen, 3),
            new MaterialStack(Hydrogen, 1))
        .constructMaterial();
    public static Materials MetamorphicMineralMixture = new MaterialBuilder(
        171,
        TextureSet.SET_DULL,
        "Metamorphic Mineral Mixture").addDustItems()
            .setRGB(108, 130, 148)
            .setColor(Dyes.dyeCyan)
            .constructMaterial();
    public static Materials Plagioclase = new MaterialBuilder(172, TextureSet.SET_SHINY, "Plagioclase").addDustItems()
        .setRGB(193, 186, 178)
        .setColor(Dyes.dyeWhite)
        .setMaterialList(
            new MaterialStack(Sodium, 1),
            new MaterialStack(Aluminium, 1),
            new MaterialStack(Silicon, 3),
            new MaterialStack(Oxygen, 8))
        .constructMaterial();
    public static Materials Epidote = new MaterialBuilder(862, TextureSet.SET_DULL, "Epidote").addDustItems()
        .setRGB(140, 177, 33)
        .setColor(Dyes.dyeLime)
        .setMaterialList(
            new MaterialStack(Calcium, 2),
            new MaterialStack(Aluminium, 3),
            new MaterialStack(SiliconDioxide, 3),
            new MaterialStack(Oxygen, 1),
            new MaterialStack(Hydrogen, 1))
        .constructMaterial();

    private static void initSubTags() {
        SubTag.METAL.addTo(Signalum, Lumium, EnrichedCopper, DiamondCopper);
        SubTag.NO_SMASHING.addTo(TarPitch);
    }

    @Override
    public void onMaterialsInit() {
        initSubTags();
    }
}
