package gregtech.api.enums;

import gregtech.api.objects.MaterialStack;

import java.util.Arrays;

public class MaterialsBotania {

    //public static Materials ManaSteel = new MaterialBuilder(796, TextureSet.SET_METALLIC, "Mana Steel").setName("ManaSteel").addDustItems().setRGB(150, 212, 246).setColor(Dyes.dyeLightBlue).setMeltingPoint(1500).setBlastFurnaceRequired(true).setMaterialList(new MaterialStack(Materials.Iron, 1), new MaterialStack(Materials.Magic, 1)).setAspects(Arrays.asList(new TC_Aspects.TC_AspectStack(TC_Aspects.METALLUM, 2), new TC_Aspects.TC_AspectStack(TC_Aspects.PRAECANTATIO, 4))).constructMaterial().disableAutoGeneratedBlastFurnaceRecipes();


    /**
     * called by Materials. Can be safely called multiple times. exists to allow Materials ensure this class is initialized
     */

    public static void init() {
        // no-op. all work is done by <clinit>
    }
}
