package gregtech.api.enums;

/**
 * Used for {@link gregtech.api.structure.error.StructureErrorRegistry}.
 */
public enum StructureErrorId {
    WRONG_BLOCK,
    BLOCK_NOT_LOADED,
    MISSING_MAINTENANCE,
    TOO_MANY_MAINTENANCE,
    MISSING_INPUT_BUS,
    MISSING_OUTPUT_BUS,
    MISSING_ENERGY_HATCH,
    MISSING_MUFFLER,
    UNNEEDED_MUFFLER,
    TOO_MANY_MUFFLER,
    TOO_FEW_CASINGS,
    MISSING_HATCH,
    TOO_MANY_HATCHES,
    MISSING_OUTPUT_HATCH_DT,
    SIMPLE_STRUCTURE_ERROR,
    UNKNOWN_STRUCTURE_ERROR,
    MISSING_STRUCTURE_WRAPPER_CASINGS;
}
