package gregtech.api.enums;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

import gregtech.api.interfaces.IIconContainer;

public class TextureSet {

    public boolean is_custom = false;

    public String aTextCustomAutogenerated = "autogenerated";

    public static final TextureSet SET_NONE = new TextureSet("NONE"), SET_DULL = new TextureSet("DULL"),
        SET_RUBY = new TextureSet("RUBY"), SET_OPAL = new TextureSet("OPAL"), SET_LEAF = new TextureSet("LEAF"),
        SET_WOOD = new TextureSet("WOOD"), SET_SAND = new TextureSet("SAND"), SET_FINE = new TextureSet("FINE"),
        SET_FIERY = new TextureSet("FIERY"), SET_FLUID = new TextureSet("FLUID"), SET_ROUGH = new TextureSet("ROUGH"),
        SET_PAPER = new TextureSet("PAPER"), SET_GLASS = new TextureSet("GLASS"), SET_FLINT = new TextureSet("FLINT"),
        SET_LAPIS = new TextureSet("LAPIS"), SET_SHINY = new TextureSet("SHINY"), SET_SHARDS = new TextureSet("SHARDS"),
        SET_POWDER = new TextureSet("POWDER"), SET_QUARTZ = new TextureSet("QUARTZ"),
        SET_EMERALD = new TextureSet("EMERALD"), SET_DIAMOND = new TextureSet("DIAMOND"),
        SET_LIGNITE = new TextureSet("LIGNITE"), SET_MAGNETIC = new TextureSet("MAGNETIC"),
        SET_METALLIC = new TextureSet("METALLIC"), SET_NETHERSTAR = new TextureSet("NETHERSTAR"),
        SET_GEM_VERTICAL = new TextureSet("GEM_VERTICAL"), SET_GEM_HORIZONTAL = new TextureSet("GEM_HORIZONTAL"),
        SET_REFINED = new TextureSet("REFINED"), SET_GEM_A = new TextureSet("GEM_A"),
        SET_NUCLEAR = new TextureSet("NUCLEAR");

    /**
     * Custom Texture Sets for more clean code
     */
    public static final TextureSet SET_DARKSTEEL = new TextureSet("darksteel", true),
        SET_ENERGETIC = new TextureSet("energetic", true), SET_VIBRANT = new TextureSet("vibrant", true),
        SET_CRYSTALLINE = new TextureSet("crystalline", true), SET_MELODIC = new TextureSet("melodic", true),
        SET_STELLAR = new TextureSet("stellar", true), SET_VIVID = new TextureSet("vivid", true),
        SET_CRUDE_STEEL = new TextureSet("crudesteel", false),
        SET_CRYSTALLINE_PINK_SLIME = new TextureSet("crystallinepinkslime", true),
        SET_ENERGETIC_SILVER = new TextureSet("energeticsilver", false),
        SET_END_STEEL = new TextureSet("endsteel", false), SET_DRACONIUM = new TextureSet("draconium", false),
        SET_AWOKEN_DRACONIUM = new TextureSet("awakeneddraconium", false),
        SET_ELECTROTINE = new TextureSet("electrotine", false), SET_REDSTONE = new TextureSet("redstone", false),
        SET_GLOWSTONE = new TextureSet("glowstone", false), SET_PYROTHEUM = new TextureSet("pyrotheum", false),
        SET_CRYOTHEUM = new TextureSet("cryotheum", false), SET_BLAZE = new TextureSet("blaze", false),
        SET_BLIZZ = new TextureSet("blizz", false), SET_MANASTEEL = new TextureSet("Manasteel", false),
        SET_LIVINGROCK = new TextureSet("Livingrock", true), SET_GAIA_SPIRIT = new TextureSet("GaiaSpirit", true),
        SET_LIVINGWOOD = new TextureSet("Livingwood", true), SET_DREAMWOOD = new TextureSet("Dreamwood", true),
        SET_MANA_DIAMOND = new TextureSet("ManaDiamond", true), SET_DRAGONSTONE = new TextureSet("Dragonstone", true),
        SET_INFINITY = new TextureSet("infinity", true), SET_BEDROCKIUM = new TextureSet("bedrockium", true),
        SET_ICHORIUM = new TextureSet("ichorium", true),
        SET_COSMIC_NEUTRONIUM = new TextureSet("cosmicneutronium", true),
        SET_SBM = new TextureSet("stablebaryonicmatter", true), SET_NETHERITE = new TextureSet("netherite", true),
        SET_PRISMATIC_ACID = new TextureSet("prismaticacid", true), SET_SPACETIME = new TextureSet("spacetime", true),
        SET_MHDCSM = new TextureSet("MagnetohydrodynamicallyConstrainedStarMatter", true),
        SET_WHITE_DWARF_MATTER = new TextureSet("WhiteDwarfMatter", true),
        SET_UNIVERSIUM = new TextureSet("universium", true), SET_ETERNITY = new TextureSet("eternity", true),
        SET_MAGMATTER = new TextureSet("magmatter", true), SET_GRAVITON_SHARD = new TextureSet("GravitonShard", true),
        SET_DIMENSIONALLY_SHIFTED_SUPER_FLUID = new TextureSet("dimensionallyshiftedsuperfluid", true),
        SET_PROTOHALKONITE_BASE = new TextureSet("protohalkonitebase", true),
        SET_HOT_PROTOHALKONITE = new TextureSet("hotprotohalkonite", true),
        SET_PROTOHALKONITE = new TextureSet("protohalkonite", true),
        SET_HOT_EXOHALKONITE = new TextureSet("hotexohalkonite", true),
        SET_EXOHALKONITE = new TextureSet("exohalkonite", true),
        SET_SG_CRYSTAL_SLURRY = new TextureSet("sgcrystalfluid", true), SET_RHUGNOR = new TextureSet("rhugnor", true),
        SET_HYPOGEN = new TextureSet("hypogen", false), SET_FLUXED = new TextureSet("fluxed", true),
        SET_CHROMATIC_GLASS = new TextureSet("chromaticglass", true),
        SET_ASTRAL_TITANIUM = new TextureSet("astraltitanium", true),
        SET_CELESTIAL_TUNGSTEN = new TextureSet("celestialtungsten", true);

    public final IIconContainer[] mTextures = new IIconContainer[MaterialIconRegistry.IconType.values().length];
    public final String mSetName;

    public TextureSet(String aSetName) {
        mSetName = aSetName;
        for (MaterialIconRegistry.IconType type : MaterialIconRegistry.IconType.values()) {
            int index = type.ordinal();
            String suffix = type.suffix;

            if (type.texture == MaterialIconRegistry.TextureType.BLOCK) {
                mTextures[index] = Textures.BlockIcons.textureSet(aSetName, suffix);
            } else if (type.texture == MaterialIconRegistry.TextureType.BLOCK_WITH_ALPHA) {
                mTextures[index] = Textures.BlockIcons
                    .customAlpha(Textures.TextureMaterialIconDirectory + aSetName + suffix);
            } else {
                mTextures[index] = Textures.ItemIcons.textureSet(aSetName, suffix);
            }
        }
    }

    public TextureSet(String aSetName, boolean isCustom) {
        this("CUSTOM/" + aSetName);
        this.is_custom = isCustom;
        this.aTextCustomAutogenerated = aSetName;
    }

    /**
     * Construct a TextureSet that will delegate some of its textures to the origin TextureSet.
     * <p>
     * This assumes you want to construct a custom texture set.
     */
    private TextureSet(String newSetName, TextureSet origin, Set<MaterialIconRegistry.IconType> overrides) {
        this.mSetName = "CUSTOM/" + newSetName;
        this.is_custom = true;

        for (MaterialIconRegistry.IconType type : MaterialIconRegistry.IconType.values()) {
            int index = type.ordinal();

            if (overrides.contains(type)) {
                System.out.println("Overriding " + type + " with " + mSetName + type.suffix);

                // Override this specific icon
                switch (type.texture) {
                    case BLOCK:
                        mTextures[index] = Textures.BlockIcons.textureSet(mSetName, type.suffix);
                        break;

                    case BLOCK_WITH_ALPHA:
                        mTextures[index] = Textures.BlockIcons
                            .customAlpha(Textures.TextureMaterialIconDirectory + mSetName + type.suffix);
                        break;

                    case ITEM:
                    default:
                        mTextures[index] = Textures.ItemIcons.textureSet(mSetName, type.suffix);
                        break;
                }
            } else {
                // Use origin texture
                mTextures[index] = origin.mTextures[index];
            }
        }
    }

    /**
     * Creates a new TextureSet that overrides only the specific material icons provided.
     *
     * <p>
     * This method is the flexible, per-icon replacement for the old boolean-based
     * block/item override system. Instead of overriding all block or all item textures,
     * you explicitly list the MaterialIconRegistry.IconType entries you want to replace.
     *
     * <p>
     * <strong>Example icon set for Materials.Copper:</strong>
     *
     * <pre>
     *     .setIconSet(
     *         TextureSet.SET_DULL.withCustomTextures(
     *             "copper",
     *             MaterialIconRegistry.IconType.ORE_RAW,
     *             MaterialIconRegistry.IconType.ORE,
     *             MaterialIconRegistry.IconType.ORE_SMALL))
     * </pre>
     *
     * In this example, only the raw ore, ore, and small ore icons are replaced with
     * textures from {@code CUSTOM/copper/}, while all other icons (dust, ingot, plate,
     * etc.) remain unchanged.
     *
     * @param newSetName the name of the custom texture folder under CUSTOM/
     * @param types      the specific icon types to override with custom textures
     * @return a new TextureSet with the requested icons overridden
     */
    public TextureSet withCustomTextures(String newSetName, MaterialIconRegistry.IconType... types) {
        Set<MaterialIconRegistry.IconType> overrideSet = new HashSet<>(Arrays.asList(types));
        return new TextureSet(newSetName, this, overrideSet);
    }
}
