package gregtech.loaders.postload;

import bloodasp.galacticgreg.WorldGenGaGT;
import gregtech.api.GregTech_API;
import gregtech.api.enums.Materials;
import gregtech.api.enums.OreMixes;
import gregtech.api.util.GT_Log;
import gregtech.common.GT_Worldgen_GT_Ore_SmallPieces;
import gregtech.common.GT_Worldgen_Stone;
import gregtech.common.GT_Worldgenerator;

public class GT_Worldgenloader implements Runnable {

    public void run() {

        new GT_Worldgenerator();

        new GT_Worldgen_Stone(
            "overworld.stone.blackgranite.tiny",
            true,
            GregTech_API.sBlockGranites,
            0,
            0,
            1,
            75,
            5,
            0,
            180,
            null,
            false);
        new GT_Worldgen_Stone(
            "overworld.stone.blackgranite.small",
            true,
            GregTech_API.sBlockGranites,
            0,
            0,
            1,
            100,
            10,
            0,
            180,
            null,
            false);
        new GT_Worldgen_Stone(
            "overworld.stone.blackgranite.medium",
            true,
            GregTech_API.sBlockGranites,
            0,
            0,
            1,
            200,
            10,
            0,
            180,
            null,
            false);
        new GT_Worldgen_Stone(
            "overworld.stone.blackgranite.large",
            true,
            GregTech_API.sBlockGranites,
            0,
            0,
            1,
            300,
            70,
            0,
            120,
            null,
            false);
        new GT_Worldgen_Stone(
            "overworld.stone.blackgranite.huge",
            true,
            GregTech_API.sBlockGranites,
            0,
            0,
            1,
            400,
            150,
            0,
            120,
            null,
            false);

        new GT_Worldgen_Stone(
            "overworld.stone.redgranite.tiny",
            true,
            GregTech_API.sBlockGranites,
            8,
            0,
            1,
            75,
            5,
            0,
            180,
            null,
            false);
        new GT_Worldgen_Stone(
            "overworld.stone.redgranite.small",
            true,
            GregTech_API.sBlockGranites,
            8,
            0,
            1,
            100,
            10,
            0,
            180,
            null,
            false);
        new GT_Worldgen_Stone(
            "overworld.stone.redgranite.medium",
            true,
            GregTech_API.sBlockGranites,
            8,
            0,
            1,
            200,
            10,
            0,
            180,
            null,
            false);
        new GT_Worldgen_Stone(
            "overworld.stone.redgranite.large",
            true,
            GregTech_API.sBlockGranites,
            8,
            0,
            1,
            300,
            70,
            0,
            120,
            null,
            false);
        new GT_Worldgen_Stone(
            "overworld.stone.redgranite.huge",
            true,
            GregTech_API.sBlockGranites,
            8,
            0,
            1,
            400,
            150,
            0,
            120,
            null,
            false);

        new GT_Worldgen_Stone(
            "overworld.stone.marble.tiny",
            true,
            GregTech_API.sBlockStones,
            0,
            0,
            1,
            75,
            5,
            0,
            180,
            null,
            false);
        new GT_Worldgen_Stone(
            "overworld.stone.marble.small",
            true,
            GregTech_API.sBlockStones,
            0,
            0,
            1,
            100,
            10,
            0,
            180,
            null,
            false);
        new GT_Worldgen_Stone(
            "overworld.stone.marble.medium",
            true,
            GregTech_API.sBlockStones,
            0,
            0,
            1,
            200,
            10,
            0,
            180,
            null,
            false);
        new GT_Worldgen_Stone(
            "overworld.stone.marble.large",
            true,
            GregTech_API.sBlockStones,
            0,
            0,
            1,
            300,
            70,
            0,
            120,
            null,
            false);
        new GT_Worldgen_Stone(
            "overworld.stone.marble.huge",
            true,
            GregTech_API.sBlockStones,
            0,
            0,
            1,
            400,
            150,
            0,
            120,
            null,
            false);

        new GT_Worldgen_Stone(
            "overworld.stone.basalt.tiny",
            true,
            GregTech_API.sBlockStones,
            8,
            0,
            1,
            75,
            5,
            0,
            180,
            null,
            false);
        new GT_Worldgen_Stone(
            "overworld.stone.basalt.small",
            true,
            GregTech_API.sBlockStones,
            8,
            0,
            1,
            100,
            10,
            0,
            180,
            null,
            false);
        new GT_Worldgen_Stone(
            "overworld.stone.basalt.medium",
            true,
            GregTech_API.sBlockStones,
            8,
            0,
            1,
            200,
            10,
            0,
            180,
            null,
            false);
        new GT_Worldgen_Stone(
            "overworld.stone.basalt.large",
            true,
            GregTech_API.sBlockStones,
            8,
            0,
            1,
            300,
            70,
            0,
            120,
            null,
            false);
        new GT_Worldgen_Stone(
            "overworld.stone.basalt.huge",
            true,
            GregTech_API.sBlockStones,
            8,
            0,
            1,
            400,
            150,
            0,
            120,
            null,
            false);

        new GT_Worldgen_Stone(
            "nether.stone.blackgranite.tiny",
            false,
            GregTech_API.sBlockGranites,
            0,
            -1,
            1,
            50,
            45,
            0,
            120,
            null,
            false);
        new GT_Worldgen_Stone(
            "nether.stone.blackgranite.small",
            false,
            GregTech_API.sBlockGranites,
            0,
            -1,
            1,
            100,
            60,
            0,
            120,
            null,
            false);
        new GT_Worldgen_Stone(
            "nether.stone.blackgranite.medium",
            false,
            GregTech_API.sBlockGranites,
            0,
            -1,
            1,
            200,
            80,
            0,
            120,
            null,
            false);
        new GT_Worldgen_Stone(
            "nether.stone.blackgranite.large",
            false,
            GregTech_API.sBlockGranites,
            0,
            -1,
            1,
            300,
            70,
            0,
            120,
            null,
            false);
        new GT_Worldgen_Stone(
            "nether.stone.blackgranite.huge",
            false,
            GregTech_API.sBlockGranites,
            0,
            -1,
            1,
            400,
            150,
            0,
            120,
            null,
            false);

        new GT_Worldgen_Stone(
            "nether.stone.redgranite.tiny",
            false,
            GregTech_API.sBlockGranites,
            8,
            -1,
            1,
            50,
            45,
            0,
            120,
            null,
            false);
        new GT_Worldgen_Stone(
            "nether.stone.redgranite.small",
            false,
            GregTech_API.sBlockGranites,
            8,
            -1,
            1,
            100,
            60,
            0,
            120,
            null,
            false);
        new GT_Worldgen_Stone(
            "nether.stone.redgranite.medium",
            false,
            GregTech_API.sBlockGranites,
            8,
            -1,
            1,
            200,
            80,
            0,
            120,
            null,
            false);
        new GT_Worldgen_Stone(
            "nether.stone.redgranite.large",
            false,
            GregTech_API.sBlockGranites,
            8,
            -1,
            1,
            300,
            70,
            0,
            120,
            null,
            false);
        new GT_Worldgen_Stone(
            "nether.stone.redgranite.huge",
            false,
            GregTech_API.sBlockGranites,
            8,
            -1,
            1,
            400,
            150,
            0,
            120,
            null,
            false);

        new GT_Worldgen_Stone(
            "nether.stone.marble.tiny",
            false,
            GregTech_API.sBlockStones,
            0,
            -1,
            1,
            50,
            45,
            0,
            120,
            null,
            false);
        new GT_Worldgen_Stone(
            "nether.stone.marble.small",
            false,
            GregTech_API.sBlockStones,
            0,
            -1,
            1,
            100,
            60,
            0,
            120,
            null,
            false);
        new GT_Worldgen_Stone(
            "nether.stone.marble.medium",
            false,
            GregTech_API.sBlockStones,
            0,
            -1,
            1,
            200,
            80,
            0,
            120,
            null,
            false);
        new GT_Worldgen_Stone(
            "nether.stone.marble.large",
            false,
            GregTech_API.sBlockStones,
            0,
            -1,
            1,
            300,
            70,
            0,
            120,
            null,
            false);
        new GT_Worldgen_Stone(
            "nether.stone.marble.huge",
            false,
            GregTech_API.sBlockStones,
            0,
            -1,
            1,
            400,
            150,
            0,
            120,
            null,
            false);

        new GT_Worldgen_Stone(
            "nether.stone.basalt.tiny",
            false,
            GregTech_API.sBlockStones,
            8,
            -1,
            1,
            50,
            45,
            0,
            120,
            null,
            false);
        new GT_Worldgen_Stone(
            "nether.stone.basalt.small",
            false,
            GregTech_API.sBlockStones,
            8,
            -1,
            1,
            100,
            60,
            0,
            120,
            null,
            false);
        new GT_Worldgen_Stone(
            "nether.stone.basalt.medium",
            false,
            GregTech_API.sBlockStones,
            8,
            -1,
            1,
            200,
            80,
            0,
            120,
            null,
            false);
        new GT_Worldgen_Stone(
            "nether.stone.basalt.large",
            false,
            GregTech_API.sBlockStones,
            8,
            -1,
            1,
            300,
            70,
            0,
            120,
            null,
            false);
        new GT_Worldgen_Stone(
            "nether.stone.basalt.huge",
            false,
            GregTech_API.sBlockStones,
            8,
            -1,
            1,
            400,
            150,
            0,
            120,
            null,
            false);

        // GT Default Small Ores
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.copper",
            true,
            60,
            180,
            32,
            true,
            true,
            true,
            true,
            true,
            false,
            Materials.Copper);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.tin",
            true,
            80,
            220,
            32,
            true,
            true,
            true,
            true,
            true,
            true,
            Materials.Tin);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.bismuth",
            true,
            80,
            120,
            8,
            false,
            true,
            false,
            true,
            true,
            false,
            Materials.Bismuth);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.coal",
            true,
            120,
            250,
            24,
            true,
            false,
            false,
            false,
            false,
            false,
            Materials.Coal);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.iron",
            true,
            40,
            100,
            16,
            true,
            true,
            true,
            true,
            true,
            false,
            Materials.Iron);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.lead",
            true,
            40,
            180,
            16,
            false,
            true,
            true,
            true,
            true,
            true,
            Materials.Lead);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.zinc",
            true,
            80,
            210,
            24,
            true,
            true,
            true,
            true,
            true,
            false,
            Materials.Zinc);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.gold",
            true,
            20,
            60,
            8,
            true,
            false,
            true,
            true,
            true,
            true,
            Materials.Gold);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.silver",
            true,
            20,
            60,
            20,
            true,
            true,
            true,
            true,
            true,
            true,
            Materials.Silver);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.nickel",
            true,
            80,
            150,
            8,
            true,
            false,
            true,
            true,
            true,
            true,
            Materials.Nickel);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.lapis",
            true,
            10,
            50,
            4,
            true,
            false,
            false,
            true,
            false,
            true,
            Materials.Lapis);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.diamond",
            true,
            5,
            15,
            2,
            true,
            false,
            false,
            true,
            true,
            true,
            Materials.Diamond);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.emerald",
            true,
            5,
            35,
            2,
            false,
            false,
            false,
            false,
            true,
            true,
            Materials.Emerald);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.ruby",
            true,
            5,
            35,
            2,
            false,
            false,
            false,
            false,
            true,
            true,
            Materials.Ruby);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.sapphire",
            true,
            5,
            35,
            2,
            false,
            false,
            false,
            false,
            true,
            true,
            Materials.Sapphire);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.greensapphire",
            true,
            5,
            35,
            2,
            false,
            false,
            false,
            false,
            true,
            true,
            Materials.GreenSapphire);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.olivine",
            true,
            5,
            35,
            2,
            false,
            false,
            false,
            false,
            true,
            true,
            Materials.Olivine);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.topaz",
            true,
            5,
            35,
            2,
            false,
            false,
            false,
            false,
            true,
            true,
            Materials.Topaz);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.tanzanite",
            true,
            5,
            35,
            2,
            false,
            false,
            false,
            false,
            true,
            true,
            Materials.Tanzanite);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.amethyst",
            true,
            5,
            35,
            2,
            false,
            false,
            false,
            false,
            true,
            true,
            Materials.Amethyst);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.opal",
            true,
            5,
            35,
            2,
            false,
            false,
            false,
            false,
            true,
            true,
            Materials.Opal);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.jasper",
            true,
            5,
            35,
            2,
            false,
            false,
            false,
            false,
            true,
            true,
            Materials.Jasper);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.bluetopaz",
            true,
            5,
            35,
            2,
            false,
            false,
            false,
            false,
            true,
            true,
            Materials.BlueTopaz);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.amber",
            true,
            5,
            35,
            2,
            false,
            false,
            false,
            false,
            true,
            true,
            Materials.Amber);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.foolsruby",
            true,
            5,
            35,
            2,
            false,
            false,
            false,
            false,
            true,
            true,
            Materials.FoolsRuby);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.garnetred",
            true,
            5,
            35,
            2,
            false,
            false,
            false,
            false,
            true,
            true,
            Materials.GarnetRed);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.garnetyellow",
            true,
            5,
            35,
            2,
            false,
            false,
            false,
            false,
            true,
            true,
            Materials.GarnetYellow);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.redstone",
            true,
            5,
            25,
            8,
            true,
            true,
            false,
            true,
            true,
            true,
            Materials.Redstone);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.netherquartz",
            true,
            30,
            120,
            64,
            false,
            true,
            false,
            false,
            false,
            false,
            Materials.NetherQuartz);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.saltpeter",
            true,
            10,
            60,
            8,
            false,
            true,
            false,
            false,
            false,
            false,
            Materials.Saltpeter);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.sulfur",
            true,
            5,
            60,
            40,
            false,
            true,
            false,
            false,
            false,
            false,
            Materials.Sulfur);

        // TODO: GTNH Custom Small Ores
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.titanium",
            true,
            10,
            180,
            32,
            false,
            false,
            false,
            Materials.Titanium);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.tungsten",
            true,
            10,
            120,
            16,
            false,
            false,
            false,
            Materials.Tungsten);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.meteoriciron",
            true,
            50,
            70,
            8,
            false,
            false,
            false,
            Materials.MeteoricIron);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.firestone",
            true,
            5,
            15,
            2,
            false,
            false,
            false,
            Materials.Firestone);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.neutronium",
            true,
            5,
            15,
            8,
            false,
            false,
            false,
            Materials.Neutronium);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.chromite",
            true,
            20,
            40,
            8,
            false,
            false,
            false,
            Materials.Chromite);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.tungstate",
            true,
            20,
            40,
            8,
            false,
            false,
            false,
            Materials.Tungstate);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.naquadah",
            true,
            5,
            25,
            8,
            false,
            false,
            false,
            Materials.Naquadah);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.quantium",
            true,
            5,
            25,
            6,
            false,
            false,
            false,
            Materials.Quantium);
        new GT_Worldgen_GT_Ore_SmallPieces("ore.small.mythril", true, 5, 25, 6, false, false, false, Materials.Mytryl);
        new GT_Worldgen_GT_Ore_SmallPieces("ore.small.ledox", true, 40, 60, 4, false, false, false, Materials.Ledox);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.oriharukon",
            true,
            20,
            40,
            6,
            false,
            false,
            false,
            Materials.Oriharukon);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.draconium",
            true,
            5,
            15,
            4,
            false,
            false,
            false,
            Materials.Draconium);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.awdraconium",
            true,
            5,
            15,
            2,
            false,
            false,
            false,
            Materials.DraconiumAwakened);
        new GT_Worldgen_GT_Ore_SmallPieces("ore.small.desh", true, 10, 30, 6, false, false, false, Materials.Desh);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.blackplutonium",
            true,
            25,
            45,
            6,
            false,
            false,
            false,
            Materials.BlackPlutonium);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.infinitycatalyst",
            true,
            40,
            80,
            6,
            false,
            false,
            false,
            Materials.InfinityCatalyst);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.infinity",
            true,
            2,
            40,
            2,
            false,
            false,
            false,
            Materials.Infinity);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.bedrockium",
            true,
            5,
            25,
            6,
            false,
            false,
            false,
            Materials.Bedrockium);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.realgar",
            true,
            15,
            85,
            32,
            false,
            true,
            false,
            Materials.Realgar);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.certusquartz",
            true,
            5,
            115,
            16,
            false,
            true,
            false,
            Materials.CertusQuartz);
        new GT_Worldgen_GT_Ore_SmallPieces("ore.small.jade", true, 5, 35, 2, false, false, false, Materials.Jade);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.deepiron",
            true,
            5,
            40,
            8,
            false,
            false,
            false,
            Materials.DeepIron);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.redgarnet",
            true,
            5,
            35,
            2,
            false,
            false,
            false,
            Materials.GarnetRed);
        new GT_Worldgen_GT_Ore_SmallPieces(
            "ore.small.chargedcertus",
            true,
            5,
            115,
            4,
            false,
            false,
            false,
            Materials.CertusQuartzCharged);

        // GT Veins registration
        for (OreMixes oreMix : OreMixes.values()){
            oreMix.addGTOreLayer();
        }


        new WorldGenGaGT().run();
        GT_Log.out.println("Started Galactic Greg ore gen code");
    }
}
