// Generated by scripts/mu/gen_gtpp_ore_transformers.py; edit the script, not this file.
package gregtech.loaders.postload;

/// The stage-11 commit-4 gtPlusPlus ore-cutover Postea migration table: one row per legacy
/// `BlockBaseOre` instance, read from the supplementary `gtpp-ores.json` dump (see
/// `MaterialDataDump#dumpGtppOres`, not itself pinned like `gtpp-materials.json`). [PosteaTransformers]
/// migrates each row's legacy placed block/item stack to `MU.stack(OrePrefixes.ore,
/// MaterialReconstruction.materialLibOf(unlocalizedName), 1)` -- see
/// `scripts/mu/gen_gtpp_ore_transformers.py`. A material that never gained
/// `Materials2OreShapes#ore` membership resolves null and is left on its legacy slot.
public final class GtppOreCutoverTable {

    public record Entry(String unlocalizedName, String registryName) {}

    private GtppOreCutoverTable() {}

    // spotless:off
    public static final Entry[] ENTRIES = new Entry[] {
        new Entry("AgarditeCd", "miscutils:oreAgarditeCd"),
        new Entry("AgarditeLa", "miscutils:oreAgarditeLa"),
        new Entry("AgarditeNd", "miscutils:oreAgarditeNd"),
        new Entry("AgarditeY", "miscutils:oreAgarditeY"),
        new Entry("Alburnite", "miscutils:oreAlburnite"),
        new Entry("AncientGranite", "miscutils:oreAncientGranite"),
        new Entry("BariteRa", "miscutils:oreBariteRa"),
        new Entry("Cerite", "miscutils:oreCerite"),
        new Entry("Comancheite", "miscutils:oreComancheite"),
        new Entry("Crocoite", "miscutils:oreCrocoite"),
        new Entry("CryoliteF", "miscutils:oreCryoliteF"),
        new Entry("DemicheleiteBr", "miscutils:oreDemicheleiteBr"),
        new Entry("Florencite", "miscutils:oreFlorencite"),
        new Entry("Fluorcaphite", "miscutils:oreFluorcaphite"),
        new Entry("FluoriteF", "miscutils:oreFluoriteF"),
        new Entry("GadoliniteCe", "miscutils:oreGadoliniteCe"),
        new Entry("GadoliniteY", "miscutils:oreGadoliniteY"),
        new Entry("Geikielite", "miscutils:oreGeikielite"),
        new Entry("Greenockite", "miscutils:oreGreenockite"),
        new Entry("Hibonite", "miscutils:oreHibonite"),
        new Entry("Honeaite", "miscutils:oreHoneaite"),
        new Entry("Irarsite", "miscutils:oreIrarsite"),
        new Entry("Kashinite", "miscutils:oreKashinite"),
        new Entry("Koboldite", "miscutils:oreKoboldite"),
        new Entry("Lafossaite", "miscutils:oreLafossaite"),
        new Entry("LanthaniteCe", "miscutils:oreLanthaniteCe"),
        new Entry("LanthaniteLa", "miscutils:oreLanthaniteLa"),
        new Entry("LanthaniteNd", "miscutils:oreLanthaniteNd"),
        new Entry("Lautarite", "miscutils:oreLautarite"),
        new Entry("Lepersonnite", "miscutils:oreLepersonnite"),
        new Entry("Miessiite", "miscutils:oreMiessiite"),
        new Entry("Nichromite", "miscutils:oreNichromite"),
        new Entry("Perroudite", "miscutils:orePerroudite"),
        new Entry("Polycrase", "miscutils:orePolycrase"),
        new Entry("RadioactiveMineralMix", "miscutils:oreRadioactiveMineralMix"),
        new Entry("RareEarthI", "miscutils:oreRareEarthI"),
        new Entry("RareEarthII", "miscutils:oreRareEarthII"),
        new Entry("RareEarthIII", "miscutils:oreRareEarthIII"),
        new Entry("Runite", "miscutils:oreRunite"),
        new Entry("SamarskiteY", "miscutils:oreSamarskiteY"),
        new Entry("SamarskiteYb", "miscutils:oreSamarskiteYb"),
        new Entry("Titanite", "miscutils:oreTitanite"),
        new Entry("Xenotime", "miscutils:oreXenotime"),
        new Entry("Yttriaite", "miscutils:oreYttriaite"),
        new Entry("Yttrialite", "miscutils:oreYttrialite"),
        new Entry("Yttrocerite", "miscutils:oreYttrocerite"),
        new Entry("Zimbabweite", "miscutils:oreZimbabweite"),
        new Entry("Zircon", "miscutils:oreZircon"),
        new Entry("Zirconolite", "miscutils:oreZirconolite"),
        new Entry("Zircophyllite", "miscutils:oreZircophyllite"),
        new Entry("Zirkelite", "miscutils:oreZirkelite"),
    };
    // spotless:on
}
