package gregtech.api.material;

/// Boolean material flags, mirroring the names of `gregtech.api.enums.SubTag` in the legacy material system.
///
/// Names are kept identical to their `SubTag` counterparts so the two systems map 1:1 by name,
/// except [#ANAEROBE_GAS] and [#NOBLE_GAS] which mirror bartworks' `WerkstoffLoader.ANAEROBE_GAS` /
/// `WerkstoffLoader.NOBLE_GAS` dynamic `SubTag`s (`"AnaerobeGas"` / `"NobleGas"`) using this enum's own naming
/// convention instead of their `SubTag#mName` strings.
public enum GTMaterialFlag {
    ANAEROBE_GAS,
    NOBLE_GAS,
    BLASTFURNACE_CALCITE_DOUBLE,
    BLASTFURNACE_CALCITE_TRIPLE,
    DONT_ADD_DEFAULT_BBF_RECIPE,
    INDUCTIONSMELTING_LOW_OUTPUT,
    WASHING_SODIUMPERSULFATE,
    WASHING_MERCURY,
    WASHING_MERCURY_99_PERCENT,
    ELECTROMAGNETIC_SEPERATION_GOLD,
    ELECTROMAGNETIC_SEPERATION_IRON,
    ELECTROMAGNETIC_SEPERATION_NEODYMIUM,
    PULVERIZING_CINNABAR,
    NO_WORKING,
    NO_SMASHING,
    NO_RECIPES,
    NO_UNIFICATION,
    NO_RECYCLING,
    NO_RECYCLING_RECIPES,
    NO_SMELTING,
    NO_ORE_PROCESSING,
    SMELTING_TO_FLUID,
    SMELTING_TO_GEM,
    WOOD,
    FOOD,
    STONE,
    PEARL,
    QUARTZ,
    CRYSTALLISABLE,
    CRYSTAL,
    MAGICAL,
    METAL,
    PAPER,
    BURNING,
    FLAMMABLE,
    UNBURNABLE,
    EXPLOSIVE,
    BOUNCY,
    INVISIBLE,
    TRANSPARENT,
    HAS_COLOR,
    STRETCHY,
    SOFT,
    MORTAR_GRINDABLE,
    SOLDERING_MATERIAL,
    SOLDERING_MATERIAL_BAD,
    SOLDERING_MATERIAL_GOOD,
    ENERGY_ELECTRICITY,
    ENERGY_ROTATIONAL,
    ENERGY_STEAM,
    ENERGY_AIR,
    ENERGY_HEAT,
    ENERGY_REDSTONE_FLUX,
    PROJECTILE_ARROW,
    BLACK_HOLE,
    ICE_ORE,
    MULTI_PLATE,
    TRANSMUTABLE_NUGGETS
}
