#!/usr/bin/env python3
"""Generates the stage-03 MaterialLib material declarations from the `gt-materials.json` and
`oreprefixes.json` material-unification dumps.

Run from anywhere; paths are resolved relative to this script's location. Requires only the Python 3
standard library.

Usage: python scripts/mu/gen_materials.py
"""

import json
import re
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
MATERIALS_DUMP_PATH = SCRIPT_DIR / "dumps" / "gt-materials.json"
PREFIXES_DUMP_PATH = SCRIPT_DIR / "dumps" / "oreprefixes.json"

MATERIALS2_DIR = REPO_ROOT / "src/main/java/gregtech/api/enums/materials2"
MATERIALS_OUTPUT = MATERIALS2_DIR / "Materials2Materials.java"
LANG_OUTPUT = REPO_ROOT / "src/main/resources/assets/gregtech/lang/en_US.lang"

LEGACY_MATERIALS_INIT = REPO_ROOT / "src/main/java/gregtech/loaders/materials/MaterialsInit.java"
LEGACY_BRIDGE_OUTPUT = REPO_ROOT / "src/main/java/gregtech/loaders/materials/MaterialsLegacyBridge.java"

GENERATED_HEADER = "// Generated by scripts/mu/gen_materials.py; edit the script, not this file."

# Kept low enough that a data file's init() method, one builder chain per material, stays comfortably under
# the JVM's 64k-bytecode-per-method limit even for materials with large composition/aspect lists.
MATERIALS_PER_FILE = 120

# Mirrors gregtech.api.enums.OrePrefixes generation-bit constants; see scripts/mu/gen_shapes.py.
DUST = 1
METAL = 2
GEM = 4
ORE = 8
CELL = 16
PLASMA = 32
TOOL = 64
GEAR = 128
EMPTY = 256

FAMILY_BITS = [
    ("familyDusts", DUST),
    ("familyMetals", METAL),
    ("familyGems", GEM),
    ("familyOres", ORE),
    ("familyCells", CELL),
    ("familyPlasmas", PLASMA),
    ("familyToolParts", TOOL),
    ("familyGears", GEAR),
    ("familyEmpties", EMPTY),
]

REF_PROPERTY_FIELDS = [
    ("smeltInto", "SMELT_INTO"),
    ("macerateInto", "MACERATE_INTO"),
    ("arcSmeltInto", "ARC_SMELT_INTO"),
    ("directSmelting", "DIRECT_SMELTING"),
    ("handleMaterial", "HANDLE_MATERIAL"),
    ("materialInto", "MATERIAL_INTO"),
]

FLUID_STATES = ["solid", "fluid", "gas", "plasma", "molten"]

# `gregtech.api.enums.SubTag` names that do not match their `GTMaterialFlag` counterpart 1:1; see the
# javadoc on GTMaterialFlag.
SUBTAG_FLAG_OVERRIDES = {
    "AnaerobeGas": "ANAEROBE_GAS",
    "NobleGas": "NOBLE_GAS",
}

# (hasCorrespondingFluid, hasCorrespondingGas) as MaterialsInit declared them, where the dump disagrees: the
# dump captured bartworks' BridgeMaterialsLoader setting both flags on cell-bearing werkstoff bridge
# materials AFTER LoaderGTBlockFluid's generation loop had already run with them false. Baking the dumped
# value makes that loop register a liquid and a gas fluid under one name, orphaning one of them in Forge's
# fluid registry (a load-complete "fluid registry is corrupted" FATAL). Verified against MaterialsInit source
# before stage 04 deleted it: AquaRegia was the only ported MaterialsInit-declared material affected.
CORRESPONDING_FLAG_OVERRIDES = {
    "AquaRegia": (False, False),
}

BLOCK_TEXTURE_INDEX_MIN = 65
BLOCK_TEXTURE_INDEX_MAX = 95


# region prefix filtering (mirrors scripts/mu/gen_shapes.py so the shape delta lines up with Materials2Shapes)


def is_block_kind(prefix):
    name = prefix["name"]
    if name in ("block", "frameGt"):
        return True
    if name.startswith("ore") and name != "rawOre":
        return True
    texture_index = prefix.get("textureIndex", -1)
    if texture_index is not None and BLOCK_TEXTURE_INDEX_MIN <= texture_index <= BLOCK_TEXTURE_INDEX_MAX:
        return True
    return False


def is_complex_tool_or_armor(prefix):
    name = prefix["name"]
    if name in ("tool", "armor"):
        return True
    if name.startswith("tool") and not name.startswith("toolHead"):
        return True
    if name.startswith("armor"):
        return True
    return False


def is_included_shape(prefix):
    if prefix["generationBits"] == 0:
        return False
    if not prefix["isMaterialBased"]:
        return False
    if prefix["isContainer"]:
        return False
    if is_block_kind(prefix):
        return False
    if is_complex_tool_or_armor(prefix):
        return False
    return True


def shape_field_name(prefix_name):
    return "shape" + prefix_name[0].upper() + prefix_name[1:]


# endregion

# region name sanitizing


def ml_name(name):
    """The string registered with MaterialLib: `Names.validate` rejects ':' and whitespace, nothing else, so
    only those are stripped. A handful of dynamically-generated (non-`Materials`-field) materials carry them
    (e.g. "Computation Base", "Unformed Hexanite"); every other name passes through unchanged."""
    return "".join(ch for ch in name if ch != ":" and not ch.isspace())


def field_name(name):
    """A valid Java identifier for the material's static field. Most dump names already are one; a few dozen
    chemical-formula names carry parentheses, commas, hyphens, or a leading digit, which are stripped/guarded
    the same way the legacy `Materials` class does for its equivalent fields (e.g. `Cobalt(II)Nitrate` ->
    `CobaltIINitrate`)."""
    cleaned = "".join(ch for ch in name if ch.isalnum())
    if not cleaned or cleaned[0].isdigit():
        cleaned = "_" + cleaned
    return cleaned


def java_string_literal(value):
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return '"' + escaped + '"'


def java_float_literal(value):
    if value == float("inf"):
        return "Float.POSITIVE_INFINITY"
    if value == float("-inf"):
        return "Float.NEGATIVE_INFINITY"
    return repr(float(value)) + "F"


def pack_argb(rgba):
    r, g, b, a = rgba
    if a == 0:
        a = 255
    return ((a & 0xFF) << 24) | ((r & 0xFF) << 16) | ((g & 0xFF) << 8) | (b & 0xFF)


def pack_argb_exact(rgba):
    """Like `pack_argb`, but without the alpha=0-becomes-255 substitution `StandardProperties.TINT` needs (an
    alpha-0 packed color is fully transparent, which MaterialLib's own rendering treats as "no tint" -- but
    alpha 0x00 is `MaterialBuilder`'s own default and the overwhelmingly common legacy value, so the legacy
    bridge needs the untouched byte to reproduce `Materials#mRGBa`/`mMoltenRGBa` exactly."""
    r, g, b, a = rgba
    return ((a & 0xFF) << 24) | ((r & 0xFF) << 16) | ((g & 0xFF) << 8) | (b & 0xFF)


def java_int_literal(value):
    if value < 0:
        return str(value)
    if value > 0x7FFFFFFF:
        return "0x%08X" % (value & 0xFFFFFFFF)
    return str(value)


# endregion


def load_materials():
    with open(MATERIALS_DUMP_PATH, encoding="utf-8") as f:
        return json.load(f)


def load_prefixes():
    with open(PREFIXES_DUMP_PATH, encoding="utf-8") as f:
        return json.load(f)["prefixes"]


def has_fluids(material):
    fluids = material["fluids"]
    return any(fluids.get(state) for state in FLUID_STATES)


def compute_referenced_names(materials):
    """Every material name any other dump entry points at via a MaterialRef-shaped field, so a marker
    material with no shapes/fluids/composition of its own is still ported when something needs to resolve it.
    Self-references (a material listing itself, e.g. in `oreByProducts`) are excluded -- they do not require
    the material to exist for anyone *else's* sake."""
    referenced = set()
    for material in materials:
        name = material["name"]
        for dump_key, _ in REF_PROPERTY_FIELDS:
            value = material.get(dump_key)
            if value and value != name:
                referenced.add(value)
        for stack in material["composition"]:
            if stack and stack.get("material") and stack["material"] != name:
                referenced.add(stack["material"])
        for byproduct in material["oreByProducts"]:
            if byproduct != name:
                referenced.add(byproduct)
    return referenced


def compute_ported(materials):
    referenced = compute_referenced_names(materials)
    skipped = []
    ported = []
    for material in materials:
        is_marker = not material["generatedPrefixes"] and not has_fluids(material) and not material[
            "composition"]
        if is_marker and material["name"] not in referenced:
            skipped.append(material["name"])
        else:
            ported.append(material)
    return ported, skipped


def assign_names(ported):
    ml_names = {}
    field_names = {}
    ml_seen = {}
    field_seen = {}
    for material in ported:
        raw = material["name"]
        mn = ml_name(raw)
        fn = field_name(raw)
        if mn in ml_seen:
            raise SystemExit(
                f"gen_materials.py: MaterialLib name collision: {raw!r} and {ml_seen[mn]!r} both sanitize to "
                f"{mn!r}")
        if fn in field_seen:
            raise SystemExit(
                f"gen_materials.py: Java field name collision: {raw!r} and {field_seen[fn]!r} both sanitize "
                f"to {fn!r}")
        ml_seen[mn] = raw
        field_seen[fn] = raw
        ml_names[raw] = mn
        field_names[raw] = fn
    return ml_names, field_names


def joined_families(material, prefix_bits):
    bits = 0
    for prefix_name in material["generatedPrefixes"]:
        bits |= prefix_bits.get(prefix_name, 0)
    return [family for family, bit in FAMILY_BITS if bits & bit]


def shape_delta(material, families, included_names, family_shape_members):
    dumped_items = set(p for p in material["generatedPrefixes"] if p in included_names)
    implied = set()
    for family in families:
        implied.update(family_shape_members[family])
    missing = sorted(dumped_items - implied)
    excess = sorted(implied - dumped_items)
    return missing, excess


def material_ref_literal(raw_name, ml_names):
    return f"new MaterialRef({java_string_literal(ml_names[raw_name])})"


def material_ref_stack_list_literal(stacks, ml_names):
    entries = []
    for stack in stacks:
        if not stack or not stack.get("material"):
            continue
        entries.append(
            f"new MaterialRefStack({material_ref_literal(stack['material'], ml_names)}, {stack['amount']}L)")
    return "List.of(" + ", ".join(entries) + ")"


def material_ref_stack_list_from_names(names, ml_names):
    entries = [f"new MaterialRefStack({material_ref_literal(name, ml_names)}, 1L)" for name in names]
    return "List.of(" + ", ".join(entries) + ")"


def fluid_ref_literal(fluid):
    if fluid is None:
        return "null"
    return f"new FluidRef({java_string_literal(fluid['name'])}, {fluid['temperature']})"


def build_property_lines(material, ml_names):
    lines = []

    local_name = material.get("localName")
    if local_name:
        lines.append(f".setProperty(GTMaterialProperties.LOCAL_NAME, {java_string_literal(local_name)})")

    true_name = material["name"]
    if ml_name(true_name) != true_name:
        lines.append(f".setProperty(GTMaterialProperties.LEGACY_NAME, {java_string_literal(true_name)})")

    lines.append(f".setProperty(GTMaterialProperties.ARGB, {java_int_literal(pack_argb_exact(material['rgba']))})")
    if material["moltenRgba"] != material["rgba"]:
        lines.append(
            ".setProperty(GTMaterialProperties.MOLTEN_ARGB, "
            f"{java_int_literal(pack_argb_exact(material['moltenRgba']))})")

    if material["meltingPoint"] != 0:
        lines.append(f".setProperty(GTMaterialProperties.MELTING_POINT, {material['meltingPoint']})")
    if material["blastTemp"] != 0:
        lines.append(f".setProperty(GTMaterialProperties.BLAST_TEMP, {material['blastTemp']})")
    if material["blastRequired"]:
        lines.append(".setProperty(GTMaterialProperties.BLAST_REQUIRED, true)")
    if material["gasTemp"] != 0:
        lines.append(f".setProperty(GTMaterialProperties.GAS_TEMP, {material['gasTemp']})")
    if material["fuelPower"] != 0:
        lines.append(f".setProperty(GTMaterialProperties.FUEL_POWER, {material['fuelPower']})")
    if material["fuelType"] != 0:
        lines.append(f".setProperty(GTMaterialProperties.FUEL_TYPE, {material['fuelType']})")
    if material["heatDamage"] != 0.0:
        lines.append(
            f".setProperty(GTMaterialProperties.HEAT_DAMAGE, {java_float_literal(material['heatDamage'])})")
    if material["toolSpeed"] != 1.0:
        lines.append(
            f".setProperty(GTMaterialProperties.TOOL_SPEED, {java_float_literal(material['toolSpeed'])})")
    if material["toolDurability"] != 0:
        lines.append(f".setProperty(GTMaterialProperties.DURABILITY, {material['toolDurability']})")
    if material["toolQuality"] != 0:
        lines.append(f".setProperty(GTMaterialProperties.TOOL_QUALITY, {material['toolQuality']})")
    if material["subId"] != -1:
        lines.append(f".setProperty(GTMaterialProperties.OLD_SUB_ID, {material['subId']})")

    if material["moltenRgba"] != [255, 255, 255, 0]:
        lines.append(
            f".setProperty(GTMaterialProperties.MOLTEN_TINT, {java_int_literal(pack_argb(material['moltenRgba']))})")

    if material["element"] is not None:
        lines.append(f".setProperty(GTMaterialProperties.ELEMENT, {java_string_literal(material['element'])})")

    if material["composition"]:
        lines.append(
            ".setProperty(GTMaterialProperties.COMPOSITION, "
            f"{material_ref_stack_list_literal(material['composition'], ml_names)})")

    for dump_key, property_name in REF_PROPERTY_FIELDS:
        value = material.get(dump_key)
        if value:
            lines.append(
                f".setProperty(GTMaterialProperties.{property_name}, {material_ref_literal(value, ml_names)})")

    if material["oreByProducts"]:
        lines.append(
            ".setProperty(GTMaterialProperties.ORE_BYPRODUCTS, "
            f"{material_ref_stack_list_from_names(material['oreByProducts'], ml_names)})")

    if material["subTags"]:
        flags = ", ".join(
            "GTMaterialFlag." + SUBTAG_FLAG_OVERRIDES.get(tag, tag) for tag in material["subTags"])
        lines.append(f".setProperty(GTMaterialProperties.FLAGS, EnumSet.of({flags}))")

    if material["oreMultiplier"] != 1:
        lines.append(f".setProperty(GTMaterialProperties.ORE_MULTIPLIER, {material['oreMultiplier']})")
    if material["byProductMultiplier"] != 1:
        lines.append(
            f".setProperty(GTMaterialProperties.BYPRODUCT_MULTIPLIER, {material['byProductMultiplier']})")
    if material["smeltingMultiplier"] != 1:
        lines.append(
            f".setProperty(GTMaterialProperties.SMELTING_MULTIPLIER, {material['smeltingMultiplier']})")

    if not material["unifiable"]:
        lines.append(".setProperty(GTMaterialProperties.UNIFIABLE, false)")
    if material["densityMultiplier"] != 1:
        lines.append(f".setProperty(GTMaterialProperties.DENSITY_MULTIPLIER, {material['densityMultiplier']})")
    if material["densityDivider"] != 1:
        lines.append(f".setProperty(GTMaterialProperties.DENSITY_DIVIDER, {material['densityDivider']})")
    if material["steamMultiplier"] != 1.0:
        lines.append(
            f".setProperty(GTMaterialProperties.STEAM_MULTIPLIER, {java_float_literal(material['steamMultiplier'])})")
    if material["gasMultiplier"] != 1.0:
        lines.append(
            f".setProperty(GTMaterialProperties.GAS_MULTIPLIER, {java_float_literal(material['gasMultiplier'])})")
    if material["plasmaMultiplier"] != 1.0:
        lines.append(
            ".setProperty(GTMaterialProperties.PLASMA_MULTIPLIER, "
            f"{java_float_literal(material['plasmaMultiplier'])})")

    if material["generationFlags"]:
        gen_flags = ", ".join("GTMaterialGenerationFlag." + f for f in material["generationFlags"])
        lines.append(f".setProperty(GTMaterialProperties.GENERATION_FLAGS, EnumSet.of({gen_flags}))")

    has_fluid, has_gas = CORRESPONDING_FLAG_OVERRIDES.get(
        material["name"], (material["hasCorrespondingFluid"], material["hasCorrespondingGas"]))
    if has_fluid:
        lines.append(".setProperty(GTMaterialProperties.HAS_CORRESPONDING_FLUID, true)")
    if has_gas:
        lines.append(".setProperty(GTMaterialProperties.HAS_CORRESPONDING_GAS, true)")
    if material["hasElectrolyzerRecipe"]:
        lines.append(".setProperty(GTMaterialProperties.HAS_ELECTROLYZER_RECIPE, true)")
    if material["hasCentrifugeRecipe"]:
        lines.append(".setProperty(GTMaterialProperties.HAS_CENTRIFUGE_RECIPE, true)")
    if material["canBeCracked"]:
        lines.append(".setProperty(GTMaterialProperties.CAN_BE_CRACKED, true)")
    if material["hasGlowingOre"]:
        lines.append(".setProperty(GTMaterialProperties.HAS_GLOWING_ORE, true)")
    if material["processingMaterialTierEU"] != 0:
        lines.append(
            ".setProperty(GTMaterialProperties.PROCESSING_MATERIAL_TIER_EU, "
            f"{material['processingMaterialTierEU']})")

    if material["addedPrefixes"]:
        added = ", ".join(java_string_literal(p) for p in material["addedPrefixes"])
        lines.append(f".setProperty(GTMaterialProperties.ADDED_PREFIXES, List.of({added}))")
    if material["removedPrefixes"]:
        removed = ", ".join(java_string_literal(p) for p in material["removedPrefixes"])
        lines.append(f".setProperty(GTMaterialProperties.REMOVED_PREFIXES, List.of({removed}))")

    if material.get("color"):
        lines.append(f".setProperty(GTMaterialProperties.DYE, {java_string_literal(material['color'])})")
    if not material["autoBlast"]:
        lines.append(".setProperty(GTMaterialProperties.AUTO_BLAST_FURNACE_RECIPES, false)")
    if not material["autoVacuum"]:
        lines.append(".setProperty(GTMaterialProperties.AUTO_VACUUM_FREEZER_RECIPES, false)")
    if not material["autoRecycle"]:
        lines.append(".setProperty(GTMaterialProperties.AUTO_RECYCLE_RECIPES, false)")

    tool_enchant = material["enchants"].get("tool")
    if tool_enchant:
        lines.append(
            f".setProperty(GTMaterialProperties.TOOL_ENCHANTMENT, {java_string_literal(tool_enchant['name'])})")
        lines.append(f".setProperty(GTMaterialProperties.TOOL_ENCHANTMENT_LEVEL, {tool_enchant['level']})")
    armor_enchant = material["enchants"].get("armor")
    if armor_enchant:
        lines.append(
            f".setProperty(GTMaterialProperties.ARMOR_ENCHANTMENT, {java_string_literal(armor_enchant['name'])})")
        lines.append(f".setProperty(GTMaterialProperties.ARMOR_ENCHANTMENT_LEVEL, {armor_enchant['level']})")

    if material["aspects"]:
        aspect_entries = ", ".join(
            f"new AspectRefStack({java_string_literal(a['name'])}, {a['amount']})" for a in material["aspects"])
        lines.append(f".setProperty(GTMaterialProperties.ASPECTS, List.of({aspect_entries}))")

    fluids = material["fluids"]
    if has_fluids(material):
        fluid_args = ", ".join(fluid_ref_literal(fluids[state]) for state in FLUID_STATES)
        lines.append(f".setProperty(GTMaterialProperties.LEGACY_FLUIDS, new FluidNames({fluid_args}))")

    return lines


def build_material_block(material, families, ml_names, field_names, included_names, family_shape_members):
    field = field_names[material["name"]]
    name_literal = java_string_literal(ml_names[material["name"]])
    icon_set_literal = java_string_literal(material["iconSet"])

    lines = []
    lines.append(
        f"        Materials2Materials.{field} = MaterialLibAPI"
        f".newMaterial(\"gregtech\", {name_literal}, TextureSet.of(\"gregtech\", {icon_set_literal}))")
    lines.append(f"            .setTint({java_int_literal(pack_argb(material['rgba']))})")
    lines.append("            .addToFamily(Materials2Families.familyAll)")
    for family in families:
        lines.append(f"            .addToFamily(Materials2Families.{family})")

    missing, excess = shape_delta(material, families, included_names, family_shape_members)
    for prefix_name in missing:
        lines.append(f"            .generateShape(Materials2Shapes.{shape_field_name(prefix_name)})")

    for property_line in build_property_lines(material, ml_names):
        lines.append("            " + property_line)

    lines.append("            .build();")

    if excess:
        lines.append(f"        MaterialLibAPI.editMaterial(\"gregtech\", {name_literal})")
        for prefix_name in excess:
            lines.append(f"            .removeShape(Materials2Shapes.{shape_field_name(prefix_name)})")
        lines[-1] += ";"

    return lines


def chunk(items, size):
    for i in range(0, len(items), size):
        yield items[i:i + size]


def write_data_file(index, materials, families_by_name, ml_names, field_names, included_names,
                     family_shape_members):
    class_name = f"Materials2Data{index}"
    lines = []
    lines.append("package gregtech.api.enums.materials2;")
    lines.append("")
    lines.append("import java.util.EnumSet;")
    lines.append("import java.util.List;")
    lines.append("")
    lines.append("import com.ruling_0.materiallib.api.MaterialLibAPI;")
    lines.append("import com.ruling_0.materiallib.api.TextureSet;")
    lines.append("")
    lines.append("import gregtech.api.material.AspectRefStack;")
    lines.append("import gregtech.api.material.FluidNames;")
    lines.append("import gregtech.api.material.FluidRef;")
    lines.append("import gregtech.api.material.GTMaterialFlag;")
    lines.append("import gregtech.api.material.GTMaterialGenerationFlag;")
    lines.append("import gregtech.api.material.GTMaterialProperties;")
    lines.append("import gregtech.api.material.MaterialRef;")
    lines.append("import gregtech.api.material.MaterialRefStack;")
    lines.append("")
    first = (index - 1) * MATERIALS_PER_FILE + 1
    last = (index - 1) * MATERIALS_PER_FILE + len(materials)
    lines.append(GENERATED_HEADER)
    lines.append(f"/// Material declarations {first}..{last}, see [Materials2Materials].")
    lines.append(f"public class {class_name} {{")
    lines.append("")
    lines.append("    public static void init() {")
    lines.append("        // spotless:off")
    for material in materials:
        families = families_by_name[material["name"]]
        lines.extend(
            build_material_block(
                material, families, ml_names, field_names, included_names, family_shape_members))
    lines.append("        // spotless:on")
    lines.append("    }")
    lines.append("")
    lines.append(f"    private {class_name}() {{}}")
    lines.append("}")
    lines.append("")

    output_path = MATERIALS2_DIR / f"{class_name}.java"
    output_path.write_text("\n".join(lines), encoding="utf-8")
    return class_name


def write_materials_file(ported, field_names, data_class_names):
    lines = []
    lines.append("package gregtech.api.enums.materials2;")
    lines.append("")
    lines.append("import com.ruling_0.materiallib.api.Material;")
    lines.append("")
    lines.append(GENERATED_HEADER)
    lines.append("/// One [Material] field per ported GregTech material, named after the legacy `Materials`")
    lines.append(
        "/// field where the dump's material name is already a valid Java identifier, else a sanitized")
    lines.append("/// variant (see `scripts/mu/gen_materials.py`).")
    lines.append("public class Materials2Materials {")
    lines.append("")
    lines.append("    // spotless:off")
    for material in ported:
        lines.append(f"    public static Material {field_names[material['name']]};")
    lines.append("    // spotless:on")
    lines.append("")
    lines.append("    public static void init() {")
    for class_name in data_class_names:
        lines.append(f"        {class_name}.init();")
    lines.append("    }")
    lines.append("")
    lines.append("    private Materials2Materials() {}")
    lines.append("}")
    lines.append("")
    MATERIALS_OUTPUT.write_text("\n".join(lines), encoding="utf-8")


# region legacy bridge (stage 04)

LEGACY_ASSIGN_RE = re.compile(r"Materials\.(\w+) = (\w+)\(\);")
# Two legacy fields sharing one instance, e.g. `Materials.Water = Materials.Steam = loadWater();` (Water/Steam,
# WroughtIron/CastIron) -- both fields need the same ml-name mapping.
LEGACY_CHAINED_ASSIGN_RE = re.compile(r"Materials\.(\w+) = Materials\.(\w+) = (\w+)\(\);")
LEGACY_METHOD_RE = re.compile(r"private static Materials (\w+)\(\) \{(.*?)\n    \}", re.S)
LEGACY_SETNAME_RE = re.compile(r'setName\(\s*"((?:[^"\\]|\\.)*)"')


def load_legacy_field_names():
    """Maps every legacy `Materials` static field name assigned by `MaterialsInit.load()` to the `mName`
    passed to that material's `setName(...)` call, so the ml-name-keyed ported set can be matched back to the
    Java field it must be assigned to. Only meaningful while `MaterialsInit.java` still existed; the
    MaterialsLegacyBridge/LegacyMaterials split it drove was a one-time port, so once stage 04 deleted that
    file the committed bridge is left untouched (see `write_legacy_bridge_file`)."""
    text = LEGACY_MATERIALS_INIT.read_text(encoding="utf-8")
    method_bodies = {m.group(1): m.group(2) for m in LEGACY_METHOD_RE.finditer(text)}

    assigns = list(LEGACY_ASSIGN_RE.findall(text))
    for first_field, second_field, method in LEGACY_CHAINED_ASSIGN_RE.findall(text):
        assigns.append((first_field, method))
        assigns.append((second_field, method))

    field_to_mname = {}
    for field, method in assigns:
        body = method_bodies.get(method)
        if body is None:
            raise SystemExit(f"gen_materials.py: no method body found for {method}() (field {field})")
        sm = LEGACY_SETNAME_RE.search(body)
        if not sm:
            raise SystemExit(f"gen_materials.py: no setName(...) found in {method}() (field {field})")
        field_to_mname[field] = sm.group(1)
    return field_to_mname


def order_by_composition(bridge_fields, materials_by_name, field_to_mname, field_names):
    """`MaterialBuilder#addMaterial` adds directly to the legacy `Materials.mMaterialList`, unlike the
    ore-byproduct/smelt-into-style links, which resolve lazily through a `Supplier`. A material's composition
    inputs must therefore already be built (and sitting in `Materials.getMaterialsMap()`) before it is built
    itself, or `Materials.get(...)` silently returns `Materials._NULL` for a forward reference. Topologically
    sorts `bridge_fields` by composition dependency (Kahn's algorithm); ties broken by the existing (field
    name) order for a stable, readable diff. Returns a list of `(fields, ml_field)` pairs, in dependency
    order; `fields` has more than one entry for an mname two legacy fields share (`Water`/`Steam`,
    `WroughtIron`/`CastIron`)."""
    mname_by_field = {f: field_to_mname[f] for f, _ in bridge_fields}
    bridge_mnames = set(mname_by_field.values())

    depends_on = {mname: [] for mname in bridge_mnames}
    for mname in bridge_mnames:
        for stack in materials_by_name[mname]["composition"]:
            dep = stack.get("material") if stack else None
            if dep and dep != mname and dep in bridge_mnames:
                depends_on[mname].append(dep)

    order_index = {field: i for i, (field, _) in enumerate(bridge_fields)}
    # A single MaterialLib material can back more than one legacy field (e.g. `Water`/`Steam` and
    # `WroughtIron`/`CastIron`, both `Materials.A = Materials.B = loadX();` in MaterialsInit) -- every field
    # sharing an mname must be emitted, in their original relative order.
    fields_by_mname = {}
    for field, mname in mname_by_field.items():
        fields_by_mname.setdefault(mname, []).append(field)
    for fields in fields_by_mname.values():
        fields.sort(key=lambda f: order_index[f])
    representative_field = {mname: fields[0] for mname, fields in fields_by_mname.items()}

    visited = set()
    in_progress = set()
    ordered_mnames = []

    def visit(mname):
        if mname in visited:
            return
        if mname in in_progress:
            raise SystemExit(f"gen_materials.py: composition dependency cycle involving {mname!r}")
        in_progress.add(mname)
        for dep in sorted(depends_on[mname], key=lambda d: order_index[representative_field[d]]):
            visit(dep)
        in_progress.discard(mname)
        visited.add(mname)
        ordered_mnames.append(mname)

    for _, mname in sorted(mname_by_field.items(), key=lambda kv: order_index[kv[0]]):
        visit(mname)

    return [(fields_by_mname[mname], field_names[mname]) for mname in ordered_mnames]


def write_legacy_bridge_file(ported_names, field_names, materials_by_name):
    if not LEGACY_MATERIALS_INIT.exists():
        print(
            "gen_materials.py: MaterialsInit.java no longer exists (deleted by stage 04); leaving the "
            "committed MaterialsLegacyBridge.java untouched")
        return None, None

    field_to_mname = load_legacy_field_names()

    bridge_fields = []
    retained_fields = []
    for legacy_field, mname in sorted(field_to_mname.items()):
        if mname in ported_names:
            bridge_fields.append((legacy_field, mname))
        else:
            retained_fields.append(legacy_field)

    groups = order_by_composition(bridge_fields, materials_by_name, field_to_mname, field_names)

    lines = []
    lines.append("package gregtech.loaders.materials;")
    lines.append("")
    lines.append("import gregtech.api.enums.Materials;")
    lines.append("import gregtech.api.enums.materials2.Materials2Materials;")
    lines.append("")
    lines.append(GENERATED_HEADER)
    lines.append("/// Rebuilds every MaterialLib-backed legacy `Materials` field from the stage-03 port, via")
    lines.append("/// [LegacyMaterials#build]. [LegacyMarkerMaterials#loadMarkers] separately rebuilds the legacy")
    lines.append("/// fields that carry no MaterialLib data (never generated an item/fluid/composition and are")
    lines.append("/// unreferenced by a ported material).")
    lines.append("public class MaterialsLegacyBridge {")
    lines.append("")
    lines.append("    public static void load() {")
    lines.append("        LegacyMarkerMaterials.loadMarkers();")
    lines.append("        // A bare JUnit run never fires MaterialLib's MaterialRegistrationEvent, so")
    lines.append("        // Materials2Materials fields stay null outside a real FML mod-loading lifecycle.")
    lines.append("        // Fall back to named stubs rather than NPE-ing Materials' static initializer")
    lines.append("        // (which would poison every test class referencing it); stubs match what bare")
    lines.append("        // JUnit saw under MaterialsInit closely enough (fluids were always null there")
    lines.append("        // too -- they only register during a real preInit).")
    lines.append("        if (Materials2Materials.Iron == null) {")
    lines.append("            loadStubs();")
    lines.append("            return;")
    lines.append("        }")
    lines.append("        // spotless:off")
    bridge_count = 0
    for fields, ml_field in groups:
        primary, *aliases = fields
        bridge_count += len(fields)
        lines.append(
            f"        Materials.{primary} = LegacyMaterials.build(Materials2Materials.{ml_field});")
        for alias in aliases:
            lines.append(f"        Materials.{alias} = Materials.{primary};")
    lines.append("        // spotless:on")
    lines.append("    }")
    lines.append("")
    lines.append("    private static void loadStubs() {")
    lines.append("        // spotless:off")
    for fields, _ in groups:
        primary, *aliases = fields
        mname = field_to_mname[primary]
        lines.append(f"        Materials.{primary} = LegacyMaterials.stub({java_string_literal(mname)});")
        for alias in aliases:
            lines.append(f"        Materials.{alias} = Materials.{primary};")
    lines.append("        // spotless:on")
    lines.append("    }")
    lines.append("")
    lines.append("    private MaterialsLegacyBridge() {}")
    lines.append("}")
    lines.append("")
    LEGACY_BRIDGE_OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    return bridge_count, retained_fields


# endregion

LANG_BEGIN = "# --- BEGIN GENERATED MATERIAL NAMES (scripts/mu/gen_materials.py) ---"
LANG_END = "# --- END GENERATED MATERIAL NAMES ---"


def write_lang_file(ported, ml_names):
    entries = sorted(
        (ml_names[material["name"]], material["localName"]) for material in ported if material["localName"])
    block_lines = [LANG_BEGIN]
    for name, local_name in entries:
        block_lines.append(f"material.gregtech.{name}={local_name}")
    block_lines.append(LANG_END)
    block = "\n".join(block_lines)

    if LANG_OUTPUT.exists():
        text = LANG_OUTPUT.read_text(encoding="utf-8")
        if LANG_BEGIN in text and LANG_END in text:
            before = text[:text.index(LANG_BEGIN)]
            after = text[text.index(LANG_END) + len(LANG_END):]
            text = before.rstrip("\n") + "\n\n" + block + after
        else:
            text = text.rstrip("\n") + "\n\n" + block + "\n"
    else:
        text = block + "\n"
    LANG_OUTPUT.write_text(text, encoding="utf-8")


def main():
    materials = load_materials()
    prefixes = load_prefixes()

    prefix_bits = {p["name"]: p["generationBits"] for p in prefixes}
    included_prefixes = [p for p in prefixes if is_included_shape(p)]
    included_names = set(p["name"] for p in included_prefixes)

    family_shape_members = {family: [] for family, _ in FAMILY_BITS}
    for prefix in included_prefixes:
        bits = prefix["generationBits"]
        for family, bit in FAMILY_BITS:
            if bits & bit:
                family_shape_members[family].append(prefix["name"])

    ported, skipped = compute_ported(materials)
    ml_names, field_names = assign_names(ported)
    families_by_name = {m["name"]: joined_families(m, prefix_bits) for m in ported}

    batches = list(chunk(ported, MATERIALS_PER_FILE))
    MATERIALS2_DIR.mkdir(parents=True, exist_ok=True)
    data_class_names = []
    for i, batch in enumerate(batches, start=1):
        data_class_names.append(
            write_data_file(
                i, batch, families_by_name, ml_names, field_names, included_names, family_shape_members))

    write_materials_file(ported, field_names, data_class_names)
    write_lang_file(ported, ml_names)

    ported_names = set(ml_names.keys())
    materials_by_name = {m["name"]: m for m in ported}
    bridge_count, retained_fields = write_legacy_bridge_file(ported_names, field_names, materials_by_name)

    print(f"gen_materials.py: {len(materials)} dump entries, {len(ported)} ported, {len(skipped)} skipped")
    print(f"  wrote {len(data_class_names)} data files + {MATERIALS_OUTPUT.relative_to(REPO_ROOT)}")
    print(f"  wrote {LANG_OUTPUT.relative_to(REPO_ROOT)}")
    if bridge_count is not None:
        print(
            f"  wrote {LEGACY_BRIDGE_OUTPUT.relative_to(REPO_ROOT)}: {bridge_count} bridged fields, "
            f"{len(retained_fields)} retained as markers (see LegacyMarkerMaterials.loadMarkers)")


if __name__ == "__main__":
    main()
