#!/usr/bin/env python3
"""Generates the stage-11 commit-4 gtPlusPlus item-cutover Postea transformer table from the pinned
`gtpp-materials.json` dump's `generatedParts`: one (prefix, material, legacy registry name) row per legacy
`miscutils:` item whose part prefix has cut over to a MaterialLib shape (see
`gtPlusPlus.core.material.MaterialReconstruction#isPartCutOver` -- CUTOVER_PREFIXES below must match its
`CUT_OVER_PART_PREFIXES` set). `PosteaTransformers` registers one migration handler per generated row in a
single loop, so this table -- not hand-written registrations -- is the source of truth for which legacy
items migrate.

Entries whose `generatedParts` registry name is not `miscutils:`-namespaced are skipped: those already
resolve to a stable MaterialLib/gregtech/vanilla stack (either cut over by an earlier stage, or never
gtpp-owned), so no migration is needed.

Run from anywhere; paths are resolved relative to this script's location. Requires only the Python 3
standard library.

Usage: python scripts/mu/gen_gtpp_item_transformers.py
"""

import json
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
DUMP_PATH = SCRIPT_DIR / "dumps" / "gtpp-materials.json"

OUTPUT = REPO_ROOT / "src/main/java/gregtech/loaders/postload/GtppItemCutoverTable.java"

GENERATED_HEADER = "// Generated by scripts/mu/gen_gtpp_item_transformers.py; edit the script, not this file."

# Mirrors gtPlusPlus.core.material.MaterialReconstruction#CUT_OVER_PART_PREFIXES: the item-kind (not
# block-kind) part families cut over so far. Excludes block/frameGt (blocks+ores commit) and cell/cellPlasma
# (fluid cutover commit).
CUTOVER_PREFIXES = {
    "dust", "dustSmall", "dustTiny", "ingot", "ingotHot", "nugget", "plate", "plateDouble", "plateDense",
    "plateSuperdense", "gearGt", "gearGtSmall", "bolt", "screw", "ring", "rotor", "foil", "wireFine",
    "spring", "springSmall", "stick", "stickLong", "crushed", "crushedCentrifuged", "crushedPurified",
    "dustImpure", "dustPure", "milled", "rawOre",
}

ENTRIES_PER_FILE = 400


def load_rows():
    materials = json.loads(DUMP_PATH.read_text(encoding="utf-8"))
    rows = []
    for material in materials:
        name = material["unlocalizedName"]
        for part in material.get("generatedParts") or []:
            prefix = part["prefix"]
            registry_name = part["registryName"]
            if prefix not in CUTOVER_PREFIXES:
                continue
            if not registry_name.startswith("miscutils:"):
                continue
            assert part["meta"] == 0, f"unexpected nonzero meta for {name}/{prefix}: {part}"
            rows.append((prefix, name, registry_name))
    rows.sort()
    return rows


def java_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def generate(rows):
    lines = []
    lines.append(GENERATED_HEADER)
    lines.append("package gregtech.loaders.postload;")
    lines.append("")
    lines.append("import gregtech.api.enums.OrePrefixes;")
    lines.append("")
    lines.append("/// The stage-11 commit-4 gtPlusPlus item-cutover Postea migration table: one row per legacy")
    lines.append("/// `miscutils:item*`-registered gtPlusPlus per-material part item whose prefix has cut over to a")
    lines.append("/// MaterialLib shape, read from the pinned `gtpp-materials.json` dump's `generatedParts`. Block-kind")
    lines.append("/// parts (`block`, `frameGt`) and fluid-tied parts (`cell`, `cellPlasma`) migrate separately.")
    lines.append("/// [PosteaTransformers] migrates each row's legacy stack to `MU.stack(prefix, MaterialLibAPI.getMaterial(")
    lines.append('/// "gregtech", materialName), 1)` in a single loop -- see `scripts/mu/gen_gtpp_item_transformers.py`.')
    lines.append("public final class GtppItemCutoverTable {")
    lines.append("")
    lines.append("    public record Entry(OrePrefixes prefix, String materialName, String registryName) {}")
    lines.append("")
    lines.append("    private GtppItemCutoverTable() {}")
    lines.append("")
    lines.append("    // spotless:off")
    lines.append(f"    public static final Entry[] ENTRIES = new Entry[] {{")
    for prefix, name, registry_name in rows:
        lines.append(
            f"        new Entry(OrePrefixes.{prefix}, {java_string(name)}, {java_string(registry_name)}),"
        )
    lines.append("    };")
    lines.append("    // spotless:on")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    rows = load_rows()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generate(rows), encoding="utf-8", newline="\n")
    print(f"Wrote {len(rows)} entries to {OUTPUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
