#!/usr/bin/env python3
"""Generates the stage-03 MaterialLib material declarations from the `gt-materials.json` and
`oreprefixes.json` material-unification dumps, plus the stage-10 werkstoff fold from `werkstoff.json`
(bartworks/goodgenerator/gtnhlanth pools): every non-proxy werkstoff merges into the gregtech dump entry of
the same name (each has one -- bartworks' BridgeMaterialsLoader created a bridge `Materials` mirror per
werkstoff at runtime, which the gregtech dump captured), adding the werkstoff shape set and a composite
`WERKSTOFF` property while the gregtech dump keeps winning every shared scalar. Every fold is written to
`merge-report.txt` for review. `werkstoff.json` is a PINNED pre-stage-10 capture -- never refresh it from
a post-fold boot (see `MaterialDataDump#dumpWerkstoffGeneratedPrefixes`).

Run from anywhere; paths are resolved relative to this script's location. Requires only the Python 3
standard library.

Usage: python scripts/mu/gen_materials.py
"""

import json
import re
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
MATERIALS_DUMP_PATH = SCRIPT_DIR / "dumps" / "gt-materials.json"
PREFIXES_DUMP_PATH = SCRIPT_DIR / "dumps" / "oreprefixes.json"
LEGACY_VARIANTS_DUMP_PATH = SCRIPT_DIR / "dumps" / "legacy-variants.json"
FLUID_TEXTURES_DUMP_PATH = SCRIPT_DIR / "dumps" / "fluid-textures.json"
WERKSTOFF_DUMP_PATH = SCRIPT_DIR / "dumps" / "werkstoff.json"
MERGE_REPORT_PATH = SCRIPT_DIR / "merge-report.txt"

MATERIALS2_DIR = REPO_ROOT / "src/main/java/gregtech/api/enums/materials2"
MATERIALS_OUTPUT = MATERIALS2_DIR / "Materials2Materials.java"
LANG_OUTPUT = REPO_ROOT / "src/main/resources/assets/gregtech/lang/en_US.lang"

LEGACY_MATERIALS_INIT = REPO_ROOT / "src/main/java/gregtech/loaders/materials/MaterialsInit.java"
LEGACY_BRIDGE_OUTPUT = REPO_ROOT / "src/main/java/gregtech/loaders/materials/MaterialsLegacyBridge.java"

GENERATED_HEADER = "// Generated by scripts/mu/gen_materials.py; edit the script, not this file."

# Kept low enough that a data file's init() method, one builder chain per material, stays comfortably under
# the JVM's 64k-bytecode-per-method limit even for materials with large composition/aspect lists (halved from
# 120 when the stage-10 WerkstoffData literals pushed a dense-werkstoff batch over it).
MATERIALS_PER_FILE = 60

# Mirrors gregtech.api.enums.OrePrefixes generation-bit constants; see scripts/mu/gen_shapes.py.
DUST = 1
METAL = 2
GEM = 4
ORE = 8
CELL = 16
PLASMA = 32
TOOL = 64
GEAR = 128
EMPTY = 256

FAMILY_BITS = [
    ("familyDusts", DUST),
    ("familyMetals", METAL),
    ("familyGems", GEM),
    ("familyOres", ORE),
    ("familyCells", CELL),
    ("familyPlasmas", PLASMA),
    ("familyToolParts", TOOL),
    ("familyGears", GEAR),
    ("familyEmpties", EMPTY),
]

REF_PROPERTY_FIELDS = [
    ("smeltInto", "SMELT_INTO"),
    ("macerateInto", "MACERATE_INTO"),
    ("arcSmeltInto", "ARC_SMELT_INTO"),
    ("directSmelting", "DIRECT_SMELTING"),
    ("handleMaterial", "HANDLE_MATERIAL"),
    ("materialInto", "MATERIAL_INTO"),
]

FLUID_STATES = ["solid", "fluid", "gas", "plasma", "molten"]

# `gregtech.api.enums.SubTag` names that do not match their `GTMaterialFlag` counterpart 1:1; see the
# javadoc on GTMaterialFlag.
SUBTAG_FLAG_OVERRIDES = {
    "AnaerobeGas": "ANAEROBE_GAS",
    "NobleGas": "NOBLE_GAS",
}

# (hasCorrespondingFluid, hasCorrespondingGas) as MaterialsInit declared them, where the dump disagrees: the
# dump captured bartworks' BridgeMaterialsLoader setting both flags on cell-bearing werkstoff bridge
# materials AFTER LoaderGTBlockFluid's generation loop had already run with them false. Baking the dumped
# value makes that loop register a liquid and a gas fluid under one name, orphaning one of them in Forge's
# fluid registry (a load-complete "fluid registry is corrupted" FATAL). Verified against MaterialsInit source
# before stage 04 deleted it: AquaRegia was the only ported MaterialsInit-declared material affected.
CORRESPONDING_FLAG_OVERRIDES = {
    "AquaRegia": (False, False),
}

BLOCK_TEXTURE_INDEX_MIN = 65
BLOCK_TEXTURE_INDEX_MAX = 95


# region prefix filtering (mirrors scripts/mu/gen_shapes.py so the shape delta lines up with Materials2Shapes)


def is_block_kind(prefix):
    name = prefix["name"]
    if name in ("block", "frameGt"):
        return True
    if name.startswith("ore") and name != "rawOre":
        return True
    texture_index = prefix.get("textureIndex", -1)
    if texture_index is not None and BLOCK_TEXTURE_INDEX_MIN <= texture_index <= BLOCK_TEXTURE_INDEX_MAX:
        return True
    return False


def is_complex_tool_or_armor(prefix):
    name = prefix["name"]
    if name in ("tool", "armor"):
        return True
    if name.startswith("tool") and not name.startswith("toolHead"):
        return True
    if name.startswith("armor"):
        return True
    return False


def is_included_shape(prefix, legacy_variant_prefixes):
    if prefix["generationBits"] == 0:
        return False
    if not prefix["isMaterialBased"]:
        return False
    if prefix["isContainer"]:
        return False
    if is_block_kind(prefix):
        return False
    if is_complex_tool_or_armor(prefix):
        return False
    # Bugfix (group A, mirrors gen_shapes.py): intersect with legacy-variants.json ground truth so a
    # capability-bit-only prefix (no real constructor slot, e.g. crystal/milled/shard) is not treated as an
    # included shape here either -- keeps this file's shape set identical to Materials2Shapes.
    return prefix["name"] in legacy_variant_prefixes


def shape_field_name(prefix_name):
    return "shape" + prefix_name[0].upper() + prefix_name[1:]


# endregion

# region name sanitizing


def ml_name(name):
    """The string registered with MaterialLib: `Names.validate` rejects ':' and whitespace, nothing else, so
    only those are stripped. A handful of dynamically-generated (non-`Materials`-field) materials carry them
    (e.g. "Computation Base", "Unformed Hexanite"); every other name passes through unchanged."""
    return "".join(ch for ch in name if ch != ":" and not ch.isspace())


def field_name(name):
    """A valid Java identifier for the material's static field. Most dump names already are one; a few dozen
    chemical-formula names carry parentheses, commas, hyphens, or a leading digit, which are stripped/guarded
    the same way the legacy `Materials` class does for its equivalent fields (e.g. `Cobalt(II)Nitrate` ->
    `CobaltIINitrate`)."""
    cleaned = "".join(ch for ch in name if ch.isalnum())
    if not cleaned or cleaned[0].isdigit():
        cleaned = "_" + cleaned
    return cleaned


def java_string_literal(value):
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return '"' + escaped + '"'


def java_float_literal(value):
    if value == float("inf"):
        return "Float.POSITIVE_INFINITY"
    if value == float("-inf"):
        return "Float.NEGATIVE_INFINITY"
    return repr(float(value)) + "F"


def java_double_literal(value):
    if value == float("inf"):
        return "Double.POSITIVE_INFINITY"
    if value == float("-inf"):
        return "Double.NEGATIVE_INFINITY"
    return repr(float(value)) + "D"


def pack_argb(rgba):
    r, g, b, a = rgba
    if a == 0:
        a = 255
    return ((a & 0xFF) << 24) | ((r & 0xFF) << 16) | ((g & 0xFF) << 8) | (b & 0xFF)


def pack_argb_exact(rgba):
    """Like `pack_argb`, but without the alpha=0-becomes-255 substitution `StandardProperties.TINT` needs (an
    alpha-0 packed color is fully transparent, which MaterialLib's own rendering treats as "no tint" -- but
    alpha 0x00 is `MaterialBuilder`'s own default and the overwhelmingly common legacy value, so the legacy
    bridge needs the untouched byte to reproduce `Materials#mRGBa`/`mMoltenRGBa` exactly."""
    r, g, b, a = rgba
    return ((a & 0xFF) << 24) | ((r & 0xFF) << 16) | ((g & 0xFF) << 8) | (b & 0xFF)


def java_int_literal(value):
    if value < 0:
        return str(value)
    if value > 0x7FFFFFFF:
        return "0x%08X" % (value & 0xFFFFFFFF)
    return str(value)


# endregion


def load_materials():
    with open(MATERIALS_DUMP_PATH, encoding="utf-8") as f:
        return json.load(f)


def load_prefixes():
    with open(PREFIXES_DUMP_PATH, encoding="utf-8") as f:
        return json.load(f)["prefixes"]


def load_legacy_variants():
    with open(LEGACY_VARIANTS_DUMP_PATH, encoding="utf-8") as f:
        return json.load(f)


def load_fluid_textures():
    """Empty (every `FluidRef.texture` null) until the first dump run produces `fluid-textures.json` -- this
    script must be able to bootstrap a build that can run that dump in the first place."""
    if not FLUID_TEXTURES_DUMP_PATH.exists():
        return {}
    with open(FLUID_TEXTURES_DUMP_PATH, encoding="utf-8") as f:
        return json.load(f)


def load_legacy_variant_prefixes(variants):
    return {v["prefix"] for v in variants}


# region werkstoff fold (stage 10)

# Werkstoff prefixes that keep their legacy bartworks blocks (GregTechAPI.sBlockSheetmetalBW /
# sBlockFramesBW): mirrors the gregtech-side decision that frameGt/sheetmetal never cut over to MaterialLib
# shapes (stage 07 scoped `block` only). They still appear in WerkstoffData#prefixes so the legacy
# reconstruction keeps serving them.
WERKSTOFF_LEGACY_ONLY_PREFIXES = {"sheetmetal", "frameGt"}

# Werkstoff prefixes with a hand-written (non-Materials2Shapes) MaterialLib shape.
WERKSTOFF_SPECIAL_PREFIXES = {"cell", "cellMolten", "block", "ore", "blockCasing", "blockCasingAdvanced"}

WERKSTOFF_FLAG_FIELDS = [
    ("sublimation", "SUBLIMATION"),
    ("toxic", "TOXIC"),
    ("radioactive", "RADIOACTIVE"),
    ("blastFurnace", "BLAST_FURNACE"),
    ("elektrolysis", "ELECTROLYSIS"),
    ("centrifuge", "CENTRIFUGE"),
    ("gas", "GAS"),
    ("enforceUnification", "ENFORCE_UNIFICATION"),
    ("chemicalRecipes", "CHEMICAL_SYNTHESIS"),
    ("metalCraftingSolidifierRecipes", "METAL_CRAFTING_SOLIDIFICATION"),
    ("metalSolidifierRecipes", "METAL_SOLIDIFICATION"),
    ("mixerRecipes", "MIXING"),
    ("sifterRecipes", "SIFTING"),
    ("formulaLocalized", "LOCALIZED_FORMULA"),
]


def load_werkstoffs():
    with open(WERKSTOFF_DUMP_PATH, encoding="utf-8") as f:
        return json.load(f)


def group_werkstoffs(werkstoffs):
    """Groups the dump by target gregtech material name. Non-proxy entries key by `varName` (== the bridge
    mirror's `mName`); the `id > 31765` proxies (werkstoffe that exist only to give a GT material bartworks
    casings/items) are not ported themselves -- only their `generatedPrefixes` fold onto their
    `bridgeMaterial`'s declaration. Returns `(by_name, display_to_var)` where each `by_name` value is
    `{"entries": [...], "prefixes": [...]}` (entries in id order, possibly empty for a proxy-only target;
    prefixes union-ordered first-entry-first)."""
    by_name = {}
    display_to_var = {}
    for entry in werkstoffs:
        if entry["pool"] == "unknown":
            continue
        if not entry["isProxy"]:
            display_to_var[entry["name"]] = entry["varName"]
    for entry in sorted(werkstoffs, key=lambda e: e["id"]):
        if entry["pool"] == "unknown":
            continue
        name = entry["bridgeMaterial"] if entry["isProxy"] else entry["varName"]
        if entry["isProxy"] and name is None:
            raise SystemExit(f"gen_materials.py: proxy werkstoff {entry['id']} has no bridgeMaterial")
        info = by_name.setdefault(name, {"entries": [], "prefixes": []})
        if not entry["isProxy"]:
            info["entries"].append(entry)
        for prefix in entry["generatedPrefixes"]:
            if prefix not in info["prefixes"]:
                info["prefixes"].append(prefix)
    return by_name, display_to_var


def werkstoff_ref_name(ref_name, kind, display_to_var):
    """Maps a werkstoff-dump reference (contents/oreByProducts entry) to a gregtech material name: werkstoff
    references use the display name (`getDefaultName`), material references the legacy `mName` (== the ml
    name for every name the werkstoff data can reach)."""
    if kind == "werkstoff":
        var = display_to_var.get(ref_name)
        if var is None:
            raise SystemExit(f"gen_materials.py: dangling werkstoff reference {ref_name!r}")
        return var
    return ref_name


def compute_werkstoff_referenced_names(werkstoff_by_name, display_to_var):
    referenced = set()
    for info in werkstoff_by_name.values():
        for entry in info["entries"]:
            for content in entry["contents"]:
                referenced.add(werkstoff_ref_name(content["name"], content["kind"], display_to_var))
            for byproduct in entry["oreByProducts"]:
                referenced.add(display_to_var.get(byproduct, byproduct))
    return referenced


def validate_werkstoff_prefixes(werkstoff_by_name, included_names):
    """Reference-closure-style fail-loud check: every dumped werkstoff prefix must map to a MaterialLib shape
    or be a deliberate legacy retention, so a new bartworks prefix cannot silently drop items."""
    known = included_names | WERKSTOFF_SPECIAL_PREFIXES | WERKSTOFF_LEGACY_ONLY_PREFIXES
    for name, info in sorted(werkstoff_by_name.items()):
        unknown = [p for p in info["prefixes"] if p not in known]
        if unknown:
            raise SystemExit(f"gen_materials.py: werkstoff {name!r} generates unmapped prefixes {unknown}")


def werkstoff_flag_names(entries):
    flags = []
    for entry in entries:
        for field, flag in WERKSTOFF_FLAG_FIELDS:
            if entry[field] and flag not in flags:
                flags.append(flag)
        if not entry["autoBlastFurnaceRecipes"] and "NO_AUTO_BLAST_FURNACE_RECIPES" not in flags:
            flags.append("NO_AUTO_BLAST_FURNACE_RECIPES")
        if not entry["autoVacuumFreezerRecipes"] and "NO_AUTO_VACUUM_FREEZER_RECIPES" not in flags:
            flags.append("NO_AUTO_VACUUM_FREEZER_RECIPES")
    return flags


def werkstoff_property_line(info, ml_names, display_to_var):
    """The composite `GTMaterialProperties.WERKSTOFF` literal -- see `WerkstoffData`'s javadoc for why the
    bartworks-side values live here instead of the shared keys (the gregtech dump wins those). Scalars come
    from the first (lowest-id) entry; prefixes/flags/subTags/additionalOredict union across a same-name fold;
    contents/oreByProducts/formula come from the first entry carrying one."""
    entries = info["entries"]
    if not entries:
        return None
    first = entries[0]

    ids = ", ".join(str(e["id"]) for e in entries)
    flags = werkstoff_flag_names(entries)
    flags_literal = ("EnumSet.of(" + ", ".join("GTWerkstoffFlag." + f for f in flags) + ")") if flags \
        else "EnumSet.noneOf(GTWerkstoffFlag.class)"
    prefixes_literal = "List.of(" + ", ".join(java_string_literal(p) for p in info["prefixes"]) + ")"

    contents = next((e["contents"] for e in entries if e["contents"]), [])
    content_stacks = ", ".join(
        f"new MaterialRefStack(new MaterialRef({java_string_literal(ml_names[werkstoff_ref_name(c['name'], c['kind'], display_to_var)])}), {c['amount']}L)"
        for c in contents)

    byproducts = next((e["oreByProducts"] for e in entries if e["oreByProducts"]), [])
    byproduct_refs = ", ".join(
        f"new MaterialRef({java_string_literal(ml_names[display_to_var.get(b, b)])})" for b in byproducts)

    sub_tags = []
    additional_oredict = []
    for entry in entries:
        for tag in entry["subTags"]:
            if tag not in sub_tags:
                sub_tags.append(tag)
        for oredict in entry["additionalOredict"]:
            if oredict not in additional_oredict:
                additional_oredict.append(oredict)
    sub_tags_literal = "List.of(" + ", ".join(java_string_literal(t) for t in sub_tags) + ")"
    oredict_literal = "List.of(" + ", ".join(java_string_literal(o) for o in additional_oredict) + ")"

    formula = next((e["formula"] for e in entries if e["formula"]), "")

    return (
        ".setProperty(GTMaterialProperties.WERKSTOFF, new WerkstoffData("
        f"List.of({ids}), {java_string_literal(first['type'])}, {java_string_literal(first['pool'])}, "
        f"{first['meltingPoint']}, {first['boilingPoint']}, {first['protons']}L, {first['neutrons']}L, "
        f"{first['mass']}L, {first['meltingVoltage']}, {first['durability']}, "
        f"{java_float_literal(first['speed'])}, {first['quality']}, "
        f"{java_float_literal(first['durabilityModifier'])}, {first['enchantmentLevel']}, "
        f"{java_double_literal(first['ebfGasTimeMultiplier'])}, "
        f"{java_double_literal(first['ebfGasAmountMultiplier'])}, {first['mixCircuit']}, "
        f"{flags_literal}, {prefixes_literal}, List.of({content_stacks}), List.of({byproduct_refs}), "
        f"{sub_tags_literal}, {oredict_literal}, {java_string_literal(formula)}))")


# endregion


def load_legacy_variants_by_material(variants):
    """Ground-truth per-material shape membership: which prefixes `MetaGeneratedItemX32` actually built a
    legacy item for, keyed by legacy material name. Used instead of a material's dumped `generatedPrefixes`
    (capability bits alone), which can drift from construction-time truth -- see `MaterialDataDump`'s
    `dumpGeneratedPrefixes` javadoc for the MHDCSM/plateDouble example this fixes."""
    by_material = {}
    for v in variants:
        by_material.setdefault(v["material"], set()).add(v["prefix"])
    return by_material


def has_fluids(material):
    fluids = material["fluids"]
    return any(fluids.get(state) for state in FLUID_STATES)


def compute_referenced_names(materials):
    """Every material name any other dump entry points at via a MaterialRef-shaped field, so a marker
    material with no shapes/fluids/composition of its own is still ported when something needs to resolve it.
    Self-references (a material listing itself, e.g. in `oreByProducts`) are excluded -- they do not require
    the material to exist for anyone *else's* sake."""
    referenced = set()
    for material in materials:
        name = material["name"]
        for dump_key, _ in REF_PROPERTY_FIELDS:
            value = material.get(dump_key)
            if value and value != name:
                referenced.add(value)
        for stack in material["composition"]:
            if stack and stack.get("material") and stack["material"] != name:
                referenced.add(stack["material"])
        for byproduct in material["oreByProducts"]:
            if byproduct != name:
                referenced.add(byproduct)
    return referenced


def compute_ported(materials, werkstoff_referenced=(), werkstoff_names=()):
    """The gregtech dump entries that become MaterialLib declarations. Beyond stage 03's marker skip, a name
    backing a werkstoff (`werkstoff_names` -- its previously-skipped bridge mirror is revived) or referenced
    by werkstoff data (`werkstoff_referenced`) is always ported."""
    referenced = compute_referenced_names(materials) | set(werkstoff_referenced)
    forced = set(werkstoff_names)
    skipped = []
    ported = []
    for material in materials:
        is_marker = not material["generatedPrefixes"] and not has_fluids(material) and not material[
            "composition"]
        if is_marker and material["name"] not in referenced and material["name"] not in forced:
            skipped.append(material["name"])
        else:
            ported.append(material)
    return ported, skipped


def assign_names(ported):
    ml_names = {}
    field_names = {}
    ml_seen = {}
    field_seen = {}
    for material in ported:
        raw = material["name"]
        mn = ml_name(raw)
        fn = field_name(raw)
        if mn in ml_seen:
            raise SystemExit(
                f"gen_materials.py: MaterialLib name collision: {raw!r} and {ml_seen[mn]!r} both sanitize to "
                f"{mn!r}")
        if fn in field_seen:
            raise SystemExit(
                f"gen_materials.py: Java field name collision: {raw!r} and {field_seen[fn]!r} both sanitize "
                f"to {fn!r}")
        ml_seen[mn] = raw
        field_seen[fn] = raw
        ml_names[raw] = mn
        field_names[raw] = fn
    return ml_names, field_names


def joined_families(prefix_names, prefix_bits):
    bits = 0
    for prefix_name in prefix_names:
        bits |= prefix_bits.get(prefix_name, 0)
    return [family for family, bit in FAMILY_BITS if bits & bit]


def shape_delta(material, families, included_names, family_shape_members, legacy_variants_by_material,
                extra_item_prefixes):
    actual_variants = legacy_variants_by_material.get(material["name"], set())
    dumped_items = set(p for p in actual_variants if p in included_names)
    dumped_items |= set(p for p in extra_item_prefixes if p in included_names)
    implied = set()
    for family in families:
        implied.update(family_shape_members[family])
    missing = sorted(dumped_items - implied)
    excess = sorted(implied - dumped_items)
    return missing, excess


def material_ref_literal(raw_name, ml_names):
    return f"new MaterialRef({java_string_literal(ml_names[raw_name])})"


def material_ref_stack_list_literal(stacks, ml_names):
    entries = []
    for stack in stacks:
        if not stack or not stack.get("material"):
            continue
        entries.append(
            f"new MaterialRefStack({material_ref_literal(stack['material'], ml_names)}, {stack['amount']}L)")
    return "List.of(" + ", ".join(entries) + ")"


def material_ref_stack_list_from_names(names, ml_names):
    entries = [f"new MaterialRefStack({material_ref_literal(name, ml_names)}, 1L)" for name in names]
    return "List.of(" + ", ".join(entries) + ")"


def fluid_ref_literal(fluid, fluid_textures):
    if fluid is None:
        return "null"
    texture = fluid_textures.get(fluid["name"])
    texture_literal = java_string_literal(texture) if texture is not None else "null"
    return f"new FluidRef({java_string_literal(fluid['name'])}, {fluid['temperature']}, {texture_literal})"


def build_property_lines(material, ml_names, fluid_textures):
    lines = []

    local_name = material.get("localName")
    if local_name:
        lines.append(f".setProperty(GTMaterialProperties.LOCAL_NAME, {java_string_literal(local_name)})")

    true_name = material["name"]
    if ml_name(true_name) != true_name:
        lines.append(f".setProperty(GTMaterialProperties.LEGACY_NAME, {java_string_literal(true_name)})")

    lines.append(f".setProperty(GTMaterialProperties.ARGB, {java_int_literal(pack_argb_exact(material['rgba']))})")
    if material["moltenRgba"] != material["rgba"]:
        lines.append(
            ".setProperty(GTMaterialProperties.MOLTEN_ARGB, "
            f"{java_int_literal(pack_argb_exact(material['moltenRgba']))})")

    if material["meltingPoint"] != 0:
        lines.append(f".setProperty(GTMaterialProperties.MELTING_POINT, {material['meltingPoint']})")
    if material["blastTemp"] != 0:
        lines.append(f".setProperty(GTMaterialProperties.BLAST_TEMP, {material['blastTemp']})")
    if material["blastRequired"]:
        lines.append(".setProperty(GTMaterialProperties.BLAST_REQUIRED, true)")
    if material["gasTemp"] != 0:
        lines.append(f".setProperty(GTMaterialProperties.GAS_TEMP, {material['gasTemp']})")
    if material["fuelPower"] != 0:
        lines.append(f".setProperty(GTMaterialProperties.FUEL_POWER, {material['fuelPower']})")
    if material["fuelType"] != 0:
        lines.append(f".setProperty(GTMaterialProperties.FUEL_TYPE, {material['fuelType']})")
    if material["heatDamage"] != 0.0:
        lines.append(
            f".setProperty(GTMaterialProperties.HEAT_DAMAGE, {java_float_literal(material['heatDamage'])})")
    if material["toolSpeed"] != 1.0:
        lines.append(
            f".setProperty(GTMaterialProperties.TOOL_SPEED, {java_float_literal(material['toolSpeed'])})")
    if material["toolDurability"] != 0:
        lines.append(f".setProperty(GTMaterialProperties.DURABILITY, {material['toolDurability']})")
    if material["toolQuality"] != 0:
        lines.append(f".setProperty(GTMaterialProperties.TOOL_QUALITY, {material['toolQuality']})")
    if material["subId"] != -1:
        lines.append(f".setProperty(GTMaterialProperties.OLD_SUB_ID, {material['subId']})")

    if material["moltenRgba"] != [255, 255, 255, 0]:
        lines.append(
            f".setProperty(GTMaterialProperties.MOLTEN_TINT, {java_int_literal(pack_argb(material['moltenRgba']))})")

    if material["element"] is not None:
        lines.append(f".setProperty(GTMaterialProperties.ELEMENT, {java_string_literal(material['element'])})")

    if material["composition"]:
        lines.append(
            ".setProperty(GTMaterialProperties.COMPOSITION, "
            f"{material_ref_stack_list_literal(material['composition'], ml_names)})")

    for dump_key, property_name in REF_PROPERTY_FIELDS:
        value = material.get(dump_key)
        if value:
            lines.append(
                f".setProperty(GTMaterialProperties.{property_name}, {material_ref_literal(value, ml_names)})")

    if material["oreByProducts"]:
        lines.append(
            ".setProperty(GTMaterialProperties.ORE_BYPRODUCTS, "
            f"{material_ref_stack_list_from_names(material['oreByProducts'], ml_names)})")

    if material["subTags"]:
        flags = ", ".join(
            "GTMaterialFlag." + SUBTAG_FLAG_OVERRIDES.get(tag, tag) for tag in material["subTags"])
        lines.append(f".setProperty(GTMaterialProperties.FLAGS, EnumSet.of({flags}))")

    if material["oreMultiplier"] != 1:
        lines.append(f".setProperty(GTMaterialProperties.ORE_MULTIPLIER, {material['oreMultiplier']})")
    if material["byProductMultiplier"] != 1:
        lines.append(
            f".setProperty(GTMaterialProperties.BYPRODUCT_MULTIPLIER, {material['byProductMultiplier']})")
    if material["smeltingMultiplier"] != 1:
        lines.append(
            f".setProperty(GTMaterialProperties.SMELTING_MULTIPLIER, {material['smeltingMultiplier']})")

    if not material["unifiable"]:
        lines.append(".setProperty(GTMaterialProperties.UNIFIABLE, false)")
    if material["densityMultiplier"] != 1:
        lines.append(f".setProperty(GTMaterialProperties.DENSITY_MULTIPLIER, {material['densityMultiplier']})")
    if material["densityDivider"] != 1:
        lines.append(f".setProperty(GTMaterialProperties.DENSITY_DIVIDER, {material['densityDivider']})")
    if material["steamMultiplier"] != 1.0:
        lines.append(
            f".setProperty(GTMaterialProperties.STEAM_MULTIPLIER, {java_float_literal(material['steamMultiplier'])})")
    if material["gasMultiplier"] != 1.0:
        lines.append(
            f".setProperty(GTMaterialProperties.GAS_MULTIPLIER, {java_float_literal(material['gasMultiplier'])})")
    if material["plasmaMultiplier"] != 1.0:
        lines.append(
            ".setProperty(GTMaterialProperties.PLASMA_MULTIPLIER, "
            f"{java_float_literal(material['plasmaMultiplier'])})")

    if material["generationFlags"]:
        gen_flags = ", ".join("GTMaterialGenerationFlag." + f for f in material["generationFlags"])
        lines.append(f".setProperty(GTMaterialProperties.GENERATION_FLAGS, EnumSet.of({gen_flags}))")

    has_fluid, has_gas = CORRESPONDING_FLAG_OVERRIDES.get(
        material["name"], (material["hasCorrespondingFluid"], material["hasCorrespondingGas"]))
    if has_fluid:
        lines.append(".setProperty(GTMaterialProperties.HAS_CORRESPONDING_FLUID, true)")
    if has_gas:
        lines.append(".setProperty(GTMaterialProperties.HAS_CORRESPONDING_GAS, true)")
    if material["hasElectrolyzerRecipe"]:
        lines.append(".setProperty(GTMaterialProperties.HAS_ELECTROLYZER_RECIPE, true)")
    if material["hasCentrifugeRecipe"]:
        lines.append(".setProperty(GTMaterialProperties.HAS_CENTRIFUGE_RECIPE, true)")
    if material["canBeCracked"]:
        lines.append(".setProperty(GTMaterialProperties.CAN_BE_CRACKED, true)")
    if material["hasGlowingOre"]:
        lines.append(".setProperty(GTMaterialProperties.HAS_GLOWING_ORE, true)")
    if material["processingMaterialTierEU"] != 0:
        lines.append(
            ".setProperty(GTMaterialProperties.PROCESSING_MATERIAL_TIER_EU, "
            f"{material['processingMaterialTierEU']})")

    if material["addedPrefixes"]:
        added = ", ".join(java_string_literal(p) for p in material["addedPrefixes"])
        lines.append(f".setProperty(GTMaterialProperties.ADDED_PREFIXES, List.of({added}))")
    if material["removedPrefixes"]:
        removed = ", ".join(java_string_literal(p) for p in material["removedPrefixes"])
        lines.append(f".setProperty(GTMaterialProperties.REMOVED_PREFIXES, List.of({removed}))")

    if material.get("color"):
        lines.append(f".setProperty(GTMaterialProperties.DYE, {java_string_literal(material['color'])})")
    if not material["autoBlast"]:
        lines.append(".setProperty(GTMaterialProperties.AUTO_BLAST_FURNACE_RECIPES, false)")
    if not material["autoVacuum"]:
        lines.append(".setProperty(GTMaterialProperties.AUTO_VACUUM_FREEZER_RECIPES, false)")
    if not material["autoRecycle"]:
        lines.append(".setProperty(GTMaterialProperties.AUTO_RECYCLE_RECIPES, false)")

    tool_enchant = material["enchants"].get("tool")
    if tool_enchant:
        lines.append(
            f".setProperty(GTMaterialProperties.TOOL_ENCHANTMENT, {java_string_literal(tool_enchant['name'])})")
        lines.append(f".setProperty(GTMaterialProperties.TOOL_ENCHANTMENT_LEVEL, {tool_enchant['level']})")
    armor_enchant = material["enchants"].get("armor")
    if armor_enchant:
        lines.append(
            f".setProperty(GTMaterialProperties.ARMOR_ENCHANTMENT, {java_string_literal(armor_enchant['name'])})")
        lines.append(f".setProperty(GTMaterialProperties.ARMOR_ENCHANTMENT_LEVEL, {armor_enchant['level']})")

    if material["aspects"]:
        aspect_entries = ", ".join(
            f"new AspectRefStack({java_string_literal(a['name'])}, {a['amount']})" for a in material["aspects"])
        lines.append(f".setProperty(GTMaterialProperties.ASPECTS, List.of({aspect_entries}))")

    fluids = material["fluids"]
    if has_fluids(material) and material["name"] not in FLUID_CUTOVER_EXCLUDED:
        fluid_args = ", ".join(fluid_ref_literal(fluids[state], fluid_textures) for state in FLUID_STATES)
        lines.append(f".setProperty(GTMaterialProperties.LEGACY_FLUIDS, new FluidNames({fluid_args}))")

    cracked = material.get("crackedFluids") or {}
    hydro_cracked = cracked.get("hydroCracked")
    if hydro_cracked:
        entries = ", ".join(fluid_ref_literal(f, fluid_textures) for f in hydro_cracked)
        lines.append(f".setProperty(GTMaterialProperties.CRACKED_HYDRO_FLUIDS, List.of({entries}))")
    steam_cracked = cracked.get("steamCracked")
    if steam_cracked:
        entries = ", ".join(fluid_ref_literal(f, fluid_textures) for f in steam_cracked)
        lines.append(f".setProperty(GTMaterialProperties.CRACKED_STEAM_FLUIDS, List.of({entries}))")

    return lines


# Materials whose fluid is hand-wired in LoaderGTBlockFluid rather than produced by the generic per-material
# GTFluidFactory pipeline this stage cuts over. Water/Ice: mFluid is vanilla "water" for both, mSolid is a
# single "ice" fluid shared by both (Materials.Water.mSolid = Materials.Ice.mSolid), and mGas is Water's steam
# shared the same way -- claiming a MaterialLib fluid shape for both would double-register the identical name,
# which MaterialLib rejects (fluid names must be unique per resolve, reused or not). Lava: vanilla "lava".
# ConstructionFoam/UUMatter: an IC2 item's fluid looked up via GTUtility#getFluidForFilledItem, owned by IC2's
# own registration. All five are left as legacy exactly as before; claiming their shapes would only produce a
# harmless "already registered elsewhere" MaterialLib warning, but stage 06 targets a clean resolve.
FLUID_CUTOVER_EXCLUDED = {"Water", "Ice", "Lava", "ConstructionFoam", "UUMatter"}

# dump fluid-slot key -> Materials2FluidShapes field.
FLUID_SHAPE_FIELDS = {
    "solid": "shapeFluidSolid",
    "fluid": "shapeFluidLiquid",
    "gas": "shapeFluidGas",
    "plasma": "shapeFluidPlasma",
    "molten": "shapeFluidMolten",
}
CRACKED_FLUID_SHAPE_FIELDS = {
    "hydroCracked": ["shapeFluidHydroCracked1", "shapeFluidHydroCracked2", "shapeFluidHydroCracked3"],
    "steamCracked": ["shapeFluidSteamCracked1", "shapeFluidSteamCracked2", "shapeFluidSteamCracked3"],
}
# legacy-variants.json prefix -> (Materials2CellShapes field, dump key whose presence the shape's fluid
# requires -- MaterialLib's container contract needs a material to generate at least one of the container's
# fluid shapes too, which not every material with a real legacy item slot satisfies (e.g. a metal's plain
# `cell` slot exists from its CELL capability flag alone, with no base liquid/gas ever put in it; its molten
# and plasma go into cellMolten/cellPlasma instead). Missing the required fluid leaves the legacy item
# uncut -- see MU#isCutOver.
CELL_SHAPE_FIELDS = {
    "cellHydroCracked1": ("shapeCellHydroCracked1", "hydroCracked"),
    "cellHydroCracked2": ("shapeCellHydroCracked2", "hydroCracked"),
    "cellHydroCracked3": ("shapeCellHydroCracked3", "hydroCracked"),
    "cellSteamCracked1": ("shapeCellSteamCracked1", "steamCracked"),
    "cellSteamCracked2": ("shapeCellSteamCracked2", "steamCracked"),
    "cellSteamCracked3": ("shapeCellSteamCracked3", "steamCracked"),
}

LEGACY_BLOCKS_DUMP_PATH = SCRIPT_DIR / "dumps" / "legacy-blocks.json"

# Materials whose legacy storage block is hard-referenced by identity (`GregTechAPI.sBlockMetalN == ...`) from
# multiblock casing matchers, a machine-block-update listener, or a client-side piston-tier icon fallback,
# rather than through GTOreDictUnificator -- see stage-07's structural-reference sweep. Cutting these over would
# leave the referencing code comparing against a Block no consumer still points at (the legacy BlockMetal
# instance stays registered and playable for every material, cut over or not -- see gen_materials.py's
# `block_shape_lines` javadoc -- but only the canonical oredict association moves for cut-over materials, and
# these call sites bypass the oredict entirely). Steel/Osmiridium/Neutronium/NaquadahAlloy/WhiteDwarfMatter/
# BlackDwarfMatter/MagnetohydrodynamicallyConstrainedStarMatter: MTESteamForgeHammer, MTESteamCompressor,
# MTEExoFoundry, MTESpinmatron casing tiers. SpaceTime/TranscendentMetal/Universium/Neutronium:
# MTEElectricImplosionCompressor(Legacy) piston tiers, bartworks ItemRegistry's registerMachineBlock
# machine-block-update listener, EICPistonVisualizer's client-side icon fallback. Copper/Zinc:
# MTEIndustrialChemicalBath casing. Osmiridium alone: MTEMicrowaveEnergyTransmitter's teleport-unlock world
# scan.
BLOCK_CUTOVER_EXCLUDED = {
    "Steel", "Osmiridium", "Neutronium", "NaquadahAlloy", "WhiteDwarfMatter", "BlackDwarfMatter",
    "MagnetohydrodynamicallyConstrainedStarMatter", "SpaceTime", "TranscendentMetal", "Universium", "Copper",
    "Zinc"
}


def load_legacy_block_materials():
    """Every material name with a real legacy storage-block slot (union of the 13 `BlockMetal` instances'
    `Materials[]` arrays), from `legacy-blocks.json` -- see `MaterialDataDump#dumpLegacyBlocks`."""
    if not LEGACY_BLOCKS_DUMP_PATH.exists():
        return set()
    with open(LEGACY_BLOCKS_DUMP_PATH, encoding="utf-8") as f:
        entries = json.load(f)
    return {e["material"] for e in entries}


def block_shape_lines(material, legacy_block_materials):
    """`generateShape(...)` line for `Materials2BlockShapes`, driven by `legacy-blocks.json` ground truth (see
    `load_legacy_block_materials`) rather than the family/delta machinery every other item shape uses: `block`'s
    dumped `generationBits` is `0` (see `gen_shapes.py`'s `is_block_kind`), so it never appears in any
    material's `generatedPrefixes` and cannot participate in that pipeline at all. `BLOCK_CUTOVER_EXCLUDED`
    materials keep their legacy storage block canonical despite having a real legacy slot -- see its
    docstring."""
    if material["name"] not in legacy_block_materials or material["name"] in BLOCK_CUTOVER_EXCLUDED:
        return []
    return ["            .generateShape(Materials2BlockShapes.shapeBlock)"]


def fluid_shape_lines(material, used_fluid_names):
    """`generateShape(...)` lines for `Materials2FluidShapes`, driven directly by which legacy fluid slots the
    dump captured (mSolid/mFluid/mGas/mPlasma/mStandardMoltenFluid, hydro/steam-cracked arrays) -- these are
    live Forge fluid object references, not capability bits, so unlike item shapes there is no drift to guard
    against with a legacy-variants intersection.

    A material only claims (generates) a shape for a name not already claimed this run: MaterialLib requires
    every fluid name unique across the whole resolve, but a large fraction of materials legitimately reuse one
    Forge fluid across two slots -- `GTFluidFactory` names both a material's `fluid` and `gas` fluid
    `aMaterial.mName.toLowerCase()`, so whichever `addAutoGeneratedCorresponding*` ran first (fluid before gas,
    see `GTProxy`) created it and the other silently reused it, leaving `mFluid`/`mGas` pointing at the exact
    same object. Processing states in `FLUID_SHAPE_FIELDS`/`CRACKED_FLUID_SHAPE_FIELDS` order and skipping an
    already-claimed name reproduces that first-claim-wins order; the skipped state's material still resolves
    correctly via `LegacyMaterials#wireFluids`, which looks the fluid up by name rather than requiring the
    material to be this shape's own generator."""
    if material["name"] in FLUID_CUTOVER_EXCLUDED:
        return []
    lines = []
    fluids = material["fluids"]
    for state, field in FLUID_SHAPE_FIELDS.items():
        ref = fluids.get(state)
        if ref and ref["name"] not in used_fluid_names:
            used_fluid_names.add(ref["name"])
            lines.append(f"            .generateShape(Materials2FluidShapes.{field})")
    cracked = material.get("crackedFluids") or {}
    for key, shape_fields in CRACKED_FLUID_SHAPE_FIELDS.items():
        refs = cracked.get(key)
        if not refs:
            continue
        for ref, field in zip(refs, shape_fields):
            if ref and ref["name"] not in used_fluid_names:
                used_fluid_names.add(ref["name"])
                lines.append(f"            .generateShape(Materials2FluidShapes.{field})")
    return lines


def container_shape_lines(material, legacy_variants_by_material):
    """`generateShape(...)` lines for `Materials2CellShapes`, driven by legacy-variants.json (the same ground
    truth item shapes use): `cellMolten`/cracked-cell prefixes live on `MetaGeneratedItem99`, which is not a
    `MetaGeneratedItemX32` subclass and so needed its own legacy-variants capture (see that class). `cellPlasma`
    picks one of two candidate shapes per material depending on whether it also has a molten fluid (see
    `Materials2CellShapes`). A material's legacy variant only becomes a MaterialLib shape when the fluid it
    requires is also present (see `CELL_SHAPE_FIELDS`); materials that fall short keep their legacy item."""
    if material["name"] in FLUID_CUTOVER_EXCLUDED:
        return []
    variants = legacy_variants_by_material.get(material["name"], set())
    fluids = material["fluids"]
    cracked = material.get("crackedFluids") or {}
    lines = []
    if "cell" in variants and (fluids.get("fluid") or fluids.get("gas")):
        lines.append("            .generateShape(Materials2CellShapes.shapeCell)")
    if "cellMolten" in variants and fluids.get("molten"):
        lines.append("            .generateShape(Materials2CellShapes.shapeCellMolten)")
    if "cellPlasma" in variants and fluids.get("plasma"):
        field = "shapeCellPlasma" if fluids.get("molten") else "shapeCellPlasmaLight"
        lines.append(f"            .generateShape(Materials2CellShapes.{field})")
    for prefix_name, (field, cracked_key) in CELL_SHAPE_FIELDS.items():
        if prefix_name in variants and cracked.get(cracked_key):
            lines.append(f"            .generateShape(Materials2CellShapes.{field})")
    return lines


def ore_shape_lines(material):
    """`generateShape(...)` lines for `Materials2OreShapes`, driven directly by the dumped `generatedPrefixes`
    ground truth: `ore`/`oreSmall` are block-kind (see `gen_shapes.py`'s `is_block_kind`), so unlike every other
    prefix carrying the `ORE` generation bit they never appear in `Materials2Shapes`'s per-item pipeline
    (`is_included_shape` excludes block-kind prefixes outright) and so need their own hand-written membership
    line here, the same way `block_shape_lines`/`container_shape_lines` do for their own block-kind/container
    shapes."""
    prefixes = material["generatedPrefixes"]
    lines = []
    if "ore" in prefixes:
        lines.append("            .generateShape(Materials2OreShapes.shapeOre)")
    if "oreSmall" in prefixes:
        lines.append("            .generateShape(Materials2OreShapes.shapeOreSmall)")
    return lines


def werkstoff_special_shape_lines(material, werkstoff_prefixes):
    """`generateShape(...)` lines for the werkstoff prefixes outside `Materials2Shapes`' per-item pipeline:
    cells (fluid-in-container, the fluid itself is already MaterialLib-owned via the bridge mirror's
    `LEGACY_FLUIDS` capture), storage blocks, ores (bartworks small ores exist for every ore werkstoff --
    `BWOreAdapter` registers big+small blocks per stone type -- so `ore` implies `oreSmall` here), and the
    bartworks casings. `WERKSTOFF_LEGACY_ONLY_PREFIXES` deliberately produce nothing."""
    name = material["name"]
    fluids = material["fluids"]
    lines = []
    if "cell" in werkstoff_prefixes:
        if not (fluids.get("fluid") or fluids.get("gas")):
            raise SystemExit(f"gen_materials.py: werkstoff {name!r} generates cell but has no dumped fluid")
        lines.append("            .generateShape(Materials2CellShapes.shapeCell)")
    if "cellMolten" in werkstoff_prefixes:
        if not fluids.get("molten"):
            raise SystemExit(
                f"gen_materials.py: werkstoff {name!r} generates cellMolten but has no dumped molten fluid")
        lines.append("            .generateShape(Materials2CellShapes.shapeCellMolten)")
    if "block" in werkstoff_prefixes:
        lines.append("            .generateShape(Materials2BlockShapes.shapeBlock)")
    if "ore" in werkstoff_prefixes:
        lines.append("            .generateShape(Materials2OreShapes.shapeOre)")
        lines.append("            .generateShape(Materials2OreShapes.shapeOreSmall)")
    if "blockCasing" in werkstoff_prefixes:
        lines.append("            .generateShape(Materials2BlockShapes.shapeBlockCasing)")
    if "blockCasingAdvanced" in werkstoff_prefixes:
        lines.append("            .generateShape(Materials2BlockShapes.shapeBlockCasingAdvanced)")
    return lines


def build_material_block(
        material, families, ml_names, field_names, included_names, family_shape_members,
        legacy_variants_by_material, used_fluid_names, fluid_textures, legacy_block_materials,
        werkstoff_info, display_to_var):
    field = field_names[material["name"]]
    name_literal = java_string_literal(ml_names[material["name"]])
    icon_set_literal = java_string_literal(material["iconSet"])
    werkstoff_prefixes = werkstoff_info["prefixes"] if werkstoff_info else []

    lines = []
    lines.append(
        f"        Materials2Materials.{field} = MaterialLibAPI"
        f".newMaterial(\"gregtech\", {name_literal}, TextureSet.of(\"gregtech\", {icon_set_literal}))")
    lines.append(f"            .setTint({java_int_literal(pack_argb(material['rgba']))})")
    lines.append("            .addToFamily(Materials2Families.familyAll)")
    for family in families:
        lines.append(f"            .addToFamily(Materials2Families.{family})")

    missing, excess = shape_delta(
        material, families, included_names, family_shape_members, legacy_variants_by_material,
        werkstoff_prefixes)
    for prefix_name in missing:
        lines.append(f"            .generateShape(Materials2Shapes.{shape_field_name(prefix_name)})")
    shape_lines = []
    shape_lines.extend(fluid_shape_lines(material, used_fluid_names))
    shape_lines.extend(container_shape_lines(material, legacy_variants_by_material))
    shape_lines.extend(block_shape_lines(material, legacy_block_materials))
    shape_lines.extend(ore_shape_lines(material))
    shape_lines.extend(werkstoff_special_shape_lines(material, werkstoff_prefixes))
    seen_shape_lines = set()
    for line in shape_lines:
        if line not in seen_shape_lines:
            seen_shape_lines.add(line)
            lines.append(line)

    for property_line in build_property_lines(material, ml_names, fluid_textures):
        lines.append("            " + property_line)
    if werkstoff_info:
        werkstoff_line = werkstoff_property_line(werkstoff_info, ml_names, display_to_var)
        if werkstoff_line:
            lines.append("            " + werkstoff_line)

    lines.append("            .build();")

    if excess:
        lines.append(f"        MaterialLibAPI.editMaterial(\"gregtech\", {name_literal})")
        for prefix_name in excess:
            lines.append(f"            .removeShape(Materials2Shapes.{shape_field_name(prefix_name)})")
        lines[-1] += ";"

    return lines


def chunk(items, size):
    for i in range(0, len(items), size):
        yield items[i:i + size]


def write_data_file(index, materials, families_by_name, ml_names, field_names, included_names,
                     family_shape_members, legacy_variants_by_material, used_fluid_names, fluid_textures,
                     legacy_block_materials, werkstoff_by_name, display_to_var):
    class_name = f"Materials2Data{index}"
    lines = []
    lines.append("package gregtech.api.enums.materials2;")
    lines.append("")
    lines.append("import java.util.EnumSet;")
    lines.append("import java.util.List;")
    lines.append("")
    lines.append("import com.ruling_0.materiallib.api.MaterialLibAPI;")
    lines.append("import com.ruling_0.materiallib.api.TextureSet;")
    lines.append("")
    lines.append("import gregtech.api.material.AspectRefStack;")
    lines.append("import gregtech.api.material.FluidNames;")
    lines.append("import gregtech.api.material.FluidRef;")
    lines.append("import gregtech.api.material.GTMaterialFlag;")
    lines.append("import gregtech.api.material.GTMaterialGenerationFlag;")
    lines.append("import gregtech.api.material.GTMaterialProperties;")
    lines.append("import gregtech.api.material.GTWerkstoffFlag;")
    lines.append("import gregtech.api.material.MaterialRef;")
    lines.append("import gregtech.api.material.MaterialRefStack;")
    lines.append("import gregtech.api.material.WerkstoffData;")
    lines.append("")
    first = (index - 1) * MATERIALS_PER_FILE + 1
    last = (index - 1) * MATERIALS_PER_FILE + len(materials)
    lines.append(GENERATED_HEADER)
    lines.append(f"/// Material declarations {first}..{last}, see [Materials2Materials].")
    lines.append(f"public class {class_name} {{")
    lines.append("")
    lines.append("    public static void init() {")
    lines.append("        // spotless:off")
    for material in materials:
        families = families_by_name[material["name"]]
        lines.extend(
            build_material_block(
                material, families, ml_names, field_names, included_names, family_shape_members,
                legacy_variants_by_material, used_fluid_names, fluid_textures, legacy_block_materials,
                werkstoff_by_name.get(material["name"]), display_to_var))
    lines.append("        // spotless:on")
    lines.append("    }")
    lines.append("")
    lines.append(f"    private {class_name}() {{}}")
    lines.append("}")
    lines.append("")

    output_path = MATERIALS2_DIR / f"{class_name}.java"
    output_path.write_text("\n".join(lines), encoding="utf-8")
    return class_name


def write_materials_file(ported, field_names, data_class_names):
    lines = []
    lines.append("package gregtech.api.enums.materials2;")
    lines.append("")
    lines.append("import com.ruling_0.materiallib.api.Material;")
    lines.append("")
    lines.append(GENERATED_HEADER)
    lines.append("/// One [Material] field per ported GregTech material, named after the legacy `Materials`")
    lines.append(
        "/// field where the dump's material name is already a valid Java identifier, else a sanitized")
    lines.append("/// variant (see `scripts/mu/gen_materials.py`).")
    lines.append("public class Materials2Materials {")
    lines.append("")
    lines.append("    // spotless:off")
    for material in ported:
        lines.append(f"    public static Material {field_names[material['name']]};")
    lines.append("    // spotless:on")
    lines.append("")
    lines.append("    public static void init() {")
    for class_name in data_class_names:
        lines.append(f"        {class_name}.init();")
    lines.append("    }")
    lines.append("")
    lines.append("    private Materials2Materials() {}")
    lines.append("}")
    lines.append("")
    MATERIALS_OUTPUT.write_text("\n".join(lines), encoding="utf-8")


# region legacy bridge (stage 04)

LEGACY_ASSIGN_RE = re.compile(r"Materials\.(\w+) = (\w+)\(\);")
# Two legacy fields sharing one instance, e.g. `Materials.Water = Materials.Steam = loadWater();` (Water/Steam,
# WroughtIron/CastIron) -- both fields need the same ml-name mapping.
LEGACY_CHAINED_ASSIGN_RE = re.compile(r"Materials\.(\w+) = Materials\.(\w+) = (\w+)\(\);")
LEGACY_METHOD_RE = re.compile(r"private static Materials (\w+)\(\) \{(.*?)\n    \}", re.S)
LEGACY_SETNAME_RE = re.compile(r'setName\(\s*"((?:[^"\\]|\\.)*)"')


def load_legacy_field_names():
    """Maps every legacy `Materials` static field name assigned by `MaterialsInit.load()` to the `mName`
    passed to that material's `setName(...)` call, so the ml-name-keyed ported set can be matched back to the
    Java field it must be assigned to. Only meaningful while `MaterialsInit.java` still existed; the
    MaterialsLegacyBridge/LegacyMaterials split it drove was a one-time port, so once stage 04 deleted that
    file the committed bridge is left untouched (see `write_legacy_bridge_file`)."""
    text = LEGACY_MATERIALS_INIT.read_text(encoding="utf-8")
    method_bodies = {m.group(1): m.group(2) for m in LEGACY_METHOD_RE.finditer(text)}

    assigns = list(LEGACY_ASSIGN_RE.findall(text))
    for first_field, second_field, method in LEGACY_CHAINED_ASSIGN_RE.findall(text):
        assigns.append((first_field, method))
        assigns.append((second_field, method))

    field_to_mname = {}
    for field, method in assigns:
        body = method_bodies.get(method)
        if body is None:
            raise SystemExit(f"gen_materials.py: no method body found for {method}() (field {field})")
        sm = LEGACY_SETNAME_RE.search(body)
        if not sm:
            raise SystemExit(f"gen_materials.py: no setName(...) found in {method}() (field {field})")
        field_to_mname[field] = sm.group(1)
    return field_to_mname


def order_by_composition(bridge_fields, materials_by_name, field_to_mname, field_names):
    """`MaterialBuilder#addMaterial` adds directly to the legacy `Materials.mMaterialList`, unlike the
    ore-byproduct/smelt-into-style links, which resolve lazily through a `Supplier`. A material's composition
    inputs must therefore already be built (and sitting in `Materials.getMaterialsMap()`) before it is built
    itself, or `Materials.get(...)` silently returns `Materials._NULL` for a forward reference. Topologically
    sorts `bridge_fields` by composition dependency (Kahn's algorithm); ties broken by the existing (field
    name) order for a stable, readable diff. Returns a list of `(fields, ml_field)` pairs, in dependency
    order; `fields` has more than one entry for an mname two legacy fields share (`Water`/`Steam`,
    `WroughtIron`/`CastIron`)."""
    mname_by_field = {f: field_to_mname[f] for f, _ in bridge_fields}
    bridge_mnames = set(mname_by_field.values())

    depends_on = {mname: [] for mname in bridge_mnames}
    for mname in bridge_mnames:
        for stack in materials_by_name[mname]["composition"]:
            dep = stack.get("material") if stack else None
            if dep and dep != mname and dep in bridge_mnames:
                depends_on[mname].append(dep)

    order_index = {field: i for i, (field, _) in enumerate(bridge_fields)}
    # A single MaterialLib material can back more than one legacy field (e.g. `Water`/`Steam` and
    # `WroughtIron`/`CastIron`, both `Materials.A = Materials.B = loadX();` in MaterialsInit) -- every field
    # sharing an mname must be emitted, in their original relative order.
    fields_by_mname = {}
    for field, mname in mname_by_field.items():
        fields_by_mname.setdefault(mname, []).append(field)
    for fields in fields_by_mname.values():
        fields.sort(key=lambda f: order_index[f])
    representative_field = {mname: fields[0] for mname, fields in fields_by_mname.items()}

    visited = set()
    in_progress = set()
    ordered_mnames = []

    def visit(mname):
        if mname in visited:
            return
        if mname in in_progress:
            raise SystemExit(f"gen_materials.py: composition dependency cycle involving {mname!r}")
        in_progress.add(mname)
        for dep in sorted(depends_on[mname], key=lambda d: order_index[representative_field[d]]):
            visit(dep)
        in_progress.discard(mname)
        visited.add(mname)
        ordered_mnames.append(mname)

    for _, mname in sorted(mname_by_field.items(), key=lambda kv: order_index[kv[0]]):
        visit(mname)

    return [(fields_by_mname[mname], field_names[mname]) for mname in ordered_mnames]


def write_legacy_bridge_file(ported_names, field_names, materials_by_name):
    if not LEGACY_MATERIALS_INIT.exists():
        print(
            "gen_materials.py: MaterialsInit.java no longer exists (deleted by stage 04); leaving the "
            "committed MaterialsLegacyBridge.java untouched")
        return None, None

    field_to_mname = load_legacy_field_names()

    bridge_fields = []
    retained_fields = []
    for legacy_field, mname in sorted(field_to_mname.items()):
        if mname in ported_names:
            bridge_fields.append((legacy_field, mname))
        else:
            retained_fields.append(legacy_field)

    groups = order_by_composition(bridge_fields, materials_by_name, field_to_mname, field_names)

    lines = []
    lines.append("package gregtech.loaders.materials;")
    lines.append("")
    lines.append("import gregtech.api.enums.Materials;")
    lines.append("import gregtech.api.enums.materials2.Materials2Materials;")
    lines.append("")
    lines.append(GENERATED_HEADER)
    lines.append("/// Rebuilds every MaterialLib-backed legacy `Materials` field from the stage-03 port, via")
    lines.append("/// [LegacyMaterials#build]. [LegacyMarkerMaterials#loadMarkers] separately rebuilds the legacy")
    lines.append("/// fields that carry no MaterialLib data (never generated an item/fluid/composition and are")
    lines.append("/// unreferenced by a ported material).")
    lines.append("public class MaterialsLegacyBridge {")
    lines.append("")
    lines.append("    public static void load() {")
    lines.append("        LegacyMarkerMaterials.loadMarkers();")
    lines.append("        // A bare JUnit run never fires MaterialLib's MaterialRegistrationEvent, so")
    lines.append("        // Materials2Materials fields stay null outside a real FML mod-loading lifecycle.")
    lines.append("        // Fall back to named stubs rather than NPE-ing Materials' static initializer")
    lines.append("        // (which would poison every test class referencing it); stubs match what bare")
    lines.append("        // JUnit saw under MaterialsInit closely enough (fluids were always null there")
    lines.append("        // too -- they only register during a real preInit).")
    lines.append("        if (Materials2Materials.Iron == null) {")
    lines.append("            loadStubs();")
    lines.append("            return;")
    lines.append("        }")
    lines.append("        // spotless:off")
    bridge_count = 0
    for fields, ml_field in groups:
        primary, *aliases = fields
        bridge_count += len(fields)
        lines.append(
            f"        Materials.{primary} = LegacyMaterials.build(Materials2Materials.{ml_field});")
        for alias in aliases:
            lines.append(f"        Materials.{alias} = Materials.{primary};")
    lines.append("        // spotless:on")
    lines.append("    }")
    lines.append("")
    lines.append("    private static void loadStubs() {")
    lines.append("        // spotless:off")
    for fields, _ in groups:
        primary, *aliases = fields
        mname = field_to_mname[primary]
        lines.append(f"        Materials.{primary} = LegacyMaterials.stub({java_string_literal(mname)});")
        for alias in aliases:
            lines.append(f"        Materials.{alias} = Materials.{primary};")
    lines.append("        // spotless:on")
    lines.append("    }")
    lines.append("")
    lines.append("    private MaterialsLegacyBridge() {}")
    lines.append("}")
    lines.append("")
    LEGACY_BRIDGE_OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    return bridge_count, retained_fields


# endregion

def werkstoff_contested_values(gt, entry):
    """The scalar values the gregtech dump won over the pool declaration -- listed per fold in the merge
    report so a merge of two genuinely different substances (rather than the bridge mirror of the same one)
    is reviewable rather than silent."""
    contested = []

    def contest(label, gt_value, w_value):
        if gt_value != w_value:
            contested.append(f"{label} gt={gt_value!r} werkstoff={w_value!r}")

    contest("localName", gt["localName"], entry["name"])
    contest("rgb", gt["rgba"][:3], entry["rgb"])
    contest("textureSet", gt["iconSet"], entry["texSet"])
    contest("meltingPoint", gt["meltingPoint"], entry["meltingPoint"])
    contest("blastRequired", bool(gt["blastRequired"]), bool(entry["blastFurnace"]))
    if entry["durability"]:
        contest("toolDurability", gt["toolDurability"], entry["durability"])
    if entry["speed"]:
        contest("toolSpeed", gt["toolSpeed"], entry["speed"])
    if entry["quality"]:
        contest("toolQuality", gt["toolQuality"], entry["quality"])
    return contested


def write_merge_report(werkstoff_by_name, gt_by_name, base_ported_names, ported_names):
    lines = []
    lines.append("Werkstoff merge report -- generated by scripts/mu/gen_materials.py; regenerate, do not edit.")
    lines.append("")
    entry_count = sum(len(info["entries"]) for info in werkstoff_by_name.values())
    named = [n for n, info in werkstoff_by_name.items() if info["entries"]]
    proxy_only = [n for n, info in werkstoff_by_name.items() if not info["entries"]]
    merged = sorted(n for n in named if n in base_ported_names)
    revived = sorted(n for n in named if n not in base_ported_names)
    newly_referenced = sorted(ported_names - base_ported_names - set(named))
    lines.append(
        f"{entry_count} pool entries folded onto {len(named)} gregtech declarations "
        f"({len(merged)} merged with stage-03 ported materials, {len(revived)} revived previously-skipped "
        f"bridge mirrors); proxy shape folds onto {len(proxy_only)} gregtech materials "
        f"({', '.join(sorted(proxy_only))}); {len(newly_referenced)} markers newly ported because werkstoff "
        f"data references them ({', '.join(newly_referenced)}).")
    lines.append("")
    for name in sorted(named):
        info = werkstoff_by_name[name]
        entries = info["entries"]
        gt = gt_by_name[name]
        pools = sorted({e["pool"] for e in entries})
        ids = ", ".join(str(e["id"]) for e in entries)
        status = "merged-with-ported" if name in base_ported_names else "revived-mirror"
        lines.append(f"== {name} (pools: {', '.join(pools)}; ids: {ids}; {status})")
        lines.append(f"   shapes: {', '.join(info['prefixes'])}")
        contested = werkstoff_contested_values(gt, entries[0])
        if contested:
            lines.append(f"   contested (gregtech dump won): {'; '.join(contested)}")
        if len(entries) > 1:
            details = "; ".join(
                f"id {e['id']} type={e['type']} prefixes={','.join(e['generatedPrefixes'])}" for e in entries)
            lines.append(f"   intra-pool fold of {len(entries)} same-name werkstoffe: {details}")
    lines.append("")
    MERGE_REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(merged), len(revived), newly_referenced


LANG_BEGIN = "# --- BEGIN GENERATED MATERIAL NAMES (scripts/mu/gen_materials.py) ---"
LANG_END = "# --- END GENERATED MATERIAL NAMES ---"


def write_lang_file(ported, ml_names):
    entries = sorted(
        (ml_names[material["name"]], material["localName"]) for material in ported if material["localName"])
    block_lines = [LANG_BEGIN]
    for name, local_name in entries:
        block_lines.append(f"material.gregtech.{name}={local_name}")
    block_lines.append(LANG_END)
    block = "\n".join(block_lines)

    if LANG_OUTPUT.exists():
        text = LANG_OUTPUT.read_text(encoding="utf-8")
        if LANG_BEGIN in text and LANG_END in text:
            before = text[:text.index(LANG_BEGIN)]
            after = text[text.index(LANG_END) + len(LANG_END):]
            text = before.rstrip("\n") + "\n\n" + block + after
        else:
            text = text.rstrip("\n") + "\n\n" + block + "\n"
    else:
        text = block + "\n"
    LANG_OUTPUT.write_text(text, encoding="utf-8")


def main():
    materials = load_materials()
    prefixes = load_prefixes()
    legacy_variants = load_legacy_variants()
    legacy_variant_prefixes = load_legacy_variant_prefixes(legacy_variants)
    legacy_variants_by_material = load_legacy_variants_by_material(legacy_variants)
    fluid_textures = load_fluid_textures()
    legacy_block_materials = load_legacy_block_materials()
    werkstoffs = load_werkstoffs()

    prefix_bits = {p["name"]: p["generationBits"] for p in prefixes}
    included_prefixes = [p for p in prefixes if is_included_shape(p, legacy_variant_prefixes)]
    included_names = set(p["name"] for p in included_prefixes)

    family_shape_members = {family: [] for family, _ in FAMILY_BITS}
    for prefix in included_prefixes:
        bits = prefix["generationBits"]
        for family, bit in FAMILY_BITS:
            if bits & bit:
                family_shape_members[family].append(prefix["name"])

    werkstoff_by_name, display_to_var = group_werkstoffs(werkstoffs)
    validate_werkstoff_prefixes(werkstoff_by_name, included_names)
    werkstoff_referenced = compute_werkstoff_referenced_names(werkstoff_by_name, display_to_var)
    werkstoff_names = {name for name, info in werkstoff_by_name.items() if info["entries"]}

    base_ported, _ = compute_ported(materials)
    base_ported_names = set(m["name"] for m in base_ported)
    ported, skipped = compute_ported(materials, werkstoff_referenced, werkstoff_names)
    ported_name_set = set(m["name"] for m in ported)
    missing_targets = sorted(set(werkstoff_by_name) - ported_name_set)
    if missing_targets:
        raise SystemExit(
            f"gen_materials.py: werkstoff fold targets missing from the gregtech dump/ported set: "
            f"{missing_targets}")

    ml_names, field_names = assign_names(ported)
    families_by_name = {}
    for m in ported:
        prefix_names = list(m["generatedPrefixes"])
        werkstoff_info = werkstoff_by_name.get(m["name"])
        if werkstoff_info:
            prefix_names += werkstoff_info["prefixes"]
        families_by_name[m["name"]] = joined_families(prefix_names, prefix_bits)

    batches = list(chunk(ported, MATERIALS_PER_FILE))
    MATERIALS2_DIR.mkdir(parents=True, exist_ok=True)
    data_class_names = []
    used_fluid_names = set()
    for i, batch in enumerate(batches, start=1):
        data_class_names.append(
            write_data_file(
                i, batch, families_by_name, ml_names, field_names, included_names, family_shape_members,
                legacy_variants_by_material, used_fluid_names, fluid_textures, legacy_block_materials,
                werkstoff_by_name, display_to_var))

    write_materials_file(ported, field_names, data_class_names)
    write_lang_file(ported, ml_names)

    ported_names = set(ml_names.keys())
    materials_by_name = {m["name"]: m for m in ported}
    bridge_count, retained_fields = write_legacy_bridge_file(ported_names, field_names, materials_by_name)

    gt_by_name = {m["name"]: m for m in materials}
    merged_count, revived_count, newly_referenced = write_merge_report(
        werkstoff_by_name, gt_by_name, base_ported_names, ported_name_set)

    print(f"gen_materials.py: {len(materials)} dump entries, {len(ported)} ported, {len(skipped)} skipped")
    print(
        f"  werkstoff fold: {sum(len(i['entries']) for i in werkstoff_by_name.values())} pool entries onto "
        f"{len(werkstoff_names)} declarations ({merged_count} merged, {revived_count} revived mirrors), "
        f"{len(newly_referenced)} newly referenced markers ({', '.join(newly_referenced)}); see "
        f"{MERGE_REPORT_PATH.relative_to(REPO_ROOT)}")
    print(f"  wrote {len(data_class_names)} data files + {MATERIALS_OUTPUT.relative_to(REPO_ROOT)}")
    print(f"  wrote {LANG_OUTPUT.relative_to(REPO_ROOT)}")
    captured = sum(1 for name in used_fluid_names if fluid_textures.get(name))
    print(
        f"  fluid textures: {captured}/{len(used_fluid_names)} generated fluid shapes captured a texture "
        f"({len(used_fluid_names) - captured} fall back to texture-set lookup)")
    uncaptured = sorted(name for name in used_fluid_names if not fluid_textures.get(name))
    if uncaptured:
        print(f"  fluids with no captured texture: {', '.join(uncaptured)}")
    if bridge_count is not None:
        print(
            f"  wrote {LEGACY_BRIDGE_OUTPUT.relative_to(REPO_ROOT)}: {bridge_count} bridged fields, "
            f"{len(retained_fields)} retained as markers (see LegacyMarkerMaterials.loadMarkers)")
    block_cutover = sorted(
        m["name"] for m in ported if m["name"] in legacy_block_materials and m["name"] not in BLOCK_CUTOVER_EXCLUDED)
    block_excluded = sorted(legacy_block_materials & BLOCK_CUTOVER_EXCLUDED)
    print(
        f"  block shape: {len(legacy_block_materials)} legacy storage-block materials, "
        f"{len(block_cutover)} cut over, {len(block_excluded)} excluded (structural references): "
        f"{', '.join(block_excluded)}")


if __name__ == "__main__":
    main()
