#!/usr/bin/env python3
"""Generates the stage-02 MaterialLib shape declarations, capability families, and GT shape data
registry from the `oreprefixes.json` material-unification dump.

Run from anywhere; paths are resolved relative to this script's location. Requires only the
Python 3 standard library.

Usage: python scripts/mu/gen_shapes.py
"""

import json
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
DUMP_PATH = SCRIPT_DIR / "dumps" / "oreprefixes.json"
LEGACY_VARIANTS_PATH = SCRIPT_DIR / "dumps" / "legacy-variants.json"

SHAPES_OUTPUT = REPO_ROOT / "src/main/java/gregtech/api/enums/materials2/Materials2Shapes.java"
FAMILIES_OUTPUT = REPO_ROOT / "src/main/java/gregtech/api/enums/materials2/Materials2Families.java"
SHAPE_DATA_OUTPUT = REPO_ROOT / "src/main/java/gregtech/api/material/ShapeData.java"

GENERATED_HEADER = "// Generated by scripts/mu/gen_shapes.py; edit the script, not this file."

# gregtech.api.enums.OrePrefixes generation-bit constants (mirrored here since the dump only carries the
# combined int).
DUST = 1
METAL = 2
GEM = 4
ORE = 8
CELL = 16
PLASMA = 32
TOOL = 64
GEAR = 128
EMPTY = 256

FAMILY_BITS = [
    ("familyDusts", DUST),
    ("familyMetals", METAL),
    ("familyGems", GEM),
    ("familyOres", ORE),
    ("familyCells", CELL),
    ("familyPlasmas", PLASMA),
    ("familyToolParts", TOOL),
    ("familyGears", GEAR),
    ("familyEmpties", EMPTY),
]

# gregtech.api.enums.MaterialIconRegistry.IconType ordinals 65-95 (VOID_14 through VOID_24) are the block
# and block-with-alpha textures (ORE_SMALL, ORE, WIRE, FOIL_2, BLOCK1-6, PIPE_*, FRAME_GT, SHEETMETAL); the
# dump does not carry IconType.texture (TextureType), so this range is hardcoded from that source file.
BLOCK_TEXTURE_INDEX_MIN = 65
BLOCK_TEXTURE_INDEX_MAX = 95


def is_block_kind(prefix):
    name = prefix["name"]
    if name in ("block", "frameGt"):
        return True
    if name.startswith("ore") and name != "rawOre":
        return True
    texture_index = prefix.get("textureIndex", -1)
    if texture_index is not None and BLOCK_TEXTURE_INDEX_MIN <= texture_index <= BLOCK_TEXTURE_INDEX_MAX:
        return True
    return False


def is_complex_tool_or_armor(prefix):
    """`tool`/`armor` and their concrete variants (toolPickaxe, armorHelmet, ...) are full crafted tools with
    durability and enchantments, not plain material items; GT keeps generating these itself. `toolHead*`
    prefixes are plain drill-tip/hammer-head style items and stay included."""
    name = prefix["name"]
    if name in ("tool", "armor"):
        return True
    if name.startswith("tool") and not name.startswith("toolHead"):
        return True
    if name.startswith("armor"):
        return True
    return False


def is_included_by_capability_bits(prefix):
    """Historical stage-02 filter, kept as a necessary (but not sufficient, see `is_included`) condition: a
    prefix with zero generation bits, non-material-based, a container, block-kind, or a complex tool/armor
    shape was never a valid MaterialLib item shape regardless of what legacy items existed for it."""
    if prefix["generationBits"] == 0:
        return False
    if not prefix["isMaterialBased"]:
        return False
    if prefix["isContainer"]:
        return False
    if is_block_kind(prefix):
        return False
    if is_complex_tool_or_armor(prefix):
        return False
    return True


def load_legacy_variant_prefixes():
    """Prefix names that `MetaGeneratedItemX32.DUMP_VARIANTS` actually constructed a legacy item for (see
    `MaterialDataDump.dumpLegacyVariants`) -- ground truth for which prefixes held a real constructor slot,
    as opposed to `doGenerateItem` capability bits alone."""
    with open(LEGACY_VARIANTS_PATH, encoding="utf-8") as f:
        variants = json.load(f)
    return {v["prefix"] for v in variants}


def is_included(prefix, legacy_variant_prefixes):
    if not is_included_by_capability_bits(prefix):
        return False
    # Bugfix: the capability-bit filter above overcounts -- 15 prefixes (bullets, cleanGravel, clump,
    # crystal, crystalline, dirtyGravel, dustRefined, handleMallet, milled, reduced, shard, toolHeadMallet,
    # toolHeadScrewdriver) pass it but never held a slot in MetaGeneratedItem01/02/03's constructor, so no
    # legacy item for them ever existed; cutting them over produced bogus MaterialLib items with no texture.
    # Intersect with legacy-variants.json rather than replace the filter, so this bugfix can only SHRINK the
    # shape set, never grow it: legacy-variants.json legitimately contains prefixes the filter above already
    # excludes for other reasons (e.g. nanite has a constructor slot and real legacy variants, but is
    # intentionally not a cutover shape -- it stays a legacy item).
    return prefix["name"] in legacy_variant_prefixes


def load_included_prefixes():
    with open(DUMP_PATH, encoding="utf-8") as f:
        dump = json.load(f)
    legacy_variant_prefixes = load_legacy_variant_prefixes()
    prefixes = [p for p in dump["prefixes"] if is_included(p, legacy_variant_prefixes)]
    prefixes.sort(key=lambda p: p["name"])
    return prefixes


def load_dropped_prefixes():
    """Prefixes the old capability-bit filter alone would have included, that the legacy-variants
    intersection now excludes -- for reporting, not consumed by codegen."""
    with open(DUMP_PATH, encoding="utf-8") as f:
        dump = json.load(f)
    legacy_variant_prefixes = load_legacy_variant_prefixes()
    return sorted(
        p["name"]
        for p in dump["prefixes"]
        if is_included_by_capability_bits(p) and p["name"] not in legacy_variant_prefixes
    )


def shape_field_name(prefix_name):
    return "shape" + prefix_name[0].upper() + prefix_name[1:]


def java_string_literal(value):
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return '"' + escaped + '"'


def write_shapes_file(prefixes):
    lines = []
    lines.append("package gregtech.api.enums.materials2;")
    lines.append("")
    lines.append("import com.ruling_0.materiallib.api.MaterialLibAPI;")
    lines.append("import com.ruling_0.materiallib.api.Shape;")
    lines.append("")
    lines.append(GENERATED_HEADER)
    lines.append(
        "/// One [Shape] field per material-driven ITEM `OrePrefixes` entry from `dumps/oreprefixes.json` with"
    )
    lines.append(
        "/// a non-zero generation bit mask, excluding block-kind, fluid-container, and complex tool/armor"
    )
    lines.append("/// prefixes (see `scripts/mu/gen_shapes.py`).")
    lines.append("public class Materials2Shapes {")
    lines.append("")
    lines.append("    // spotless:off")
    for prefix in prefixes:
        lines.append(f"    public static Shape {shape_field_name(prefix['name'])};")
    lines.append("    // spotless:on")
    lines.append("")
    lines.append("    public static void init() {")
    for prefix in prefixes:
        field = shape_field_name(prefix["name"])
        name_literal = java_string_literal(prefix["name"])
        format_literal = java_string_literal(prefix["localNameFormat"])
        lines.append(f"        {field} = MaterialLibAPI.newItemShape(\"gregtech\", {name_literal})")
        lines.append(f"            .displayName({format_literal})")
        lines.append("            .build();")
    lines.append("    }")
    lines.append("")
    lines.append("    private Materials2Shapes() {}")
    lines.append("}")
    lines.append("")
    SHAPES_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    SHAPES_OUTPUT.write_text("\n".join(lines), encoding="utf-8")


def write_families_file(prefixes):
    family_members = {family_name: [] for family_name, _ in FAMILY_BITS}
    for prefix in prefixes:
        bits = prefix["generationBits"]
        for family_name, bit in FAMILY_BITS:
            if bits & bit:
                family_members[family_name].append(prefix["name"])

    lines = []
    lines.append("package gregtech.api.enums.materials2;")
    lines.append("")
    lines.append("import com.ruling_0.materiallib.api.Family;")
    lines.append("import com.ruling_0.materiallib.api.MaterialLibAPI;")
    lines.append("import com.ruling_0.materiallib.api.StandardProperties;")
    lines.append("import com.ruling_0.materiallib.api.TextureSet;")
    lines.append("")
    lines.append(GENERATED_HEADER)
    lines.append("/// Capability families mirroring the legacy `OrePrefixes` generation-bit groups (`DUST`, `METAL`,")
    lines.append("/// `GEM`, `ORE`, `CELL`, `PLASMA`, `TOOL`, `GEAR`, `EMPTY`). A shape with generation bits `B` joins")
    lines.append("/// every family whose bit is set in `B`, which over-generates relative to the legacy AND/OR")
    lines.append("/// capability logic where a material's own bits must also overlap; stage 03's codegen corrects")
    lines.append("/// per-material differences with explicit `generateShape`/`removeShape` deltas computed from the")
    lines.append("/// dumped `generatedPrefixes` ground truth.")
    lines.append("public class Materials2Families {")
    lines.append("")
    lines.append("    // spotless:off")
    lines.append("    public static Family familyAll;")
    for family_name, _ in FAMILY_BITS:
        lines.append(f"    public static Family {family_name};")
    lines.append("    // spotless:on")
    lines.append("")
    lines.append("    public static void init() {")
    lines.append("        familyAll = MaterialLibAPI.newFamily(\"gregtech\", \"All\")")
    lines.append(
        "            .setProperty(StandardProperties.FALLBACK_TEXTURE_SET, TextureSet.of(\"gregtech\", \"NONE\"))"
    )
    lines.append("            .build();")
    lines.append("")
    for family_name, bit in FAMILY_BITS:
        members = family_members[family_name]
        family_key = family_name[len("family"):]
        lines.append(f"        {family_name} = MaterialLibAPI.newFamily(\"gregtech\", {java_string_literal(family_key)})")
        if members:
            lines.append("            .generateShapes(")
            shape_refs = ", ".join(f"Materials2Shapes.{shape_field_name(name)}" for name in members)
            lines.append(f"                {shape_refs})")
        lines.append("            .build();")
    lines.append("    }")
    lines.append("")
    lines.append("    private Materials2Families() {}")
    lines.append("}")
    lines.append("")
    FAMILIES_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    FAMILIES_OUTPUT.write_text("\n".join(lines), encoding="utf-8")


def java_material_ref_stack(secondary_material):
    if secondary_material is None:
        return "null"
    material_literal = java_string_literal(secondary_material["material"])
    amount = secondary_material["amount"]
    return f"new MaterialRefStack(new MaterialRef({material_literal}), {amount}L)"


def write_shape_data_file(prefixes):
    lines = []
    lines.append("package gregtech.api.material;")
    lines.append("")
    lines.append("import java.util.HashMap;")
    lines.append("import java.util.Map;")
    lines.append("")
    lines.append("import com.ruling_0.materiallib.api.Shape;")
    lines.append("")
    lines.append(GENERATED_HEADER)
    lines.append("/// Per-shape data the recipe and recycling code needs, sourced from each `OrePrefixes` entry's")
    lines.append("/// `materialAmount`, `secondaryMaterial`, `defaultStackSize`, `isRecyclable`, `isEnchantable`, and")
    lines.append("/// `isUnifiable` in `dumps/oreprefixes.json`. Kept GT-side because every consumer (recycling math,")
    lines.append("/// cell recipes, tool logic) is in-repo; MaterialLib does not need per-shape properties for the")
    lines.append("/// unification.")
    lines.append("public class ShapeData {")
    lines.append("")
    lines.append("    private static final Map<String, Long> MATERIAL_AMOUNT = new HashMap<>();")
    lines.append("    private static final Map<String, MaterialRefStack> SECONDARY_MATERIAL = new HashMap<>();")
    lines.append("    private static final Map<String, Integer> DEFAULT_STACK_SIZE = new HashMap<>();")
    lines.append("    private static final Map<String, Boolean> RECYCLABLE = new HashMap<>();")
    lines.append("    private static final Map<String, Boolean> ENCHANTABLE = new HashMap<>();")
    lines.append("    private static final Map<String, Boolean> UNIFIABLE = new HashMap<>();")
    lines.append("")
    lines.append("    static {")
    lines.append("        // spotless:off")
    for prefix in prefixes:
        name_literal = java_string_literal(prefix["name"])
        lines.append(f"        MATERIAL_AMOUNT.put({name_literal}, {prefix['materialAmount']}L);")
        secondary = java_material_ref_stack(prefix.get("secondaryMaterial"))
        if secondary != "null":
            lines.append(f"        SECONDARY_MATERIAL.put({name_literal}, {secondary});")
        lines.append(f"        DEFAULT_STACK_SIZE.put({name_literal}, {prefix['defaultStackSize']});")
        lines.append(f"        RECYCLABLE.put({name_literal}, {str(bool(prefix['isRecyclable'])).lower()});")
        lines.append(f"        ENCHANTABLE.put({name_literal}, {str(bool(prefix['isEnchantable'])).lower()});")
        lines.append(f"        UNIFIABLE.put({name_literal}, {str(bool(prefix['isUnifiable'])).lower()});")
    lines.append("        // spotless:on")
    lines.append("    }")
    lines.append("")
    lines.append("    /// The amount of the shape's own material one item represents (`GTValues.M` = one ingot), or")
    lines.append("    /// -1 for a shape this registry has no data for.")
    lines.append("    public static long materialAmount(String shapeName) {")
    lines.append("        return MATERIAL_AMOUNT.getOrDefault(shapeName, -1L);")
    lines.append("    }")
    lines.append("")
    lines.append("    public static long materialAmount(Shape shape) {")
    lines.append("        return materialAmount(shape.getName());")
    lines.append("    }")
    lines.append("")
    lines.append("    /// The secondary material and amount consumed alongside the shape's own material (e.g. the")
    lines.append("    /// tin plates a cell is stamped from), or null when the shape has none.")
    lines.append("    public static MaterialRefStack secondaryMaterial(String shapeName) {")
    lines.append("        return SECONDARY_MATERIAL.get(shapeName);")
    lines.append("    }")
    lines.append("")
    lines.append("    public static MaterialRefStack secondaryMaterial(Shape shape) {")
    lines.append("        return secondaryMaterial(shape.getName());")
    lines.append("    }")
    lines.append("")
    lines.append("    public static int defaultStackSize(String shapeName) {")
    lines.append("        return DEFAULT_STACK_SIZE.getOrDefault(shapeName, 64);")
    lines.append("    }")
    lines.append("")
    lines.append("    public static int defaultStackSize(Shape shape) {")
    lines.append("        return defaultStackSize(shape.getName());")
    lines.append("    }")
    lines.append("")
    lines.append("    public static boolean isRecyclable(String shapeName) {")
    lines.append("        return RECYCLABLE.getOrDefault(shapeName, false);")
    lines.append("    }")
    lines.append("")
    lines.append("    public static boolean isRecyclable(Shape shape) {")
    lines.append("        return isRecyclable(shape.getName());")
    lines.append("    }")
    lines.append("")
    lines.append("    public static boolean isEnchantable(String shapeName) {")
    lines.append("        return ENCHANTABLE.getOrDefault(shapeName, false);")
    lines.append("    }")
    lines.append("")
    lines.append("    public static boolean isEnchantable(Shape shape) {")
    lines.append("        return isEnchantable(shape.getName());")
    lines.append("    }")
    lines.append("")
    lines.append("    public static boolean isUnifiable(String shapeName) {")
    lines.append("        return UNIFIABLE.getOrDefault(shapeName, false);")
    lines.append("    }")
    lines.append("")
    lines.append("    public static boolean isUnifiable(Shape shape) {")
    lines.append("        return isUnifiable(shape.getName());")
    lines.append("    }")
    lines.append("")
    lines.append("    private ShapeData() {}")
    lines.append("}")
    lines.append("")
    SHAPE_DATA_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    SHAPE_DATA_OUTPUT.write_text("\n".join(lines), encoding="utf-8")


def main():
    prefixes = load_included_prefixes()
    write_shapes_file(prefixes)
    write_families_file(prefixes)
    write_shape_data_file(prefixes)
    print(f"gen_shapes.py: {len(prefixes)} shapes included")
    print(f"  wrote {SHAPES_OUTPUT.relative_to(REPO_ROOT)}")
    print(f"  wrote {FAMILIES_OUTPUT.relative_to(REPO_ROOT)}")
    print(f"  wrote {SHAPE_DATA_OUTPUT.relative_to(REPO_ROOT)}")

    dropped = load_dropped_prefixes()
    print(f"  dropped {len(dropped)} prefixes with no real legacy item: {', '.join(dropped)}")

    legacy_variant_prefixes = load_legacy_variant_prefixes()
    included_names = {p["name"] for p in prefixes}
    variants_not_cutover = sorted(legacy_variant_prefixes - included_names)
    print(
        f"  {len(variants_not_cutover)} prefixes have real legacy variants but are not cutover shapes "
        f"(follow-up decision, e.g. nanite): {', '.join(variants_not_cutover)}"
    )


if __name__ == "__main__":
    main()
