#!/usr/bin/env python3
"""Generates the gtPlusPlus ore-cutover Postea transformer table from `gtpp-ores.json` (a
supplementary, non-pinned dump -- see `MaterialDataDump#dumpGtppOres` -- of every legacy `BlockBaseOre`
registry name, sourced by scanning the live block registry since `BlockBaseOre` never populates
`Material.mComponentMap` the way every other legacy part item does). One (unlocalized name, registry name)
row per gtpp ore material; `PosteaTransformers` registers an item AND a block-placement migration handler per
row, resolving through `MaterialReconstruction#materialLibOf` + `MU.stack(OrePrefixes.ore, ..., 1)` -- the same
resolution `GTPPOreAdapter#getBlock` uses live.

Run from anywhere; paths are resolved relative to this script's location. Requires only the Python 3 standard
library.

Usage: python scripts/mu/gen_gtpp_ore_transformers.py
"""

import json
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
DUMP_PATH = SCRIPT_DIR / "dumps" / "gtpp-ores.json"

OUTPUT = REPO_ROOT / "src/main/java/gregtech/loaders/postload/GtppOreCutoverTable.java"

GENERATED_HEADER = "// Generated by scripts/mu/gen_gtpp_ore_transformers.py; edit the script, not this file."


def load_rows():
    entries = json.loads(DUMP_PATH.read_text(encoding="utf-8"))
    rows = [(e["unlocalizedName"], e["registryName"]) for e in entries]
    rows.sort()
    return rows


def java_string(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def generate(rows):
    lines = []
    lines.append(GENERATED_HEADER)
    lines.append("package gregtech.loaders.postload;")
    lines.append("")
    lines.append("/// The gtPlusPlus ore-cutover Postea migration table: one row per legacy")
    lines.append("/// `BlockBaseOre` instance, read from the supplementary `gtpp-ores.json` dump (see")
    lines.append("/// `MaterialDataDump#dumpGtppOres`, not itself pinned like `gtpp-materials.json`). [PosteaTransformers]")
    lines.append("/// migrates each row's legacy placed block/item stack to `MU.stack(OrePrefixes.ore,")
    lines.append('/// MaterialReconstruction.materialLibOf(unlocalizedName), 1)` -- see')
    lines.append("/// `scripts/mu/gen_gtpp_ore_transformers.py`. A material that never gained")
    lines.append("/// `Materials2OreShapes#shapeOre` membership resolves null and is left on its legacy slot.")
    lines.append("public final class GtppOreCutoverTable {")
    lines.append("")
    lines.append("    public record Entry(String unlocalizedName, String registryName) {}")
    lines.append("")
    lines.append("    private GtppOreCutoverTable() {}")
    lines.append("")
    lines.append("    // spotless:off")
    lines.append("    public static final Entry[] ENTRIES = new Entry[] {")
    for name, registry_name in rows:
        lines.append(f"        new Entry({java_string(name)}, {java_string(registry_name)}),")
    lines.append("    };")
    lines.append("    // spotless:on")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    rows = load_rows()
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generate(rows), encoding="utf-8", newline="\n")
    print(f"Wrote {len(rows)} entries to {OUTPUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
