#!/usr/bin/env python3
"""Generates the stage-02 MaterialLib item shape declarations from the `oreprefixes.json`
material-unification dump.

Run from anywhere; paths are resolved relative to this script's location. Requires only the
Python 3 standard library.

Usage: python scripts/mu/gen_shapes.py
"""

import json
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent.parent
DUMP_PATH = SCRIPT_DIR / "dumps" / "oreprefixes.json"

SHAPES_OUTPUT = REPO_ROOT / "src/main/java/gregtech/api/enums/materials2/Materials2Shapes.java"

GENERATED_HEADER = "// Generated by scripts/mu/gen_shapes.py; edit the script, not this file."

# gregtech.api.enums.MaterialIconRegistry.IconType ordinals 65-95 (VOID_14 through VOID_24) are the block
# and block-with-alpha textures (ORE_SMALL, ORE, WIRE, FOIL_2, BLOCK1-6, PIPE_*, FRAME_GT, SHEETMETAL); the
# dump does not carry IconType.texture (TextureType), so this range is hardcoded from that source file.
BLOCK_TEXTURE_INDEX_MIN = 65
BLOCK_TEXTURE_INDEX_MAX = 95


def is_block_kind(prefix):
    name = prefix["name"]
    if name in ("block", "frameGt"):
        return True
    if name.startswith("ore") and name != "rawOre":
        return True
    texture_index = prefix.get("textureIndex", -1)
    if texture_index is not None and BLOCK_TEXTURE_INDEX_MIN <= texture_index <= BLOCK_TEXTURE_INDEX_MAX:
        return True
    return False


def is_complex_tool_or_armor(prefix):
    """`tool`/`armor` and their concrete variants (toolPickaxe, armorHelmet, ...) are full crafted tools with
    durability and enchantments, not plain material items; GT keeps generating these itself. `toolHead*`
    prefixes are plain drill-tip/hammer-head style items and stay included."""
    name = prefix["name"]
    if name in ("tool", "armor"):
        return True
    if name.startswith("tool") and not name.startswith("toolHead"):
        return True
    if name.startswith("armor"):
        return True
    return False


def is_included(prefix):
    if prefix["generationBits"] == 0:
        return False
    if not prefix["isMaterialBased"]:
        return False
    if prefix["isContainer"]:
        return False
    if is_block_kind(prefix):
        return False
    if is_complex_tool_or_armor(prefix):
        return False
    return True


def load_included_prefixes():
    with open(DUMP_PATH, encoding="utf-8") as f:
        dump = json.load(f)
    prefixes = [p for p in dump["prefixes"] if is_included(p)]
    prefixes.sort(key=lambda p: p["name"])
    return prefixes


def shape_field_name(prefix_name):
    return "shape" + prefix_name[0].upper() + prefix_name[1:]


def java_string_literal(value):
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return '"' + escaped + '"'


def write_shapes_file(prefixes):
    lines = []
    lines.append("package gregtech.api.enums.materials2;")
    lines.append("")
    lines.append("import com.ruling_0.materiallib.api.MaterialLibAPI;")
    lines.append("import com.ruling_0.materiallib.api.Shape;")
    lines.append("")
    lines.append(GENERATED_HEADER)
    lines.append(
        "/// One [Shape] field per material-driven ITEM `OrePrefixes` entry from `dumps/oreprefixes.json` with"
    )
    lines.append(
        "/// a non-zero generation bit mask, excluding block-kind, fluid-container, and complex tool/armor"
    )
    lines.append("/// prefixes (see `scripts/mu/gen_shapes.py`).")
    lines.append("public class Materials2Shapes {")
    lines.append("")
    lines.append("    // spotless:off")
    for prefix in prefixes:
        lines.append(f"    public static Shape {shape_field_name(prefix['name'])};")
    lines.append("    // spotless:on")
    lines.append("")
    lines.append("    public static void init() {")
    for prefix in prefixes:
        field = shape_field_name(prefix["name"])
        name_literal = java_string_literal(prefix["name"])
        format_literal = java_string_literal(prefix["localNameFormat"])
        lines.append(f"        {field} = MaterialLibAPI.newItemShape(\"gregtech\", {name_literal})")
        lines.append(f"            .displayName({format_literal})")
        lines.append("            .build();")
    lines.append("    }")
    lines.append("")
    lines.append("    private Materials2Shapes() {}")
    lines.append("}")
    lines.append("")
    SHAPES_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    SHAPES_OUTPUT.write_text("\n".join(lines), encoding="utf-8")


def main():
    prefixes = load_included_prefixes()
    write_shapes_file(prefixes)
    print(f"gen_shapes.py: {len(prefixes)} shapes included")
    print(f"  wrote {SHAPES_OUTPUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
