name: Test integration in latest daily

on:
  workflow_run:
    workflows: ["Build and test"]
    types: [completed]

jobs:
  pack-test:
    name: Pack Test
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    container:
      image: ghcr.io/malteeez/gtnh-daily:latest

    steps:
      - name: Run pack test
        run: |
          bash /entrypoint.sh
