name: Forbidden System.out.print calls

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  test-forbidden-sysout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Detect forbidden System.out calls
        shell: bash
        run: |
          ! grep -E -r 'System.out.print' src/main/java || exit 1
