name: Test Scala Presence

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [ master, main ]

jobs:
  test-scala-presence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Detect scala presence
        shell: bash
        run: |
          ! grep -E -r 'import scala\.' src/main/java

